[1, 2단계 - Spring 적용하기] 웨지(성시형) 미션 제출합니다.
woowacourse/jwp-chess pull request #220
Opened 2021-04-14 07:03 UTC by sihyung92

안녕하세요 제이!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

또 만났네요 ^^
질문은 추후에 작성하겠습니다!! 

리뷰 잘 부탁드려요~~

2021-04-15 16:07 UTC, JunHoPark93 requested changes
안녕하세요 웨지!
또 만났네용ㅎㅎ 저도 반가워요 🥳
이번에도 많은 고민을 해주신거같아요!
몇 가지 코멘트 남겼는데 확인하시고 웨지의 의견도 남겨주세요 🙏

2021-04-15 16:07 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/ChessController.java
> +public class ChessController {
근데 테스트코드가 커밋이 안된건가요?
새로이 구현해주신 부분들에 대한 테스트코드 뿐만아니라 기존 체스에 대한 테스트코드가 보이질 않아서 말씀드렸습니다!

2021-04-15 16:41 UTC, sihyung92 commented on src/main/java/chess/service/ChessService.java
> +public interface ChessService {
SparkController가 기존의 ChessService를 활용하고 있었습니다!
기존의 콘솔 및 Spark방식도 유지하는게 목표였기 때문에 기존의 ChessService를 재활용하기 위해 인터페이스화 하고, 
 스프링에서 사용할 Service, Spark에서 사용할 Service를 만들었다가 둘의 차이점이 없어 하나로 줄이는 과정에서 ChessService 인터페이스 하나, 구현체도 하나로 남게 되었습니다.
 
 그러나 Service에 대한 명세가 드러나고 ChessService와 컨트롤러와의 결합도를 낮추어주므로 굳이 인터페이스 구현 전으로 돌아가야한다고 생각하진 않습니다!

2021-04-15 16:45 UTC, sihyung92 commented on src/main/java/chess/controller/web/ChessController.java
> +    @PostMapping("/game/move")
나중에 user와 하위 path를 고려하고 있기 때문에 game이라는 컨트롤러를 따로 정의하도록 하겠습니다!

2021-04-15 16:46 UTC, sihyung92 commented on src/main/java/chess/controller/web/dto/MoveRequestDto.java
> +    private final long id;
네 gameId가 맞습니다~! id를 활용하는 곳이 많은데 확인하고 네이밍을 변경하도록 하겠습니다

2021-04-15 16:51 UTC, sihyung92 commented on src/main/java/chess/controller/web/ChessController.java
> +    public MoveResponseDto movePiece(@RequestBody MoveRequestDto moveMessage) {
오? ResponseEntity는 ResponseBody에 추가로 header와 status, message의 등의 메타데이터를 수정할 수 있는 객체라고 이번에 학습해서, 클라이언트 입장에선 동일한 Json객체를 받는거라고 생각하고 있었습니다.
Postman에서 쏴보고 결과물의 차이점을 이해한 후에 수정하겠습니다!

2021-04-15 17:00 UTC, sihyung92 commented on src/main/java/chess/controller/web/ChessController.java
> +        return ResponseEntity.badRequest().body(new ErrorMessageResponseDto(e.getMessage()));
비즈니스 로직 상에서 나는 에러(IllegalArgumentException 등등) 들은 badRequest 맞는데? 하다가..
SqlException도 있고 설계상 실수로 인한 NPE등도 있고.. 500에러도 있구나!!!
구분해줘야겠다는 생각이 들었습니다. 

현재 비즈니스 로직상에 나고 있는 IllegalArgumentException, UnsupportedOperationException, NoSuchElementException, IllegalStateException에 대해서만 badRequest로 반응하도록 수정하겠습니다!

추가 질문으로 체스에서 custom exception의 구현 필요성에 대해 저번 리뷰어에게서는 `필요하지 않다고  생각한다` 는 피드백을 받았는데요, 제이는 어떤 의견을 가지고 계신지 궁금합니다!

2021-04-15 17:05 UTC, sihyung92 commented on src/main/java/chess/controller/web/ChessController.java
> +public class ChessController {
이번 미션에 대한 요구사항 중 테스트 코드에 대한 내용이 없어서 테스트 패키지를 이전하지 않았는데, 테스트 코드의 중요도를 생각해보면 상당히 부끄러운 행동이라는 생각이 듭니다아.................ㅠㅠ

기존 테스트 코드를 이전하고, 이번 스프링 적응을 위한 샘플 코드 미션에서 `RestAssured` 라는 라이브러리를 활용하여 테스트 하던 부분이 인상깊어 해당 코드로 api테스트도 진행해보도록~! 하겠습니다!

2021-04-15 17:15 UTC, sihyung92 commented on src/main/java/chess/domain/repository/ChessGameRepository.java
> +    private final ChessDao chessDao;
네 생각을 정리하는데 조금 더 도움이 되었습니다!

질문으로 Repository 에서 dao를 분리하려고 하는 것에 대해선 어떻게 생각하시나요? 

> 만약 Controller, Service가 없었다면 Repository가 Dao를 포함하여도 무관하였을 것이다. 어디선가 DB접근에 대한 결합이 필요하기 때문이다. 그런데 Dao에 대한 결합을 수행해줄 Service계층이 있다면, Repository는 Dao와의 연관관계를 가질 필요가 없다.

위의 생각에 의거해서 chessgameRepository를 예로들면 dao대신 chessgameBundle 같은 일급컬렉션으로 의존을 바꾸어주고, Service만 Dao와 의존하여 도메인과 Dao를 격리시키고자 했습니다. 
또 어찌 생각하면 지금 상태처럼 Dao를 인터페이스화 하여 Repository가 추상화된 dao에 의존하게 한다면, 충분히 결합이 느슨한거 같기도 하고.. 🤔 어렵네요오

2021-04-15 17:36 UTC, sihyung92 commented on src/main/java/chess/domain/repository/ChessGameRepository.java
> +public class ChessGameRepository {
@Repository가 아닌 @Service인 이유를 여쭤보신거라고 생각하면 될까요?
붙일때만 해도 Dao만이 @Repository에 걸맞는 다고 생각해서 현재 ChessGameRepository는 Service의 연장선이야..라는 느낌으로 달아주었는데 질문을 받고보니 @Repository가 더 맞다는 생각이 드네용

스프링에서 붙이는 @Repository와 DDD에서 말하는 Repository는 다르다는 생각을 가지고 있었고, 그래서 Repository를 붙여주는 것에 무의식적으로 거부감이 있었던 것 같습니당!

 말씀해주신 
 
 > 그래서 구조를 chessgame 하위에 domain, repository 가 있고 domain 하위에 board, manager, order 등등을 위치시키는건 어떨까요? 그리고 repository밑에는 이 클래스가 위치하고요.
 
 를 적용하면 현재구조에서 chess.domain.repository 가 chess.repository로만 이동하면 될 것 같은데, 의도하신 바와 맞을까요?

2021-04-16 09:24 UTC, JunHoPark93 commented on src/main/java/chess/domain/repository/ChessGameRepository.java
> +public class ChessGameRepository {
음 새벽에 남겨서 그런지 주저리주저리 말이 많았네요 😂
제정신으로 다시보고 나니 모호하게 드린거같아요. 구조에 대해서는 따로질문주셔서 어느정도 방향성은 이야기 나누었고요! 
다음에는 좀 더 명확하게 드리도록 하겠습니다 🙏

2021-04-16 09:48 UTC, JunHoPark93 commented on src/main/java/chess/domain/repository/ChessGameRepository.java
> +    private final ChessDao chessDao;
따로말씀주신 -> _dao를 인터페이스로  추상화하여 다형성이 필요한 부분에서 활용중이고, repository같은 경우엔 현재 한가지 구현체로 활용하기 때문에 따로 인터페이스화 하지 않았다_

이 부분에 대해서는 구현체가 하나인데 인터페이스를 쓰는게 이상하다 라고 생각하신부분에 공감해요 지금도 좋습니다!
추후 미션을 진행하시면서 여러 구조를 보게 되실 텐데 그 때 다시 고민해보셔도 좋습니다

2021-04-16 09:50 UTC, JunHoPark93 commented on src/main/java/chess/service/ChessService.java
> +public interface ChessService {
기존에 구현체가 2개였군요. 그부분은 히스토리를 알지못해서 단순히 인터페이스를 만든줄알았어요 ㅎㅎ

2021-04-16 10:04 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/ChessController.java
> +    public MoveResponseDto movePiece(@RequestBody MoveRequestDto moveMessage) {
작성해주신 ErrorMessageResponseDto가 응답 포맷을 따로 정의한게 아니었군요, 그래도 한가지로 통일하면 더 좋을거같아요!

2021-04-16 10:06 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/ChessController.java
> +        return ResponseEntity.badRequest().body(new ErrorMessageResponseDto(e.getMessage()));
이부분도 질문주셔서 말씀드렸어요! 저는 커스텀예외를 사용하면 비지니스적으로 더 와닿아서 좋다고 생각하는데 사람마다 생각은 다를 수 있으니까요

2021-04-16 10:08 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/ChessController.java
> +        return ResponseEntity.badRequest().body(new ErrorMessageResponseDto(e.getMessage()));
이부분도 따로 질문주셔서 말씀드렸어요! 커스텀예외관련해서는 사용한다면 비지니스적으로 더 와닿아서 좋다고 생각하는데 사람마다 생각은 다를 수 있으니까요

2021-04-18 11:08 UTC, sihyung92 commented
저번에 너무너무 감사했어요 제이
감동의 도가니였답니다...
피드백 반영과 repository를 interface화 해보았어요, 정말 새로운 개념이었고 눈이 뜨이는 기분이었습니다.

하지만 지금 구조에서 굳이 repository가 필요하지 않을거 같아 3단계를 진행하기 전에 Service -> Dao 구조로 리팩토링해서 작업할 것 같습니다. 
리뷰 감사합니다 🙇‍♂️

2021-04-20 14:44 UTC, JunHoPark93 approved these changes
피드백 반영하시느라 고생많으셨어요 🙏
저번에 코드 보여드린게 도움이 많이 되었다니 다행이네요!
항상 직접 해보고 부딪혀보면서 진행하는 모습이 멋져요 🥳
궁금한점 생기면 언제든 말씀주세요

2021-04-20 14:44 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/ExceptionAdvice.java
> +    public ResponseEntity<ErrorMessageResponseDto> handle(Exception e) {
다음 프로젝트를 할 때는 CustomException을 정의하여 사용해보시는 경험을 가져도 좋을거같아요 :)

2021-04-20 14:44 UTC, merged

2021-04-23 02:15 UTC, sihyung92 commented
# 웨지의 학습로그
모든 학습로그는 [링크](https://www.notion.so/4-1-62931784cbd34ec9b600df69b395ca04)에 모아두었습니다!

## NoClassDefFoundError 발생원인 및 해결
- 링크 참조
## 태그
- Debug, Exception

## 잭슨의 InvalidDefinitionException 발생원인 및 해결
- 링크 참조
## 태그
- Debug, Exception

## Field Injection VS Constructor Injection
- 링크 참조
## 태그 
- Spring, Spring Core
 
##  Request Header - Location
- 링크 참조
## 태그 
- Http, WEB

## RestAssured API
- 링크 참조
## 태그
- Test, Spring

## RequestMapping - Consumes, Produces
- 링크 참조
## 태그
- Spring, Spring MVC

## RequestMapping - url Pattern
- 링크 참조
## 태그 
- Spring, Spring MVC

## RequestMapping - params
- 링크 참조
## 태그
- Spring, Spring MVC

## RequestMapping - pathvariable
- 링크 참조
## 태그
- Spring, Spring MVC

## Spring - ResponseEntity
- 링크 참조
## 태그
- Spring, Spring MVC

## Request Mapping - ModelAttribute
- 링크 참조
## 태그
- Spring, Spring MVC

## Spring Controller Exception Handling
- 링크 참조 
## 태그
- Spring, Spring MVC

## AOP
- 링크 참조
## 태그
- Spring

## Spring Valid
- 링크 참조
## 태그
- Spring, validation

## JDBC Template - SqlParameterSource
- 링크 참조
## 태그
- Spring, Spring JDBC

## annotation - @EnableAutoConfiguration
- 링크 참조
## 태그
- Spring, Spring Annotation

## AOP, interceptor, filter의 차이
- 링크 참조
## 태그
- Spring

## 인터셉터
- 링크 참조
## 태그
- Spring

## Session과 JsessionID
- 링크 참조
## 태그
- WEB, Http

## 인터페이스와 구현체의 Layer 분리
- 링크 참조
## 태그
- Architecture