[1, 2단계 - Spring 적용하기] 손너잘(손민성) 미션 제출합니다.Step1
woowacourse/jwp-chess pull request #224
Opened 2021-04-14 11:29 UTC by bperhaps

안녕하세요 휴! 손너잘입니다!
이번 미션은 저번 소스에서 어노테이션만 붙이면 되어서 금방 끝냈네요!
다만 궁금한 점은, 제가 이전 소스에서 repository와 dao를 분리시키고, repository에서 dao와의 의존성을 만들어서 사용했었어요!
그래서 이번에 @Repository를 repository 클래스에 달고, jdbcTemplate 의존성 주입을 repository에서 받도록 했어요, 그리고 dao와 의존성을 연결해 줬어요. 괜찮은 방법이었을까요??

처음 하는거라 부족하게 많아요!! 앞으로 스프링 리뷰 잘 부탁드립니다!

2021-04-14 18:37 UTC, Hue9010 requested changes
손너잘 반가워요! 이번 리뷰를 맡은 휴입니다! 😸 

굉장히 빠르게 작업해주셨네요. 💯 그래서 저도 빠르게ㅎㅎ
몇가지 피드백과 안내사항 남겼는데 궁금한건 언제든 질문주세요!!

스프링, 생각했던 것 보다는 어려울 것 없죠(?) 😋

2021-04-14 18:37 UTC, Hue9010 commented on src/main/java/chess/repository/GameRepository.java
> +    }
> 다만 궁금한 점은, 제가 이전 소스에서 repository와 dao를 분리시키고, repository에서 dao와의 의존성을 만들어서 사용했었어요!
그래서 이번에 @repository를 repository 클래스에 달고, jdbcTemplate 의존성 주입을 repository에서 받도록 했어요, 그리고 dao와 의존성을 연결해 줬어요. 괜찮은 방법이었을까요??

아니요. 지금 구조를 보면 repository가 의존성을 가지는 대상은 dao고, dao가 의존성을 가지는 대상은 jdbcTemplate입니다.
그러면 repository한테 의존성을 주입한다 하면 의존성을 가지는 대상인 dao가 주입되야하겠죠? 하지만 지금은 repository가 의존성을 가지는 대상이 아닌 jdbcTemplate를 주입해주고 있습니다.

그리고 이는 repository한테 dao가 jdbcTemplate에 대한 의존성을 가진다는 걸 알려주고 있는 상황이죠. ChessDAO도 빈으로 관리되어 스프링이 의존성을 주입하게 Repository 혹은 Component 애노테이션을 추가해서 각자의 의존성을 주입 받게 수정해주세요!

2021-04-14 18:37 UTC, Hue9010 commented on build.gradle
>      implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
이번 단계 리뷰를 진행하면서 전제로 하고 있는 부분 안내드릴게요.
체스 관련 비즈니스 로직은 이전 단계 때 끝냈다고 보고 관련 피드백은 배제 할게요. 대신 스프링 적용에 있어 개선하면 좋을 부분이 있을 때만 안내드릴게요.

혹은 개인적으로 중요시하는 부분에 대해서 안내드릴 수도 있어요. (리뷰어마다 중요하게 보는게 다라 의견이 갈릴 수도 있습니다.ㅎㅎ) 하지만 이것도 별도로 체스 로직을 찾아보는게 아닌 service layer 기준으로 리뷰를 진행하다 보이는게 있을 때만 드릴 것 같아요.(대신 체스가 복잡하다 보니 로직에 관해 질문 드릴수도 있어요. 😋)

몇가지 이유가 있지만 가장 큰 이유는 이번 단계는 스프링을 적용해보고, 학습하는게 목적이라고 보기 때문에 이 부분에 집중하고자 합니다!

사실 웹 관련으로도 이전 spark때는 받지 못했던 피드백을 받을 수도 있는데(아닐수도.. 🙄) 저 포함 다른 리뷰어분들도 spark는 익숙치 않고 웹 적용 자체만 초점을 맞춰 뒀을 확률이 높답니다.

이런 안내글은 잘 안남기는 편인데 하나의 프로젝트를 콘솔 -> spark -> spring으로 끌고 오는 특수 케이스라 사전 안내드립니다. 😉
이점 참고 부탁드려요. 혹시 궁금한 점이나 그래도 이건 체크해줬으면 좋겠다 싶은 부분 있으면 말씀주세요! 🙏

2021-04-14 18:37 UTC, Hue9010 commented on src/main/resources/schema.sql
> +/*!50503 SET character_set_client = utf8mb4 */;
프로젝트 상에서는 불필요한 주석으로 보이는데 제거하죠. 😉 
\+ schema.sql은 현재 사용되지 활용하지 않는 걸로 보이고, table.sql은 테이블 ddl 제공 목적이 맞을까요? ㅎㅎ

2021-04-14 18:37 UTC, Hue9010 commented on src/main/resources/schema.sql
> +/*!50503 SET character_set_client = utf8mb4 */;
build.gradle을 보니 브라운이 h2를 추가해두셨는데 한번 h2를 사용해보죠. 😉
```java
runtimeOnly 'com.h2database:h2'
```
[SpringBoot에서 H2 데이터베이스 사용하기](https://youngjinmo.github.io/2020/03/h2-database/)
위 글에는 애플리케이션 종료 시 무조건 데이터가 사라지는 것 처럼 설명되어 있지만 설정에 따라 조금씩 다르답니다. 하지만 지금은 h2를 학습하는게 아닌 단순히 적용만 해보죠. 😉

2021-04-14 21:04 UTC, bperhaps commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost/chess"
헉.. 커밋하면서 잘못 눌렀나봐요... 수정하겠습니다!

2021-04-14 21:14 UTC, bperhaps commented on src/main/java/chess/service/MoveService.java
> +        Position targetPosition = getPositionFromInput(target);
> 그래서 단순 생성 가능한지 확인하는 질문이 아닌 비숍, 룩과 같이 멀리 이동(?)할 수 있는 말의 이동 가능 위치를 확인 할 때 체스판 범위를 벗어난 Position을 만드는지 궁금해요.

저같은 경우는 움직일 수 있는 위치를 계산하기 보다는, 사용자가 입력한 target 포지션과 현재 위치한 말의 포지션간의 수학적 계산(?)을 통해 말의 움직임을 정하고 있어요.
예를 들면, 룩의 경우
- source 포지션과 target 포지션의 column 또는 row가 같은가?
- 움직이려는 위치 사이에 말이 없는가?
- target에 아군 말이 없는가?
- target에 적군 말이 있는가?

등의 조건을 검사해요..

처음에 Position 클래스를 구상할 때, Position을 체스게임의 룰에 국한되지 않는다고 생각했어요. 객체의 책임과 역할의 관점에서 볼 때, Position의 책임은 단순히 "위치" 그 자체라고 생각해서 validation 로직을 따로 생성자에 넣지 않았었어요.

아마 Service 로직에 validation 같은 비즈니스 로직이 들어간걸로 인해서 피드백 주신 것 같은데 저도 사실 이 부분이 엄청 거슬렸(?)습니다... 제가 알기로 서비스에는 "흐름제어" 만이 존재해야 하는데, 로직일 들어가 버려서요... 근데, 저 소스를 작성할 당시에 "도메인 주도 설계 철저 입문" 이라는 책에서 Application Service 부분을 읽었던걸로 기억하는데 그때 Serivce 로직에 validation 로직을 넣는게 가능하다(?) 혹은 예시 코드에 그런 로직이 있었어서 넣었던걸로 기억해요.

지금생각하니까 뭔가... DDD하고 제가 알고있는 레이어간의 역할하고 잘 안맞는 것 같다(?)라는 생각도 드네요....

2021-04-14 21:27 UTC, bperhaps commented on src/main/java/chess/service/SaveService.java
> +    }
스프링도 처음이고 JPA도 다뤄본적이 없어서 JPA를 고려해서 만든건 아니었어요!
단순하게, 매번 게임 객체의 상태를 변화시키고 그 상태를 관리해야 하는데 모든 변화를 DB에 저장하고 사용자의 요청마다 불러와서 사용하는게 CONNECTION비용이나 복구비용이 너무 크다고 생각해서 내부적 메모리 캐시가 필요하다 생각했었어요.
그런데 DAO에다가 메모리 캐시를 만드는건 당연히 어색하고 이상하다 생각해서 어떻게 할까 생각하다가, DDD책에서 REPOSITORY를 이용해 객체의 상태관리는 한다는 내용을 본 기억이 있었고, 그래서 REPOSITORY 클래스를 따로 만들어서 게임 객체들의 상태를 관리했어요!

이때, DB와의 연동도 필요한데, DAO는 어쨌든 DB와의 "연결 장치" 이니, REPOSITORY에 속하는게 맞다는 생각으로 의존성을 생성했었습니다!

2021-04-14 21:40 UTC, bperhaps commented on src/main/java/chess/web/SpringWebChessController.java
> +    public Object save(@PathVariable String gameId) {
이전 Spark에서 Error handle을 Service에서 하다 보니 에러일때와 정상일때의 반환값이 달라지는 문제가 있어서 그렇게 했었습니다!

스프링으로 바꾸고 그 문제가 사라졌으니 수정하겠습니다!

2021-04-14 21:42 UTC, bperhaps commented on src/main/java/chess/web/SpringWebChessController.java
> +    private final LoadService loadService;
처음 console로 게임을 만들었을 때, 커멘트 패턴을 이용해서 사용자의 command를 handle 했었어요.
그리고 웹으로 바꾸다 보니, spark의 routing 자체가 커멘트 패턴과 같다는 생각을 했고, 이에 따라서 Service도 위와 같이 만들었던 것 같아요.

서비스의 크기를 어느정도로 유지해야하는지에 대해 계속 헷갈렸는데, 정말 그 "서비스" 별로 묶는게 맞다고 생각해도 될까요??? 한번 묶어보긴 했는데 서비스가 너무 비대하다는 생각이 들어서요...

2021-04-14 21:50 UTC, bperhaps commented on src/main/java/chess/web/SpringWebChessController.java
> +    }
오... DataAccessException(SQLException)을 생각을 못했네요... 이전 미션에서도 SQLException을 400으로 처리해버렸는데 눈치도 못채고 있었네요... 수정하고도록 하겠습니다 감사합니다!!!

2021-04-14 21:51 UTC, bperhaps commented on src/main/java/chess/repository/GameRepository.java
> +    }
이거에 대해서 다른 크루랑 많은 얘기를 했었는데 결국 bean으로 관리하는게 답이었군요...!!
Repository에다가 Repository를 주입하는게 어색하다 생각했는데.... 수정하도록 하겠습니다!

2021-04-14 21:55 UTC, bperhaps commented on src/main/resources/schema.sql
> +/*!50503 SET character_set_client = utf8mb4 */;
> schema.sql은 현재 사용되지 활용하지 않는 걸로 보이고, table.sql은 테이블 ddl 제공 목적이 맞을까요? ㅎㅎ

처음에 h2를 이용해서 코드를 작성했어서 그 흔적이 남아있는 것 같아요..ㅎㅎ.. table.sql는 ddl 제공 목적이 맞습니다.!!

> build.gradle을 보니 브라운이 h2를 추가해두셨는데 한번 h2를 사용해보죠. 😉

오.. h2도 휘발성을 제거할 수 있었군요...!!
한번 적용해 보도록 하겠습니다!

2021-04-14 22:26 UTC, bperhaps commented
안녕하세요 휴! 피드백 정말 감사합니다!
말씀해 주신 부분 모두 수정 완료했습니다! 추가적인 질문사항은 코멘트에 남겼습니다.
이번 리뷰도 잘 부탁드려요 ㅎㅎ!!

2021-04-14 23:38 UTC, bperhaps commented on build.gradle
>      implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
인녕하세요 휴!!
저는 사실 설계쪽에 관심이 매우 많답니다...
레이어간의 분리, 객체지향적 설계 등등.... 혹시나!!! 시간이 남으신다면 설계관점에서도 도와주시면 정말 감사하겠습니다 ㅠ
ㅠ

2021-04-15 02:53 UTC, Hue9010 commented on src/main/java/chess/console/view/dto/BoardDto.java
> +public class BoardDto {
아무 dto나 잡아 피드백을 남겼다가 이런 불상사가!! 🙄 

```java
    @PatchMapping("/{gameId}/move")
    public Object move(@PathVariable String gameId, @RequestBody MoveDto moveDto) {
```
MoveDto에 기본 생성자가 없지 않나요?

2021-04-15 06:13 UTC, bperhaps commented on src/main/java/chess/console/view/dto/BoardDto.java
> +public class BoardDto {
안녕하세요 휴!  처음에 기본 생성자를 "주 생성자"랑 순간적으로 헷갈려서 다른얘기를 잠시 했네요....
저같은 경우는 기본생성자를 따로 생성하지 않더라도 에러가 발생하지 않았어요. 주신 링크를 읽어보고 제 코드에서는 왜 에러가 없는지 한번 디버깅을 따라가 봤는데요, 위 블로그 글의 마지막에 기본 생성자가 없다면 프로퍼티 기반으로 bean을 생성한다고 나와 있고, 저의 경우도 해당 로직으로 분기가 발생합니다.

그리고 쭉 가다보니 아래와 같은 로직이 나왔는데요.
![image](https://user-images.githubusercontent.com/33603557/114822275-c48fa600-9dfc-11eb-9a4c-9b7765270bf1.png)

요청으로 들어온 json을 파싱하고, key값과 "이름이 일치하는 생성자의 프로퍼티"가 존재하는지 확인하는 로직을 확인했습니다.

![image](https://user-images.githubusercontent.com/33603557/114822410-fa348f00-9dfc-11eb-8d0f-9fac9370fb74.png)

마지막에는 파싱된 데이터를 args로 받아 bean을 생성하는 로직까지 도달합니다.

결론적으로, 제 소스에서 프론트앤드로 넘어온 json데이터의 key와 bean의 생성자의 프로퍼티 이름이 모두 일치하기 때문에 에러없이 RequestBody가 잘 작동했습니다.

개인적으로 모든 객체를 불변으로 만드는걸 선호해서 setter를 사용하는걸 안좋아하는데... 이런 방식으로 진행하면 혹시 나중에 현업이라던지 문제가 발생할까요??

2021-04-15 17:54 UTC, Hue9010 approved these changes
굿 👍  빠르게 잘해주셨네요. 💯 
몇가지 피드백 남겼는데 다음 단계를 진행할 때 반영해주시면 될 것 같아요. 😄 
궁금한건 마찬가지로 언제든 질문 남겨주세요!! 😉

2021-04-15 17:54 UTC, Hue9010 commented on src/main/java/chess/web/SpringWebChessController.java
> +    @GetMapping("/{gameId}/load")
[REST API 제대로 알고 사용하기](https://meetup.toast.com/posts/92)
`4) REST API 디자인 가이드` 항목을 참고해서 URI를 고민해보면 좋을 것 같아요. 😉

2021-04-15 18:09 UTC, Hue9010 commented on src/main/java/chess/service/MoveService.java
> +        Position targetPosition = getPositionFromInput(target);
> Position의 책임은 단순히 "위치" 그 자체라고 생각해서 validation 로직을 따로 생성자에 넣지 않았었어요.

안그래도 Position을 그렇게 보고 있지 않을까 생각도 했었어요. service에 validation 로직이 들어갈 수 있지 않냐는 부분에 대해서부터 답변드리면 넵 가능합니다. 다양한 상황이 있을 수도 있는데 a, b, c 각 객체의 상태 조합에 따라 유효하지 않을 수도 있죠. 가능하다면 서로 연관 있는 객체끼리 도메인 내에서 서로간 비교를 해주면 좋지만 그게 여의치 않을 수도 있습니다. 
(예를 들면 두개였다면 a.xx(b)로 검증, 단 이것도 이렇게 검증 가능할만한 연관성이 있을 떄나 가능하죠)

다시 돌아와서 Position을 생각해보자면 Position을 위치 자체로만 생각해서 그렇게 할 수도 있습니다. 하지만 체스 내에서만 사용할 Position인게 명확하고, Position에 제한을 두지 않았을 때 지금과 같이 Position에서 처리하면 좋았을 책임이 다른 곳으로 넘어가 버립니다. 그래서 개인적으로 생각하기에 체스의 Position으로 의미를 한정하는게 프로젝트 내에서 Position을 사용하는데 있어 더 유리하다고 보여 생성자 자체에서 검증을 둘 것 같습니다. 혹은 위치 자체로 본다면 체스 생성자 자체는 지금처럼 체스판에 따른 validation을 두지 않고 체스 Position을 만드는 정적 팩토리 메서드를 만들어 사용할 것 같습니다. 그러면 위치 자체로서의 의미도 유지하고 체스에 대한 Position 검증 또한 Position 스스로가 가질 수 있죠.

이 부분에 대한 얘기를 꺼낸건 사실 다른게 아니라 Position 자체에 대한 얘기보다는 validateRightInputs 때문이랍니다.
```java
    private void validateRightInputs(String source, String target) {
        if (isRightPositionFormat(source) && isRightPositionFormat(target)) {
            return;
        }

        throw new CommandFormatException();
    }
```
잘못된 위치를 입력 했을 때 나는 예외로서 `CommandFormat`Exception가 맞을까요? Position에 대한 예외가 발생해야 하는게 아닐까요? 🤔
라는 생각을 하고보니 Position에 대한 검증을 Service가 아닌 Position이 가게 할 수 있을 것 같은데 생각이 들어 그게 가능한 구조인지 여쭤본거랍니다. 😄  (이동 가능한 위치를 찾을 때 a9를 생성한다면 불가능하죠. ㅎㅎ)

2021-04-15 18:24 UTC, Hue9010 commented on src/main/java/chess/service/SaveService.java
> +    }
사실 스프링에서는 그런 캐싱에 대한 처리를 도와주는 기능을 제공한답니다.
[Spring 의 Caching 기능 이용하기](https://jins-dev.tistory.com/entry/Spring-%EC%9D%98-Caching-%EA%B8%B0%EB%8A%A5-%EC%9D%B4%EC%9A%A9%ED%95%98%EA%B8%B0)

그리고 이런건 스프링을 공부하다 보면 한두번씩 접했을 수도 있는 AOP라는 개념과 유관하답니다. [AOP 정리 (3)](https://jojoldu.tistory.com/71?category=635883)

그러면 간단한 퀴즈 
1. `내부적 메모리 캐시가 필요하다 생각했었어요.`라고 말씀해주셨는데 하나의 서버가 아닌 여러대의 서버가 운영되고 있을 때 내부적인 메모리 캐시에 저장하고 있으면 문제 없을까요? 🤔 
2. 캐싱 해둔 데이터가 바뀔 때 db에는 반영이 됐는데 캐싱 데이터가 들어가 있는 Map repository엔 반영이 안됐다면 어떤 문제가 있을까요?

2021-04-15 18:30 UTC, Hue9010 commented on src/main/java/chess/web/SpringWebChessController.java
> +    private final LoadService loadService;
어느면에서 비대하다고 느꼈을까요? 코드량이라면 그렇게 많은 편은 아니랍니다.
대신 두가지를 생각 해 볼 수 있을 것 같아요. ChessGame이 자신한테 맞지 않는 책임을 가지고 있는가? 게임을 저장하고 불러오고 등등 이건 맞다고 봐요.
그러면 두번째로 체스가 가지고 있는 책임이 너무 많아 역할 분리를 해야하는건 아닌가? 를 고려해볼 수 있을 것 같아요. 근데 이것도 아직 크게 역할을 분리할 만한 요소는 크지 않다고 봤습니다.
무언가 기능이 더 추가된다면 체스 방 관리 등 전체적인 게임을 운영하는 측면의 서비스와 게임을 진행시키는 역할을 담당하는 서비스로 분리가 이뤄 질 수도 있겠지만 그건 어디까지나 알수 없는 미래 상황에 대한 추측으로 섣불리 작업하는 걸로 생각되네요.

2021-04-15 18:30 UTC, merged

2021-04-15 21:26 UTC, bperhaps commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:file:./chess
파일디비는 ddl을 자동으로 넣기 힘든 것 같아서 나름의 배려..?? 였는데 쮸르륵...ㅠㅠ 다 좋은 방법을 찾아보도록 하겠습니다!!

2021-04-15 21:26 UTC, bperhaps commented on src/main/java/chess/dao/table.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
아...! 이쪽도 제거하겠습니다!! DDL 제공 목적이라서 뭔가 정보들이 보여야 할 줄 알았어요!!

2021-04-15 21:52 UTC, bperhaps commented on src/main/java/chess/service/MoveService.java
> +        Position targetPosition = getPositionFromInput(target);
오 정적 팩토리 매서드...!!!!!!!!! 시도해 보겠습니다!!

2021-04-16 04:23 UTC, Hue9010 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:file:./chess
schema.sql과 data.sql을 찾아보실래요? 😉

2021-04-19 10:41 UTC, bperhaps commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:file:./chess
Spring 기본값으로 classpath 루트에 schema.sql 파일이 있다면 서버 시작시 스크립트를 실행한다. 보통 schema.sql은 DDL 스크립트를 명시해두고, 데이터를 위한 DML문은 data.sql 파일로 작성해두면 역시 자동으로 실행한다.

와.. 처음알았어요... 신기하네요...

2021-04-22 14:54 UTC, bperhaps commented
test

2021-04-22 18:04 UTC, bperhaps commented
# 학습로그
## @RequestBody
- RequestBody는 기본생성자가 곡 필요하다. 하지만 실제로 돌려봤을 때 기본생성자가 없더라도 코드가 정상적으로 돌아가는 상황을 경험했다. 문제점을 보니, Gradle의 Build and run using의 빌드 셋팅에 따라 달라지는걸 알 수 있었다. 휴는 gradle로 하면 제이슨 파서는 gson, intellij로 하면 jackson을 사용한다고 했지만, 실제로 디버깅을 돌려보다 둘 다 jackson을 사용하는걸로 보인다. 어떤 차이가 있는걸까?
- https://github.com/woowacourse/jwp-chess/pull/224#discussion_r613782805
## 태그
- Spring, RequestBody

# 학습로그
## 서비스
- 서비스를 어느 단위로 묶는게 맞을까? 휴의 피드백에 따르면 "액션에 따라" 묶기 보다는 "서비스의 단위" 별로 묶는게 맞다고 하는 것 같다. 무슨 소린고 하니, 기존의 내 코드는 체스 게임의 명령어별로 서비스 객체를 나눴었다. 하지만 휴는 이 객체를 "체스게임"이라는 하나의 서비스객체로 본다.
- https://github.com/woowacourse/jwp-chess/pull/224/commits/cc967240213f84c9b00b8176173ae1e10111dafb

## 태그
- 설계, service layer

# 학습로그
## h2 database
- h2데이터베이스는 일반적으로 테스트용 메모리db로 알고 있지만 설정을 통해 여러가지 방법으로 사용할 수 있다.
- 이번 미션에서는 file기반으로 영속성을 만족시켜봤다.
- https://github.com/woowacourse/jwp-chess/pull/224/commits/7b4919232011b577622710e1f54ce3a6d94d888b
- http://www.h2database.com/html/features.html

## 태그
- spring, db, h2

# 학습로그
## schema.sql, data.sql
- Spring 기본값으로 classpath 루트에 schema.sql 파일이 있다면 서버 시작시 스크립트를 실행한다. 보통 schema.sql은 DDL 스크립트를 명시해두고, 데이터를 위한 DML문은 data.sql 파일로 작성해두면 역시 자동으로 실행한다.

## 태그
- spring, db