[1, 2단계 - Spring 적용하기] 춘식(안예장) 미션 제출합니다.
woowacourse/jwp-chess pull request #236
Opened 2021-04-15 10:47 UTC by RinSabbit

반가워요 재연링!! 레벨 2 첫 미션을 함께하게 되어 설레네요ㅎㅎ
잘 부탁드립니다!! 😆

레벨 1때 스파크로 구현한 체스에 스프링을 적용하면서 콘솔 및 스파크 관련 클래스, 메소드들은 모두 정리했습니다.
혹시나를 위해 스파크 체스 링크를 [여기](https://github.com/RinSabbit/java-chess/tree/step2) 두고 갑니다!

이번 미션을 진행하면서 궁금했던 점은 다음과 같습니다.
- 위에 적혀있듯 스프링을 적용하면서 콘솔, 스파크 관련 메소드를 모두 지웠는데 구현을 하면서 에러가 나면, 정확히 어느 구간에서 에러가 난 건지 알 수가 없었습니다.. 404 또는 400 으로만 떠서 디버깅을 하는데 시간이 다소 걸렸습니다ㅠㅠ 제가 에러 메세지를 잘 찾지 못한 것인지 아니면 따로 오류를 찾는 방법이 있는지 궁금해요.
- 테스트 코드를 짜면서 MockMvc와 RestAssured를 둘 다 사용했습니다. 찾아보니 MockMvc는 서버를 이용하지 않고도 Spring MVC의 동작을 재현할 수 있으며 주로 단위 테스트에 사용되고, RestAssured는 실제 요청을 보내서 전체적인 로직을 테스트 해 전 구간 테스트에 용이하다고 합니다. 둘 다 장단점이 있는 것 같은데 현장에서는 어떤 테스트 도구가 주로 쓰이는지 궁금해요!
- ReqeustMapping을 사용해보고 싶어 Controller가 2개로 나누어지게 되었는데, 이래도 되는 것인지 잘 모르겠습니다.. 😅 스프링의 경우에도 MVC 패턴을 사용할 때 Controller가 하나만 존재해야 하나요?

+) 이유는 잘 모르겠으나 체스를 오래 진행하면 가끔 체스말을 옮겨도 턴이 바뀌지 않거나 체스말 이동 가능 영역이 이상하게 뜨는 경우가 있습니다.. 오류가 뜨질 않아 아직 이유를 찾고 있는 중인 점 양해 부탁드립니다..ㅠㅠ..

2021-04-16 09:53 UTC, jaeyeonling requested changes
안녕하세요 춘식!
스프링 입문을 함께할 재연링입니다 :)
요구사항에 맞게 잘 반영해주셨어요 👍 
소소한 피드백 남겨두었으니 확인 후 반영해주세요!

2021-04-16 09:53 UTC, jaeyeonling commented on build.gradle
> +    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.2'
compile과 implementation는 어떠한 차이가 있을까요?

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/controller/BoardController.java
> +    public boolean isEnd(){
```suggestion
    public boolean isEnd() {
```

컨벤션을 위반하셨습니다!
IntelliJ Auto Formatting 기능을 사용하는 습관을 들여보아요

The auto-formatting shortcut in IntelliJ

* For windows Ctrl + Alt + L.
* For ubuntu Ctrl + Alt + windows + L.
* For Mac Command + Option + L.

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/controller/MenuController.java
> +    @ExceptionHandler(RuntimeException.class)
@ExceptionHandler 👍 

ExceptionHandler는 어디에 위치하냐에 따라 커버되는 범위가 달라지는데요
MenuController 내부에 존재한다면 MenuController에서 발생하는 예외를 처리합니다!
BoardController에는 따로 존재하지 않는데 의도된 내용일까요?

Q. 위에 적혀있듯 스프링을 적용하면서 콘솔, 스파크 관련 메소드를 모두 지웠는데 구현을 하면서 에러가 나면, 정확히 어느 구간에서 에러가 난 건지 알 수가 없었습니다.. 404 또는 400 으로만 떠서 디버깅을 하는데 시간이 다소 걸렸습니다ㅠㅠ 제가 에러 메세지를 잘 찾지 못한 것인지 아니면 따로 오류를 찾는 방법이 있는지 궁금해요.

A. 정확히 어떠한 부분에서 디버깅이 힘들었는지 애매하지만

1. 의도된 예외를 CustomException으로 분리하여 정확한 에러메시지와 StatusCode를 클라이언트에 전달한다.
2. 모든 Exception을 catch하여 로그를 남겨준다.
3. 로그레벨을 올린다.

등을 통해 해결이 가능한 부분 같아요!
어느 부분에서 디버깅이 힘들었는지 말씀해주시면 조금 더 자세히 답변 드리도록 하겠습니다 ㅎㅎ

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/domain/board/Board.java
> +    private final Map<Piece, Position> coordinates;
```suggestion
    private static final Piece EMPTY_PIECE = new Empty();
    
    private final Map<Piece, Position> coordinates;
```

클래스 변수와 인스턴스 변수 사이에 공백을 추가한다면 가독성이 상승합니다

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/domain/board/Board.java
> +    }
```suggestion
    public Board() {
        this(new LinkedHashMap<>());
    }
    
    public void putPiece(Piece piece, Position position) {
        coordinates.put(piece, position);
    }
```

생성자를 위로 올려주시면 가독성이 상승합니다 :) 

```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

또한 인스턴스 변수의 초기화를 하나의 생성자에서 해주면 어떠한 장점이 있을지 고민해보아요

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/controller/BoardController.java
> +public class BoardController {
Q. ReqeustMapping을 사용해보고 싶어 Controller가 2개로 나누어지게 되었는데, 이래도 되는 것인지 잘 모르겠습니다.. 😅 스프링의 경우에도 MVC 패턴을 사용할 때 Controller가 하나만 존재해야 하나요?

A. 사람마다 의견은 다를 수 있지만 의미가 있다면 저는 여러 Controller로 분리해주셔도 괜찮다고 생각합니다 :)

2021-04-16 09:53 UTC, jaeyeonling commented on src/test/java/chess/SpringChessApplicationTests.java
> +    private MockMvc mockMvc;
Q. 테스트 코드를 짜면서 MockMvc와 RestAssured를 둘 다 사용했습니다. 찾아보니 MockMvc는 서버를 이용하지 않고도 Spring MVC의 동작을 재현할 수 있으며 주로 단위 테스트에 사용되고, RestAssured는 실제 요청을 보내서 전체적인 로직을 테스트 해 전 구간 테스트에 용이하다고 합니다. 둘 다 장단점이 있는 것 같은데 현장에서는 어떤 테스트 도구가 주로 쓰이는지 궁금해요!
A. 차이를 잘 알고 계시네요 👍 
말씀하신 것 처럼 둘 다 장단점이 존재하여 선택의 영역이지만, 과거엔 MockMvc가 많이 사용 됐고 지금은 RestAssured를 많이 사용하는 추세로 보이긴 합니다 ㅎㅎ
두 테스트 도구의 차이를 잘 알고 계셔서 결론만 말씀드렸는데 추가적으로 궁금하신 점 있다면 말씀해주세요!

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
지금의 구조는 하나의 게임만 가능한 것 같은데 의도된 내용이 맞으실까요!?

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
Q. 이유는 잘 모르겠으나 체스를 오래 진행하면 가끔 체스말을 옮겨도 턴이 바뀌지 않거나 체스말 이동 가능 영역이 이상하게 뜨는 경우가 있습니다.. 오류가 뜨질 않아 아직 이유를 찾고 있는 중인 점 양해 부탁드립니다..ㅠㅠ..
A. 질문주신 내용과 큰 연관은 없지만 지금의 구조에서 동시에 같은 요청이 왔을 때 어떻게 동작할지에 대해서도 같이 고민해보면 좋겠어요 ㅎㅎ

2021-04-16 09:53 UTC, jaeyeonling commented on src/test/java/chess/domain/piece/PawnTest.java
> +class PawnTest {
테스트를 매우 탄탄하게 작성해주셨네요 👍

2021-04-16 09:53 UTC, jaeyeonling commented on src/main/java/chess/controller/BoardController.java
> +    @GetMapping(value = {"","/restart"})
`게임을 재시작한다.`라는 기능은 POST에 더욱 적절한 요청으로 보여지는데 어떻게 생각하시나요!?

2021-04-16 09:53 UTC, jaeyeonling commented on src/test/java/chess/Dao/MoveDaoTest.java
> +    private MoveDao moveDao;
테스트 환경에서는 실제 환경의 DB를 사용하는 것 보다는 h2 DB를 활용해보면 어떨까요!?

2021-04-17 06:58 UTC, RinSabbit commented on build.gradle
> +    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.2'
알아보니 compile 은 gradle 3.0이 나오면서 deprecated 되었네요!!

compile 대신 implemention 또는 api 를 권장하고 있습니다. Implementaion은 수정이 일어날 경우 직접 의존하는 모듈만 rebuild를 해서 속도가 빠르고, 연결된 모듈의 api가 노출되는 compile(지금은 api로 대체되었네요!!)과 다르게 연결된 모듈의 api를 노출하지 않는다고 합니다!!

2021-04-17 07:02 UTC, RinSabbit commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
네!! 다음 단계를 진행할 때 방을 만들어 여러 체스 게임을 진행할 수 있는 기능을 추가할 예정입니다 :3

2021-04-17 07:04 UTC, RinSabbit commented on src/test/java/chess/Dao/MoveDaoTest.java
> +    private MoveDao moveDao;
test용 properties를 따로 만들어 테스트 환경은 h2 디비를 사용하도록 수정했습니다!!

2021-04-17 07:13 UTC, RinSabbit commented on src/main/java/chess/controller/BoardController.java
> +    @GetMapping(value = {"","/restart"})
앗 현시점에서는 보드가 하나 밖에 없어서 GET을 해도 괜찮았는데 여러 체스 게임방을 진행하게 된다면 방 id가 필요하게 될 테니 POST로 바뀌게 되겠네요..! 다음 단계를 진행할 때 수정하도록 하겠습니다 😄

2021-04-17 07:27 UTC, RinSabbit commented on src/main/java/chess/controller/MenuController.java
> +    @ExceptionHandler(RuntimeException.class)
위치에 따라서 ExceptionHandler 커버 범위가 달라지는 거였군요!! 발생하는 모든 예외를 처리하고 싶었던 지라 MenuController에 있던 handler를 controller 패키지 바로 아래에 따로 클래스를 구현해 이동시켰습니다!! 🙏 🙏 

디버깅이 힘들었던 부분은 Run을 돌리면 너무 뜨는 게 많아 System.out.println으로 써놓은 걸 찾기 힘들었던 건데... logback-access.xml을 비활성화시키니까 해결되었습니다ㅋㅋㅋㅠㅠㅠ 또한 Logger를 사용하는 방법도 알게 되었습니다..!

2021-04-17 08:06 UTC, RinSabbit commented on src/test/java/chess/SpringChessApplicationTests.java
> +    private MockMvc mockMvc;
RestAssured를 더 많이 사용하는 군요!! 그럼 테스트 도구를 사용할 때 여러 개의 테스트 도구를 사용해도 괜찮은 걸까요?! 👀

2021-04-17 08:49 UTC, RinSabbit commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
다른 크루의 도움으로 버그를 수정할 수 있었습니다!! Map은 중복된 Key를 허용하지 않는다는 점을 간과해서 생긴 문제였습니다ㅠㅠ... 💃 💃

현재 구조에서는 moveDao를 필드변수로 쓰고 있어서 한 디비를 같이 공유하게 될 것 같아요 🤔  체스방이 여러 개 생기게 된다면 moveDao에서 방 ID별 moves를 갖고 오게 될텐데... 생각해보니 같은 방에서 동시에 같은 요청이 오는 문제가 생길 수 있겠네요... 🤔  🤔  그럼 Service에서는 필드 변수를 최대한 지양하는 쪽으로 가면 되려나요..!!

2021-04-17 10:03 UTC, RinSabbit commented
반가워요 재연링!! 상세한 피드백 감사합니다 🥰 
피드백 중점으로 리팩토링 해보았습니다!!
크게 바뀐 사항은 다음과 같습니다.

- 체스말 이동 버그 수정
- 테스트에선 h2 DB를 사용하도록 변경
- Dto에서 ConstructorProperties를 사용하도록 변경

이번에도 잘 부탁드립니다!! 🙏  🙏

2021-04-18 06:44 UTC, jaeyeonling approved these changes
피드백을 잘 반영해주셨어요 👍 
소소한 피드백 남겨두었으니 확인해주시고 다음 단계에 반영해주세요 :)

2021-04-18 06:44 UTC, jaeyeonling commented on src/main/java/chess/controller/GlobalExceptionHandler.java
> +            new HttpHeaders(), HttpStatus.CONFLICT, request);
해당 서비스에서 발생하는 모든 IllegalArgumentException과 RuntimeException이 HttpStatus.CONFLICT라고 보장할 수 있을까요!?
예외 상황에 맞은 올바른 응답과 StatusCode를 전달하기 위해선 어떠한 구조를 잡아야할지 고민해보아요
힌트를 드리자면 CustomException을 분리하는 방법이 있겠네요 :)

2021-04-18 06:44 UTC, jaeyeonling commented on src/test/java/chess/SpringChessApplicationTests.java
> +    private MockMvc mockMvc;
같은 기능을 하는 라이브러리의 경우 현업에서는 하나의 도구로 통일하는 경우가 많지만, 지금은 학습 과정이기 때문에 하고싶은 모든 라이브러리를 같이 사용하셔도 됩니다 ㅎㅎ 
물론 현업에서도 취향에 맞게 여러 테스트 도구를 쓰는 경우도 있지만, 유지보수성이 낮아지고 프로젝트가 무거워지는 문제가 있기 때문에 저도 하나의 도구로 통일하는 것을 선호합니다!

2021-04-18 06:44 UTC, jaeyeonling commented on src/main/java/chess/controller/BoardController.java
> +    @GetMapping(value = {"", "/restart"})
> 앗 현시점에서는 보드가 하나 밖에 없어서 GET을 해도 괜찮았는데 여러 체스 게임방을 진행하게 된다면 방 id가 필요하게 될 테니 POST로 바뀌게 되겠네요..! 다음 단계를 진행할 때 수정하도록 하겠습니다 😄

URL에 고유식별자(id)를 추가하여 의미를 전달하는 방법도 존재하는데요!
https://github.com/woowacourse/jwp-chess/pull/236#discussion_r614710771 해당 리뷰의 의미는 기능과 HTTP Method의 의미가 일치하는가? 에 대한 의미였습니다 ㅎㅎ 
RESTful API 키워드로 검색해보시면 관련 내용들을 확인할 수 있습니다!

2021-04-18 06:45 UTC, merged

2021-04-19 08:32 UTC, RinSabbit commented
# 학습로그

# [테스트 도구] RestAssured vs MockMVC

## 내용

|RestAssured|vs|MockMvc|
|-----|--|----|
|전 구간 테스트|주 목적|단위 테스트|
|*별도 추가 O|의존성|별도 추가 X|
|@SpringBootTest|**Annotation|@WebMvcTest|
|느림|**속도|빠름|
|상대적 good|가독성|상대적 bad|

* RestAssured의 경우 의존성을 따로 추가해야 한다.
```java
Dependencies {
    testImplementation ‘io.rest-assured:rest-assured:3.3.0’
}
```

** @SpringBootTest로 테스트 수행시 등록된 Spring Beand을 전부 로드해 시간이 오래 걸린다. 반면 @WebMvcTest는 Presentation Layer의 Bean만 로드하기 때문에 상대적으로 빠르다. 하지만 Mock 객체로 처리해주는 비용을 생각해보면 MockMvc를 사용하는 게 무조건 좋은 건 아니다. 상황에 따라 RestAssured 와 MockMvc를 골라 쓰면 되지만 요즈음엔 RestAssured를 주로 쓴다고 한다.

===

## 링크

- https://dundung.tistory.com/229

# [JAVA] Logger

## 내용

### 사용 이유

System.out.prinltn() 은 IO 리소스를 많이 사용해 시스템이 느려질 수 있다. 
로그를 파일로 저장해 분석할 필요가 있다.

```java
// 스프링 부트는 logback이 기본으로 설정되어 있어 별도 라이브러리를 추가하지 않아도 된다.
Private final Logger logger = LoggerFactort.getLogger(클래스이름.class);
logger.info("로그 타이틀”, 출력할 값);
```
### 로그 레벨

로깅 레벨을 지정하면 지정한 레벨 이상의 로그만 출력하고 미만은 무시한다.
1) Trace: Trace, Debug, Info, Warn, Error
2) Debug: Debug, Info, Warn, Error
3) Info: Info, Warn, Error
4) Warn: Warn, Error
5) Error: Error

```java
// application.properties
// 루트(전체) 로깅 레벨 지정
logging.level.root=info

// 패키지별 로깅 레벨 지정
logging.level.test.chess.dao=info
logging.level.test.chess.controller=debug
```

===
## 링크

- https://doublesprogramming.tistory.com/82
- https://meetup.toast.com/posts/149
- https://goddaehee.tistory.com/206


# [Design Pattern] Spring MVC 패턴

## 내용

스프링 프레임워크는 기본적으로 MVC 패턴을 따른다.
기본적으로 MVC 패턴은 아래의 모델을 주로 사용한다.
![MVCPattern](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FblPTBS%2FbtqyBzvIQhg%2FbAYZmdxgD7mUGCnYiKlku0%2Fimg.png)

여기서 스프링 MVC 프레임워크는 MVC 패턴을 따르면서 스프링만의 독자적인 Class를 통해 처리를 한다.
![SpringMVCPattern](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbNgYN8%2FbtqyAMB7FFS%2F6lxcAlnXqURYkHpP8LyRb1%2Fimg.png)
1) Clinet로부터 요청이 오면 DispatcherServlet이 호출된다
2) DistpatcherServlet은 받은 요청을 HandlerMapping에게 던져준다. 요청받은 URL을 분석한 HandlerMapping은 적합한 Controller를 선택하여 반환한다.
3) DispatcherServlet은 다음으로 HandlerAdapter를 호출한다. HandlerAdapter는 해당하는 Controller 중 요청한 URL에 맞는 적합한 Method를 찾아준다.
4) Controller는 Business Logic을 처리하고, 해당하는 결과를 View에 전달할 객체를 Model에 저장한다.
5) Controller는 View name을 DispatcherServlet에게 반환한다.
6) DispathcerServlet은 ViewResolver를 호출하여 Controller가 반환한 View name을 기반으로 적합한 View를 찾아준다.
7) DispatcherServlet은 View 객체에 처리결과를 넘겨 최종 결과를 보여주도록 요청한다.
8) View 객체는 해당하는 View를 호출하며, View는 Model 객체에서 화면 표시에 필요한 객체를 가져와 화면 표시를 처리하고 Client에게 넘겨준다.

Servlet은 Clinet의 요청을 처리하고 결과를 전송하는 기술이다. 특징은 다음과 같다.
- Clinet의 요청에 대해 동적으로 작동
- HTML을 사용해 요청에 응답
- Java Thread을 이용해 동작
- MVC 패턴에서 Controller로 이용됨

===
## 링크
- https://aridom.tistory.com/61

# [DB] H2 DB

## 내용

H2 데이터베이스는 컴퓨터에 내장된 램(RAM) 메모리에 의존하는 데이터베이스이다. 때문에 웹서버를 재부팅할 때마다 기존의 데이터가 사라져 테스트용 디비로 사용하기에 용이하다.

테스트용 디비를 따로 설정하려면 테스트용 porperties를 만들고 테스트의 TestPropertySource를 테스트용 properties로 설정해주면 된다.

application-test.properties
```java
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
```

MoveDatoTest.java
```java
@SpringBootTest(webEnvironment = WebEnvironment.NONE)
@TestPropertySource(("classpath:application-test.properties"))
class MoveDaoTest { 
// …
```

===

## 링크

- https://youngjinmo.github.io/2020/03/h2-database/
- https://jungguji.github.io/2020/07/05/H2-DB%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-Repository-Test/
- https://bgpark.tistory.com/78

# [Spring] ControllerAdvice, Exception Handler

## 내용

스프링 3.2부터 @ControllerAdvice가 나오면서 Controller 레벨의 @ExceptionHandler가 아닌 Global 레벨의 @ExceptionHandler를 사용할 수 있게 되었다.

```java

@ControllerAdvice
Public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

// 여러 Exception 클래스를 handle 하고 싶을 경우엔
// @ExceptionHandler(value = {aException.class, bException.class})
@ExceptionHandler(RunTimeException.class)
protected ResponseEntity<Object> handleConflict(RuntimeException exception,
    WebRequest request) {
    return handleExceptionInternal(exception, exception.getMessage(),
        new HttpHeaders(), HttpStatus.CONFLICT, request);
   }

// 특정 HttpStatus(에러)마다 다른 응답을 하고 싶으면 CustomException, @ResponseStatus(원하는 HttpStatus) 을 사용한다.
@ResponseStatus(HttpStatus.BAD_REQUEST)
@ExceptionHandler(CustomException.class)
    public ModelAndView handleNotContent() {
        logger.info("NotContextException 입니다.”);
         // 이 경우 CustomView 표현. 반환형 void 에 logger 찍어도 되고…
        return new ModelAndView("error");
    }
}


```


===

## 링크

- https://www.baeldung.com/exception-handling-for-rest-with-spring
- https://velog.io/@max9106/Spring-Boot-ExceptionHandler
- https://heowc.tistory.com/34

# [Gradle] Implementation vs Compile vs API

## 내용

implemnetation과 api는 grade 3.0 때 새로 나왔다.
api는 compile과 동일한 키워드이므로 compile 대신 api, 또는 implementation을 쓸 것을 권장하고 있다.

### implementation vs api(compile)

A <- B <- C
모듈 A, B, C가 다음과 같은 의존 관계를 가지고 있다고 가정하자.
A가 수정된다면 api의 경우, A에 의존하고 있는 모든 모듈, B와 C가 모두 rebuild 된다.
반면 implementation의 경우, A에 직접 의존하고 있는 B만 rebuild 된다.
이러한 차이는 Implementation이 api보다 빠른 빌드 속도를 가지게 한다.
또한 api는 의존된 모든 모듈에 접근할 수 있으나 implementation은 다른 모듈로의 접근이 불가능하다. 즉, Implementatino은 불필요한 api의 노출을 줄여준다.

===

## 링크

- https://hack-jam.tistory.com/13
- https://aroundck.tistory.com/6042
- https://sikeeoh.github.io/2017/08/28/implementation-vs-api-android-gradle-plugin-3/