[1, 2단계 - Spring 적용하기] 알리(허진호) 미션 제출합니다.
woowacourse/jwp-chess pull request #241
Opened 2021-04-16 05:24 UTC by jh8579

안녕하세요 알리입니다!
이번 미션을 통해 레벨1때 작성한 체스 코드에 스프링을 적용했습니다.
스프링에서 사용할 수 있는 여러 annotation을 사용해봤습니다.
그걸 통해 spark를 사용했을 때보다 코드가 더 간결해지고 추가적인 작업이 사라졌습니다.
부족한 부분들 피드백 해주시면 리팩토링을 통해 더 좋은 코드로 만들어 보고 싶습니다.
감사합니다!

2021-04-16 05:25 UTC, jh8579 commented
### 학습 로그

[가변 인자 학습 로그](https://velog.io/@jh8579/Java-%EA%B0%80%EB%B3%80%EC%9D%B8%EC%9E%90)

2021-04-18 08:51 UTC, dave915 requested changes
알리 안녕하세요! 이번에 리뷰를 맡게 된 데이브입니다 🙇‍♂️
미션 구현 잘 해주셨네요 ㅎㅎ
몇 가지 코멘트 남겼어요. 확인부탁드릴게요! 
궁금한점 있다면 언제든 DM주세요!

2021-04-18 08:51 UTC, dave915 commented on src/main/java/chess/controller/SpringWebController.java
> +    @GetMapping(ROOT + GAMES)
개인적으로 `@GetMapping(ROOT)` 또는 `return LOGIN + SPRING_FOOTER` 같은 경로를 나타낼때는 변수로 분리하는 것 보단 그냥 써주는것이 더 가독성이 좋은 것 같아요. 
`/games` 또는 `login-spring` 이런 문자열은 여러 문자열의 조합이 아닌 하나의 Value로 봐야 한다고 생각해요 😁

2021-04-18 08:51 UTC, dave915 commented on src/main/java/chess/controller/SpringWebController.java
> +        return REDIRECT + ROOT + GAMES + "/" + gameId;
오류 처리를 해주셨네요! 보통 오류처리는 각 컨트롤러가 아닌 한곳에서 해주는데요, 검색 키워드 남겨둘 테니 한번 찾아보시면 좋을 것 같아요! 

키워드 : `@ControllerAdvice`, `@RestControllerAdvice`

2021-04-18 08:51 UTC, dave915 commented on src/main/java/chess/domain/dto/WebBoardDto.java
> +    private static final String imgTag = "<img class=\"chessboard\" src=\"/images/%s.png\" alt=\"\">";
Backend에서 Html태그까지 만들어서 주기보단 imge url만 따로 전달해주고 Front 에서 각 기물별로 찾아서 사용하도록 하는게 좋지 않을까 하는 생각이 들어요.
서버에서 태그를 다 만들어서 내리면 화면을 구성할때 제약이 생기지 않을까요?

2021-04-18 08:51 UTC, dave915 commented on src/main/java/chess/repository/GameHistoryDao.java
> +    private final RowMapper<GameHistory> gameHistoryRowMapper = (resultSet, rowNum) ->
👍

2021-04-18 08:51 UTC, dave915 commented on src/main/java/chess/controller/SpringWebController.java
> +    @PostMapping("/login")
Chess 에 관한 컨트롤러, Login에 관한 컨트롤러 분리해주면 좋을 것 같네요 :)

2021-04-18 08:55 UTC, dave915 commented
깜빡한 코멘트 몇개 있어서 남길게요! 

1. 혹시 mysql 대신 h2를 사용해보실 생각 있으신가요?
h2인 경우 메모리에 올라가는 DB이기 때문에 각 개발자 로컬에서 개인적으로 DB 셋팅을 안해줘도 되기 때문에, 테스트 또는 지금처럼 학습용 프로젝트에서 많이 쓰이고 있어요 :)
https://www.baeldung.com/spring-boot-h2-database

2. Controller, Service, Repository Layer에 관한 테스트도 추가하면 좋을 것 같아요! 

3. Spring 관련해서 공부해보셨으면 하는 점도 몇개 남겨둘게요! (이 부분은 코드에 반영할건 아니고, Spring하면 기본적으로 알아야 한다고 생각해서 남겼어요 ㅎㅎ )
- Spring에서 request 처리 과정
- @ResponseBody는 어떤 역할을 해줄까?
- @ComponentScan과 빈 주입 방법 (@Autowired, 생성자 주입)

2021-04-20 07:52 UTC, jh8579 commented on src/main/java/chess/controller/SpringWebController.java
> +    @GetMapping(ROOT + GAMES)
중복되는 상수를 없애고 싶다는 강박이 있었는데,
리뷰해주신 부분을 다시 생각해보니
경로와 같이 이 메소드가 어떤 역할을 하는지 알 수 있는 부분들은
상수로 찾아 올라가서 확인하기보다는 url로 바로 확인할 수 있는 게 나을 것 같다는 생각이 드네요
수정했습니다!

2021-04-20 07:54 UTC, jh8579 commented on src/main/java/chess/controller/SpringWebController.java
> +        return REDIRECT + ROOT + GAMES + "/" + gameId;
@ControllerAdvice를 사용하니 controller에서는 예외를 던지기만 하고,
예외를 담당하는 controller에서 한꺼번에 처리해주니 코드가 더 간결해져 좋은 것 같아요
수정했습니다.

2021-04-20 07:55 UTC, jh8579 commented on src/main/java/chess/controller/SpringWebController.java
> +    @PostMapping("/login")
login, chess 관련 로직이 엮어있어 분리하기 어려울거라고 생각했는데
막상 분리하다보니 깔끔하게 분리가 되네요
수정했습니다.

2021-04-20 07:58 UTC, jh8579 commented on src/main/java/chess/domain/dto/WebBoardDto.java
> +    private static final String imgTag = "<img class=\"chessboard\" src=\"/images/%s.png\" alt=\"\">";
저도 image src만 넘겨주고 싶었는데 아직 html이 익숙하지 않아서 편하게 하려다보니 이런 코드를 작성하게 된 것 같아요
프론트 입장에서 생각해보니 저렇게 태그를 다 만들어서 주면 제약이 생기겠네요
수정했습니다

2021-04-20 08:37 UTC, jh8579 commented
> 깜빡한 코멘트 몇개 있어서 남길게요!
> 
> 1. 혹시 mysql 대신 h2를 사용해보실 생각 있으신가요?
>    h2인 경우 메모리에 올라가는 DB이기 때문에 각 개발자 로컬에서 개인적으로 DB 셋팅을 안해줘도 되기 때문에, 테스트 또는 지금처럼 학습용 프로젝트에서 많이 쓰이고 있어요 :)
>    https://www.baeldung.com/spring-boot-h2-database
> 2. Controller, Service, Repository Layer에 관한 테스트도 추가하면 좋을 것 같아요!
> 3. Spring 관련해서 공부해보셨으면 하는 점도 몇개 남겨둘게요! (이 부분은 코드에 반영할건 아니고, Spring하면 기본적으로 알아야 한다고 생각해서 남겼어요 ㅎㅎ )
> 
> * Spring에서 request 처리 과정
> * @responsebody는 어떤 역할을 해줄까?
> * @componentscan과 빈 주입 방법 (@Autowired, 생성자 주입)

h2 데이터베이스로 db 변경했고 table 생성에 필요한 sql문도 추가했습니다

spring 관련해서 키워드 주신부분은 조금 더 찾아보고 공부해서 학습 로그로 작성해서 올리겠습니다.

2021-04-20 08:39 UTC, jh8579 commented
### 변경사항
* url 상수 제거하고 url 그대로 유지
* 예외 처리를 담당하는 Controller 추가
* img 태그를 전달하던 dto를 말의 정보만 전달하도록 변경
* 로그인 관련 controller 분리
* database h2로 변경

2021-04-23 11:43 UTC, dave915 approved these changes
알리 안녕하세요! 
피드백 반영한 부분 확인했습니다 👍
저번 피드백에서 추가로 제안드린 부분은 다음 단계 하면서 같이 반영해주셔도 됩니다 :) 
이번 단계는 이만 머지할게요!

2021-04-23 11:43 UTC, dave915 commented on src/main/java/chess/controller/spring/ErrorController.java
> +    @ExceptionHandler(ChessException.class)
👍

2021-04-23 11:43 UTC, dave915 commented on src/main/resources/templates/chess-spring.mustache
> +            <img class="chessboard" src="/images/{{a8}}.png" alt="">{{/a8}}</td>
👍

2021-04-23 11:43 UTC, dave915 commented on src/main/java/chess/controller/spring/UserController.java
> +public class UserController {
👍

2021-04-23 11:43 UTC, dave915 commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
```
spring.datasource.schema=classpath:data.sql
spring.datasource.initialization-mode=always
```

이렇게 추가하면 시작할때마다 디비가 초기화 되도록 할 수 있어요 :) 
그리고 ddl 은 `schema.sql` , dml 은 `data.sql` 파일에서 관리해요 ㅎㅎ

2021-04-23 11:43 UTC, dave915 commented on src/main/resources/data.sql
> +);
```suggestion
DROP TABLE IF EXISTS `game`;
CREATE TABLE `game` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int unsigned DEFAULT NULL,
  `isEnd` tinyint DEFAULT NULL,
  `createdTime` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `game_history`;
CREATE TABLE `game_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `gameId` int DEFAULT NULL,
  `command` varchar(45) DEFAULT NULL,
  `createdTime` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
```

2021-04-23 11:43 UTC, merged