[1, 2단계 - Spring 적용하기] 욘(김영빈) 미션 제출합니다.
woowacourse/jwp-chess pull request #242
Opened 2021-04-16 06:01 UTC by thisisyoungbin

미립 안녕하세요! 스프링 체스 미션으로 처음 만나뵙네요! ㅎㅎㅎ
체스 코드들은 저번 미션에 완성되어 있어 이번에는 스프링과 연결을 통해 웹에서 동작하도록 만드는데 집중해봤습니다!

[학습 테스트](https://github.com/next-step/spring-learning-test)를 참고해서 진행하며 테스트 코드를 똑같이 짜보고 싶었으나 페이지에 대한 테스트 코드 작성은 아직 어렵더라구요.. 차차 학습하면서 추가 리팩토링 해보도록 하겠습니다!

DB 구조는 아래 이미지와 같습니다.
<img width="221" alt="스크린샷 2021-04-16 오후 2 00 21" src="https://user-images.githubusercontent.com/67272922/114973847-3aa71200-9ebc-11eb-99d1-4b5a58554d6c.png">

리뷰를 위해 귀한 시간 내주셔서 감사합니다!!
거침없는 피드백 부탁드릴게요 :)

2021-04-18 08:43 UTC, seok-2-o requested changes
안녕하세요 욘. 이번 미션을 함께할 미립이에요.
리뷰가 늦어서 죄송해요.

코드는 정말 잘 구현해주셨네요 :)
다만 HTTP 메소드에 대한 학습을 조금 더 진행해보면 좋을 것같아
해당부분에 코멘트 남겨놓았어요.

확인 후 리펙토링 해주세요.

미션 진행하면서 궁금한점이나 어려운 점 있으면 편하게 DM 주세요 감사합니다.

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/controller/dto/BoardDto.java
> +    private final String[][] board;
2차원 배열을 이용하신 이유가 있으실까요? 🤔

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/controller/dto/GameDto.java
> +    private final Board board;
DTO 가 도메인을 가지고 있는것에 대해서 어떻게 생각하시나요
GameDTO 는 BoardDTO 를 가지는게 바람직하지 않을까요?

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/controller/web/ErrorAdvice.java
> +@ControllerAdvice
👍

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/controller/web/GameController.java
> +    @GetMapping("/game/create/{roomId}")
자주 쓰는 http method가 각각 어떤 상황에서 쓰이는지 학습해보면 좋을 것 같아요.
https://developer.mozilla.org/ko/docs/Web/HTTP/Methods

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/controller/web/GameController.java
> +    @GetMapping("/game/create/{roomId}")
추가로 방을 생성할때 클라이언트에서 방 아이디를 지원하는것과 생성해서 아이디를 돌려주는것에 장던점도 고민해보면 좋겟어요.

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/controller/web/GameController.java
> +    @PostMapping("/game/show/{roomId}")
말그대로 조회하는 메소드인데 GET 이 더 명확하지 않을까요?

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/service/dao/GameDao.java
> +        final String query = "SELECT * FROM game_status WHERE room_id = (?) ORDER BY id DESC limit 1";
아이디로 조회하면 하나의 결과밖에 없을 것 같은데 정렬과 limit 이 필요할까요?

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/service/dao/GameDao.java
> +                -> makeGameDto(rs.getString(COLUMN_LABEL_OF_TURN), rs.getString(COLUMN_LABEL_OF_BOARD)), roomId);
조회의 결과가 없으면 어떻게 되나요 ?

2021-04-18 08:43 UTC, seok-2-o commented on src/main/java/chess/service/dao/GameDao.java
> +        }
이번 과정에서는 인덴트를 1번으로 제한하고있어요,

오버엔지니어링이라고 느껴지실 수 있겠지만, 수업이니만큼 한번 지켜보는건 어떤가요?

2021-04-19 07:11 UTC, thisisyoungbin commented on src/main/java/chess/controller/dto/BoardDto.java
> +    private final String[][] board;
페어의 코드로 진행했던 부분이라 신경쓰지 못했었는데요! 이전 레벨 마지막 미션에서 콘솔 출력의 편의성과 체스보드 출력화면에서 인덱스를 지정해 출력할 수 있는 편리함 때문에 사용했다고 생각합니다. 
현재는 Map<String, String>의 자료구조를 가지도록 변경해봤어요.

2021-04-19 07:27 UTC, thisisyoungbin commented on src/main/java/chess/controller/dto/GameDto.java
> +    private final Board board;
도메인은 참조할 수 있지만 반환을 할 수 없다고 알고 있었어요! 근데 여기선 그대로 반환을 하고 있었네요...
Turn과 board를 String값으로 가지도록 변경했습니다. Board, Turn으로 변경하는 것은 Service 계층에서 담당하도록 변경했는데요.
올바르게 사용한 것인지는 아직 잘 모르겠습니다ㅠㅜ

2021-04-20 09:08 UTC, thisisyoungbin commented on src/main/java/chess/service/dao/GameDao.java
> +        final String query = "SELECT * FROM game_status WHERE room_id = (?) ORDER BY id DESC limit 1";
그러네요... 바로 수정했습니다 !!

2021-04-20 09:08 UTC, thisisyoungbin commented on src/main/java/chess/service/dao/GameDao.java
> +        }
교육과정 내에서 당연히 지켜야 하는 부분인데 그렇지 못했네요..! 인덴트 2인 모든 부분들 수정했습니다 !!

2021-04-20 12:22 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/GameController.java
> +    @PostMapping("/game/show/{roomId}")
GET 을 사용하도록 수정했습니다! 

여기서 궁금한 게 생겼는데요! 이 부분은 기물이 움직일 수 있는 좌표를 하이라이팅 해 보여주기 위해 존재했어요. 그래서 자바스크립트에서 갈 수 있는 좌표는 배경색이 변경하도록 바뀌는 부분인데요. 갈 수 있는 위치를 전송하는 게 아니라 조회하기 때문에 GET을 사용하는 게 더 명확하다는 말씀 맞을까요?! 아직 http 메서드에 익숙치 않아 질문도 굉장히 구체적이지 못한 거 같네요..ㅠㅜ

2021-04-20 13:20 UTC, thisisyoungbin commented on src/main/java/chess/service/dao/GameDao.java
> +                -> makeGameDto(rs.getString(COLUMN_LABEL_OF_TURN), rs.getString(COLUMN_LABEL_OF_BOARD)), roomId);
Optional<GameDto>를 반환하고 비어있는 경우 예외페이지로 이동하도록 수정했습니다!

2021-04-20 15:08 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/GameController.java
> +    @GetMapping("/game/create/{roomId}")
현재 방식처럼 아이디를 생성해서 돌려주는 방식의 장점은 클라이언트가 따로 아이디를 기억하거나 관리할 필요 없이 방이름만 기억해서 게임을 진행할 수 있다는 장점이 있을 것 같아요. 단점은.. 서버에서 아이디를 생성해주느라 원하는 아이디를 만들 수 없는 점..? 일까요..ㅠㅜ 사실 잘 모르겠네요. 어떤 의도로 질문주신 건지도 파악하지 못하겠습니다ㅠㅜ.. 제가 더 고민하고 생각해 볼 부분들을 말씀해주시면 감사하겠습니다..!

2021-04-20 15:24 UTC, thisisyoungbin commented
미립 안녕하세요! 리뷰주신 부분들에 대해서 나름 고민해보고 리팩토링을 해봤는데요. 
Http, 스프링 애노테이션 등등 처음 접한 개념들이 많아서 형편 없는 코드지 않나 싶네요..
아직까지 테스트 코드도 작성하지 못 했는데, 이 부분은 인프런에 김영한님 스프링 입문강의를 보면서 꼭 채워보겠습니다!


제가 더 고민하고, 생각해보고, 학습해야 할 부분들이 굉장히 많을 것 같은데요. 빠짐없이 리뷰해주시면 제 성장에 큰 도움이 될 것 같습니다 !
오늘도 리뷰를 위해 시간 내주셔서 감사합니다 ~~ :)

2021-04-21 07:35 UTC, seok-2-o commented on src/main/java/chess/controller/web/GameController.java
> +    @PostMapping("/game/show/{roomId}")
네 쉽게 생각하면 어떤 이유라도 조회는 GET 을 사용한다고 생각해주시면 좋을 것 같아요.

2021-04-21 07:42 UTC, seok-2-o requested changes
피드백 반영 잘 해주셨네요.

조금더 HTTP 메소드와 상태코드에대해서 학습해보셨으면 해서 코멘트 남겨두었어요
확인 후 리펙토링 진행해주세요.

2021-04-21 07:42 UTC, seok-2-o commented on src/main/java/chess/controller/web/RoomController.java
> +    @RequestMapping(value = "/room/new", method = RequestMethod.POST)
```suggestion
    @PostMapping(value = "/room/new")
```

2021-04-21 07:42 UTC, seok-2-o commented on src/main/java/chess/controller/web/RoomController.java
> +        return new ResponseEntity<>("DELETE Response", HttpStatus.OK);
삭제의 결과는 보통 204 NoContent 를 많이 사용해요.

```suggestion
    public ResponseEntity<Void> deleteRoom(@PathVariable Long roomId) {
        roomService.delete(roomId);
        gameService.delete(roomId);
  return ResponseEntity.noContent()
            .build();
```

2021-04-21 07:42 UTC, seok-2-o commented on src/main/java/chess/controller/web/RoomController.java
> +        return "redirect:/game/load/" + roomId;
생성은 보통 201 Created 를 사용합니다
헤더에 새로 생성된 리소스의 위치를 전달할 수 있어요!

2021-04-21 07:42 UTC, seok-2-o commented on src/main/java/chess/domain/ChessGame.java
> +
개행에는 어떤 의미가 있나요 ? 🤔

2021-04-21 07:42 UTC, seok-2-o commented on src/main/java/chess/service/GameService.java
> +        final GameDto gameDto = gameDao.load(roomId).get();
get() 에는 어떤 단점이 있을까요?

2021-04-21 07:43 UTC, seok-2-o commented on src/main/java/chess/controller/web/RoomController.java
> +    @RequestMapping(value = "/room/new", method = RequestMethod.POST)
POST 는 새로운 리소스 생성한다는 의미를 가지고 있어요

그렇다면 new 키워드는 생략 할 수 있지 않을까요

POST /rooms

2021-04-21 10:07 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/RoomController.java
> +    @RequestMapping(value = "/room/new", method = RequestMethod.POST)
!!!
DELETE도 리소스를 삭제한다는 의미를 지니고 있으니 delete 키워드를 삭제했습니다!

2021-04-21 11:37 UTC, thisisyoungbin commented on src/main/java/chess/domain/ChessGame.java
> +
엔터가... 잘못 입력된 거 같습니다...!! ㅠㅜㅠㅜ 수정했어용!

2021-04-21 16:46 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/RoomController.java
> +        return new ResponseEntity<>("DELETE Response", HttpStatus.OK);
삭제는 204 NoContent !! 꼭 기억하겠습니다...!! 감사합니다 👍

2021-04-22 10:32 UTC, thisisyoungbin commented on src/main/java/chess/service/GameService.java
> +        final GameDto gameDto = gameDao.load(roomId).get();
안전하지 않은 점이 단점이라고 생각해요! Optional에 값이 있을 경우 해당 값을 꺼내오지만 없는 경우엔 예외를 던지기 때문에..
그래서 validate를 통해 비어있는 값인 경우 예외를 던지게 했는데.. 
생각해보니 굳이 지금처럼 load를 두 번하고, 또 값을 비교하는 등의 비용 없이 꺼내면서 비어있는 값이면 바로 예외를 던지도록 수정했습니다!
(여기서 예외를 던지면 디미터 법칙에도 어긋나고 해서.. 서비스 클래스까지 가져오지 않고 Dao에서 값이 없는 경우 바로 예외를 던지도록 했습니다.)
지금 코드보단 나은 코드라고 생각해요! 감사합니다 :)
혹시 제가 캐치하지 못한 다른 의미가 있다면 말씀해주세요..!

2021-04-22 13:24 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/RoomController.java
> +        return "redirect:/game/load/" + roomId;
헤더에 새로 생성된 리소스의 위치를 전달 받아 웹에서 헤더에 적힌 주소로 바로 이동해서 방을 만들고 게임이 바로 시작되도록 수정했습니다!!!
응답만 반환하고 응답에 대한 행동이 없다보니 계속 빈페이지가 열려서 해멨어요. 
따로 질문드리면서 말씀해주신 클라이언트에게 판단을 맡긴다는 답변이 많은 도움이 됐습니다!! 감사합니다 미립~~~ 💯

2021-04-22 13:32 UTC, thisisyoungbin commented
미립 안녕하세요~~ 두 번째 리뷰 받은 부분들 고민해가며 리팩토링 해봤습니다!
이제야... http 메서드에 대한 이해와 스프링에 조금씩 익숙해지고 있는 것 같습니다ㅎㅎㅎ
부족한 부분이 있다면 또 리뷰 부탁드려요!! 감사합니다 🙇

2021-04-22 14:37 UTC, thisisyoungbin commented
# 학습로그
## Spring MVC
- 스프링 프레임 워크를 활용해 서버와 웹이 통신한다.
- @GetMapping, @PostMapping 등 어노테이션을 통해 해당 요청에 응답할 수 있다.
- @ComponenetScan, @Component(@Controller, @Service, @Repository) 등의 어노테이션으로 스프링 빈으로 등록 가능하다.
- [학습 테스트](https://github.com/next-step/spring-learning-test/tree/mvc)
## 태그
- Spring Framework, Spring MVC, Web Programming


## Spring JDBC
- Spring JDBCtemplate을 활용해 데이터베이스와 연결할 수 있다.
- [학습 테스트](https://github.com/next-step/spring-learning-test/tree/jdbc)
## 태그
- Spring Framework, Spring Core, Web Programming


## Spring Core
- IoC(제어의 역전) : 프레임워크(스프링)이 객체의 생성과 관리를 담당한다.
- DI(의존성 주입) : 의존성을 주입하는 방식에는 생성자 주입, 필드 주입, setter 주입 방식이 있고 주로 생성자 주입 방식을 사용한다. [링크](https://madplay.github.io/post/why-constructor-injection-is-better-than-field-injection)
- [학습 테스트](https://github.com/next-step/spring-learning-test/tree/core)
## 태그
- Spring Framework, Spring Core, Web Programming


## Http Method
- GET(조회), POST(생성), PUT, DELETE(삭제) 등 상황에 따라 다른 메서드를 사용한다.
- 이번 미션에서는 GET, POST, DELETE 메서드를 사용했다.
- [HTTP 요청 메서드](https://developer.mozilla.org/ko/docs/Web/HTTP/Methods)
## 태그
- Http Method, REST API, Web Programming


## ResponseEntity
- Http 응답에 해당하는 헤더와 바디를 가진 객체
- 상태코드와 헤더를 설정할 수 있다.
- [ResponseEntity란?](https://devlog-wjdrbs96.tistory.com/182)
## 태그
- Web Programming, REST API

## HTTP 응답 코드
- 200 : 요청이 처리됐음을 나타내는 응답 코드
- 201 : 요청에 처리됐고, 자원이 생성됐음을 나타내는 응답 코드
- 302 : 요청을 처리하고 Location 헤더에 주어진 주소로 리다이렉트 한다.
- [HTTP 상태 코드](https://developer.mozilla.org/ko/docs/Web/HTTP/Status)
## 태그
- HTTP 상태 코드, REST API, Web Programming

2021-04-23 10:54 UTC, seok-2-o requested changes
url  설계에 대해 추가적인 코멘트 남겨놓았습니다.
확인 후 리펙토링 해주세요.

2021-04-24 05:39 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/GameController.java
> +        System.out.println(source + " "+ target);
앗,, 디버깅 할 때 작성했던 건데 꼼꼼하게 파악하지 못했었네요... 바로 삭제했습니다!

2021-04-24 05:43 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/GameController.java
> +    @GetMapping("/result/{roomId}")
감사합니다! 변경했습니다 ㅎㅎ!!

2021-04-24 05:45 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/RoomController.java
> +    @GetMapping("/room/list")
확인 후 반영했습니다! 감사합니다~!

2021-04-24 05:55 UTC, thisisyoungbin commented on src/main/java/chess/controller/web/RoomController.java
> +        return new ResponseEntity<>(headers, HttpStatus.CREATED);
접속이 안 되겠네요..!! JS, hbs 파일들까지 수정하게 되니 처음부터 설정을 잘 주자..! 라는 것을 배웠습니다,, ㅎㅎ 감사합니다 미립!

2021-04-24 06:11 UTC, thisisyoungbin commented
안녕하세요 미립~~ url 수정만 하면 되는 것들이라 빠르게 수정해봤습니다! 감사합니다!! 부족한 부분은 또 리뷰 주시면 감사하겠습니다!

2021-04-25 09:34 UTC, seok-2-o approved these changes
피드백을 빨리 반영 해주셨는데, 제가 리뷰가 좀 늦었네요 🙇 

소소한 코멘트 몇가지 남겨 놓았습니다.

다음 미션전에 한번 고민해보시면 좋을 것 같아요.
이번 미션은 종료하도록 하겠습니다. 👍

2021-04-25 09:34 UTC, seok-2-o commented on src/main/java/chess/controller/dto/BoardDto.java
> +    private final Map<String, String> board;
final 키워드로 board 의 변경을 완벽하게 방지 할 수 있을까요.

특히 get을 통해 board 가 노출 되는 상황에서 외부에서 어떤 값을 넣으면 어떻게 될까요.
```
getBoard().put("foo","bar")
```

2021-04-25 09:34 UTC, seok-2-o commented on src/main/java/chess/controller/web/GameController.java
> +    @GetMapping("/load/{roomId}")
```suggestion
    @GetMapping("/{roomId}")
```
같이 간결하게 표현하는 건 어떤가요 REST 방식에서 행위는 HTTP METHOD 를 통해서 표현하는것을 권장합니다.

2021-04-25 09:34 UTC, seok-2-o commented on src/main/java/chess/controller/web/GameController.java
> +    @PostMapping("/move/{roomId}")
HTTP METHOD 로 표현하기 힘든 행위는 맨뒤에서 표현하도록 하는 편 인것 같아요
구글 같은경우에는 `games/{id}:move` 와 같이 표현하기도 하지만 스프링 프레임워크에서는 파싱을 지원하지 않으니
`/games/{id}/move` 같이 표현하는 것도 좋을 것 같아요.

2021-04-25 09:35 UTC, merged