[1, 2단계 - Spring 적용하기] 마갸(정찬영) 미션 제출합니다.
woowacourse/jwp-chess pull request #248
Opened 2021-04-16 09:15 UTC by MyaGya

이번 과제는 크게 어렵지 않았던 것 같아요
기존에 있던 로직을 단순히 스프링으로 바꿔 줄 뿐이었고 오히려 스프링에서 제공하는 DB와 웹 객체를 사용하니 훨씬 쉽게 구현이 가능했습니다.
이번에는 크게 의문이 남는 점은 없었네요, 서버와 클라이언트의 동기화, DB의 세부 구현 방법은 조금 의문이 남았지만 지나가던 브라운에게 질문을 받아 잘 배웠습니다!
편하게 리뷰해 주세요 늦어도 상관없어요!

2021-04-18 08:32 UTC, Hue9010 requested changes
마갸 반가워요! 이번 리뷰를 맡은 휴입니다. 😄
요구사항에 맞춰 스프링으로 이전 잘해주셨네요. 👍 
개선하면 좋을 부분 피드백 남겼는데 확인해주세요. 🙏 
궁금한건 언제든 질문 주세요!!

2021-04-18 08:32 UTC, Hue9010 commented on src/main/java/chess/SpringChessApplication.java
> +	public Response move(@RequestBody MoveRequestDto moveRequestDto) throws SQLException {
또한 

```js
        if (data.code !== 200) {
            alert(data.message);
            return;
        }


        if (data.code === 401) {
            alert(data.message);
            return;
        }
        if (data.code !== 204) {
            alert(data.message);
            return;
        }
```

js에서 위와 같이 요청이 실패했을 때 응답의 message 필드를 사용하고자 한것 같은데 현재 잘못된 이동 등 예외가 발생할 때 ExceptionHandler로 인해 모두 500응답을 하고 있으며 이때 Response 모델을 사용하지 않습니다. 현재 설계한 Response와 ResponseCode가 제대로 동작하지 않는걸로 보입니다.

js를 봤을 때 지금 기대하는 응답형태는 아래와 같습니다.

```
Request URL: http://localhost:8080/move
Request Method: POST
Status Code: 200 

{"code":404,"message":"입력 값에 해당하...
```

이는 js에서도 요청이 실패 했을 때에 대한 처리를 넣어 주고 Line 85에 body에 넣어준 `e.getMessage()`를 활용하는 방법으로 바꿀 수 있을 것 같아요.

그럼 이쯤에서 Response. message가 정말 필요한 값인지 다시 한번 생각 해 볼 수 있을 것 같네요. 🤔

2021-04-19 10:10 UTC, MyaGya commented on src/main/resources/templates/schema.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
mysql workbench에서 자동으로 제공해주는 기능을 사용했었는데 확인이 미흡했네요. 기본값 1부터 시작하도록 변경했었습니다.

2021-04-19 10:11 UTC, MyaGya commented on src/main/java/chess/service/ChessService.java
> +    public void start(long gridId) throws SQLException {
제거했습니다

2021-04-19 10:48 UTC, MyaGya commented on src/test/java/chess/domain/dao/ConnectionSetupTest.java
> +        ConnectionSetup connectionSetup = new ConnectionSetup();
해당 테스트는 스프링 테스트에 맞는 테스트가 아니라 임의로 만든 테스트였어요. `h2` 를 이용한 테스트를 적용하려고 생각하고 있고 다음 미션부터 적용해도 된다고 브라운이 말해서 지웠어야 했는데 테스트는 놔두고 도메인의 연결 코드만 남겨놨었네요 삭제했습니다

2021-04-19 11:10 UTC, MyaGya commented on src/main/java/chess/SpringChessApplication.java
> +@RestController
스파크에서 대충 사용했던 대로 옮겨 사용했더니 이런 방식으로 사용했는데 두 방식은 혼용되지 않는 방식이었군요. 사실 이전 미션에서도 몇 번 application단에서 데이터를 간단하게 받아 넘겨주는게 좋다는 피드백을 받아서 그럼 느낌으로 구현했는데 지금 보니 동시에 여러 기능을 수행하고 있었네요
Application단은 스프링 실행만 수행하고 컨트롤러를 하나 만들어서 url 매핑 작업을 컨트롤러에서 진행시켜주었어요

2021-04-19 11:12 UTC, MyaGya commented on src/main/java/chess/SpringChessApplication.java
> +	private ChessService chessService;
위의 기능 수행을 처리하는 김에 추가로 `ChessService` 클래스를 `Repository` 로 지정하고 `chessService` 를 `Bean` 으로 관리시켰습니다.

2021-04-19 11:23 UTC, MyaGya commented on src/main/java/chess/dto/responsedto/RoomsResponseDto.java
> +    private final List<RoomDto> rooms;
음... 현재 `RoomDto` 로 선언되어 있는 내용을 단순히 감싸기만 하는 기능을 하는 게 `RoomsResponseDto` 이니 해당 값을 사용 시 `RoomsResponseDto` 객체를 사용하지 말고 `List<RoomDto>` 형태로 사용하라는 말씀이신가요? 이 방식에 어떤 이점이 있는지 잘 모르겠어요

2021-04-19 11:36 UTC, MyaGya commented on src/main/java/chess/SpringChessApplication.java
> +		StartRequestDto startRequestDto = new StartRequestDto(roomName);
처음에는 저도 Dto를 통한 값 전달이 번거롭다고 생각했었는데 몇 가지 이유가 있어서 Dto를 적극 사용하는 방법을 쓰게 되었습니다
1. 확장성: 단순히 어떤 서비스가 추가 될 것이다를 떠나서 제시하신 기능처럼 `getRoom` 이라는 기능을 위해서 현재는 `roomName` 만 필요하다고 판단했지만 어떤 값이 더 필요할 지에 대한판단이 어려웠습니다. 따라서 **_모든 데이터 전달 시 Dto를 사용함으로서_** 레이어간 데이터 전달 시 필요한 모든 값을 **_포장_** 했다고 알려주는 느낌으로 사용하고 있습니다.
2. 일관성: 어찌됬든 단순히 값만 전달하는 것 보다는 단 하나의 값이라도 `Dto`로 만들어서 전달하면 다른 여러 값을 전달하는 객체와의 일관성이 유지된다고 생각했습니다.
3. 현재 미션 규모: 현재 미션 규모가 크지 않기 때문에 단순한 `Dto`를 만들더라도 복잡도가 크게 올라가지 않는다고 생각했습니다. 저도 쓸데없는 클래스가 많아지면 몸집이 커보여서 분석하기 어렵다는 생각을 가지고 있기는 한데 이 정도 규모에서는 패키징만 잘 하면 문제 없을 거라고 생각했습니다

이정도 생각을 바탕으로 만들었습니다.

2021-04-19 17:18 UTC, Hue9010 commented on src/main/resources/templates/schema.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
`ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin` 처럼 아예 없어도 됩니다! 😄

2021-04-19 17:21 UTC, Hue9010 commented on src/main/java/chess/SpringChessApplication.java
> +	private ChessService chessService;
push가 안된 상태라 확인이 안되는데 ChessService과 같은 Service layer를 위한 값으로는 @Service가 있답니다. Repository가 아닌 Service를 사용해주시면 됩니다!

다른 코멘트도 포함해서 말씀주신걸 봤을 때 작업이 끝난 것 같은데 혹시 리뷰 요청 중 오류가 있었던걸까요? 확인 부탁드려요. 🙏

2021-04-19 17:24 UTC, Hue9010 commented on src/main/java/chess/SpringChessApplication.java
> +		StartRequestDto startRequestDto = new StartRequestDto(roomName);
이건 제가 속한 조직에서도 팀마다 조금씩 정책이 다른 부분이라 장단점이나 어떤 이유로 특정 방법을 선택했는지 알수만 있다면 충분하다고 생각해요. 그런 점에서 잘 판단해주신 것 같아요. 💯

2021-04-19 17:37 UTC, MyaGya commented on src/main/resources/templates/schema.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
넵, 아예 없애는 식으로 변경했습니다

2021-04-19 17:39 UTC, Hue9010 commented on src/main/java/chess/dto/responsedto/RoomsResponseDto.java
> +    private final List<RoomDto> rooms;
넵 큰 틀에서는 맞습니다. 정확히는 `ResponseDto`로 응답하는 구조이기 때문에 `RoomResponseDto(s가 빠진)` List로 응답하는 걸 말씀 드린 겁니다.

이점보다는 
> GET /room

가 `복수개의 Room을 가진 객체(RoomsResponseDto)`를 요청했다고 봐야할지 `복수개의 Room(List\<RoomResponseDto>)`을 요청했다고 봐야할지의 차이로 봐주시면 될 것 같아요.

우선 전 위 API가 후자의 성격으로 생각했습니다. API 설계를 어떤 방향으로 하셨는지에 따라서도 조금 달라질 수 있는 부분이고, 사내 정책에 따라서도 이에대한 처리가 조금 달라질 수 있답니다.

비슷한 사항으로 객실이 하나도 없을 때
```java
    public RoomsResponseDto(List<RoomDto> rooms) {
        this.rooms = rooms;
    }
```
rooms에 null 값으로 초기화 해주는게 맞을지, 빈 리스트로 초기화 해줄지를 선택할 수도 있습니다.
지금은 구현상 빈 리스트가 들어가겠지만 (의도하셨을 수도 있지만..ㅎㅎ) 이는 `roomDAO.findAllRooms()`의 구현에 따라간 것이지 조회한 값이 하나도 없을 때에 처리방법이 정해져 있진 않은 상태입니다. 그래서 이런 정책(약속)을 정하고 그에 맞춰 구현 할 수 있답니다.

2021-04-19 17:41 UTC, MyaGya commented
따로 요청을 안올렸는데 벌써 확인하셧네요 Response 피드백 관련해서 도메인이랑 엮여 있어서 확인하는데 시간이 좀 걸리고 있습니다 04/20 오후까지는 확인하고 리뷰 요청드릴게요

2021-04-20 03:21 UTC, MyaGya commented on src/main/java/chess/SpringChessApplication.java
> +	public Response move(@RequestBody MoveRequestDto moveRequestDto) throws SQLException {
우선 `Response`를 직접 만들어 주었던 것은 내부의 값을 body 객체에 전달하기 위해서였어요. 네이밍에 문제가 있었다고 볼 수도 있겠네요 이름을 `ResponseDto`로 바꿔주었어요 해당 내용을 커스텀해서 `Response` 객체로 사용한 건 해당 내용을 `body`로 추가하여 응답을 보내려고 한 건데 혼동을 드린 것 같네요. 우선 말씀하신 대로 `ResponseEntity` 객체로 변경해서 명확하게 리넡 해 주었어요. 그 외에 500 에러가 발생하던 부분은 나중에 처리해야지 하고 잊어버렸네요, 다른 URL 매칭 코드와 마찬가지로 예외 처리 문구와 코드를 body에 넣어서 보내도록 구현했어요

2021-04-20 03:31 UTC, MyaGya commented on src/main/java/chess/dto/response/ResponseCode.java
> +    private final int code;
위에서와 마찬가지로 조금 혼동이 드린 것 같아 설명드릴게요
제가 생각한 http 코드를 제공하는 방식은 서버와의 통신이 제대로 성공했다면 무조건 200을 던지는 거였어요.
예를 들자면 체스에서 잘못된 위치를 이동시키더라도 그건 "잘못된 명령" 이 아니라 "결과적으로 이동되지 않는 명령" 으로 받아들여서 200 http 코드를 받아야 하는 거죠. 저는 400, 500 코드 같은 경우는 말 그대로 "오류" 로 받아들였어요 클라이언트의 값이 틀어져서 명령어를 보냈는데 서버에서 제대로 받아들여지지 않아 발생하는 경우 말이죠
그래서 "예상한" 데이터가 오고 가는 경우는 모두 200 응답 코드로 처리를 했는데 이런 방식으로 만드니 200 응답 코드에 비즈니스 로직의 다양한 경우를 모두 담을 수 없었어요
그런데 생각해보니 프로그램을 설치할 때 라던가 게임 설치, 게임 도중 네트워크가 끉어졌을 때 오류가 발생하는 걸 보니 오류[16403]: XXXX~~ 이런식으로 오류를 표현하더라구요. 그래서 이런 방식을 도입해서 `ResponseCode` 는위에서와 마찬가지로 조금 혼동이 드린 것 같아 설명드릴게요
제가 생각한 http 코드를 제공하는 방식은 서버와의 통신이 제대로 성공했다면 무조건 200을 던지는 거였어요.
예를 들자면 체스에서 잘못된 위치를 이동시키더라도 그건 "잘못된 명령" 이 아니라 "결과적으로 이동되지 않는 명령" 으로 받아들여서 200 http 코드를 받아야 하는 거죠. 저는 400, 500 코드 같은 경우는 말 그대로 "오류" 로 받아들였어요 클라이언트의 값이 틀어져서 명령어를 보냈는데 서버에서 제대로 받아들여지지 않아 발생하는 경우 말이죠
그래서 "예상한" 데이터가 오고 가는 경우는 모두 200 응답 코드로 처리를 했는데 이런 방식으로 만드니 200 응답 코드에 비즈니스 로직의 다양한 경우를 모두 담을 수 없었어요
그런데 생각해보니 프로그램을 설치할 때 라던가 게임 설치, 게임 도중 네트워크가 끉어졌을 때 오류가 발생하는 걸 보니 오류[16403]: XXXX~~ 이런식으로 오류를 표현하더라구요. 이런 방식을 도입해서 `ResponseCode` 는 비즈니스 로직을 표현하기 위한 코드고 해당 코드를 JS 에서 받아서 웹 페이지 렌더링에 사용하고 있습니다.
http 코드와는 전혀 관계 없는 코드예요

2021-04-20 07:10 UTC, Hue9010 commented on src/main/java/chess/dto/response/ResponseCode.java
> +    private final int code;
제대로된 리뷰는 이따 밤에 드리도록 할게요. 🙏 
그전에 https://twitter.com/iamdevloper/status/1384074981840097289 에 댓글(?)들을 보면 좋을 것 같아요.
외부 API의 경우(특히 금융)는 성공을 보장해야해서 200으로 응답하고 실패원인을 따로 알려주기도 하는데 내부API라면 그렇게 특수한 방식으로 사용하지 않습니다.

2021-04-20 10:05 UTC, MyaGya commented on src/main/java/chess/dto/response/ResponseCode.java
> +    private final int code;
정말 많은 도움이 됬어요
이전까지는 `http` 상태 코드는 말 그대로 상태 코드라고 생각했거든요, http 연결 상태에 대해서만 해당 코드가 동작해야 한다고 생각했어요. 그러니 200코드가 발생하고 내용이 에러! 라고 놀린 트위터 포스팅 글대로 동작해야 한다고 생각한거죠. 브라운한테 몇 가지 질문을 한게 있었는데 그 중에 

> 도메인 내용을 서버가 몰라야하고 커플링이 발생하면 안된다

라는 항목이 있었어요. 저는 마찬가지로 http 상태 코드도 비즈니스 로직이 성공했는지 아닌지는 각 코드가 몰라도 된다. http 응답과 관련해서는 통신이 성공했는지 아닌지만 확인하고 비즈니스 로직에 대한 처리는 body의 값을 참조한다 라고 생각했거든요. 앞서 예로 들었던 설치나 오류 과정에서 생기는 상태 코드도 당연히 이런 식으로 동작하니 "상태 코드"와 "비즈니스 로직 코드" 를 분리한거였어요. 
그런데 이런 방식으로 짜면 안되고 http 상태 코드에도 로직이 성공했는지 아닌지에 대한 정보를 담아서 보내줘야 하는 거였군요.
에러 발생시 모두 예외로 잡아주고 있었으니 400 에러를 발생시키도록 했고 해당 에러를 js에서 처리해서 경고문을 띄우도록 변경했습니다.

2021-04-20 12:53 UTC, Hue9010 approved these changes
마갸 피드백 반영 잘 해주셨어요! 👍
이번 단계는 여기서 머지하도록 할게요. 
몇가지 피드백 남겼는데 다음 단계 진행하면서 반영해주셔도 충분 할 것 같아요. 😉 
궁금한건 언제든 질문 주세요!

2021-04-20 12:53 UTC, Hue9010 commented on src/main/java/chess/service/ChessService.java
> +@Repository
Service layer에는 @Repository가 아닌 @Service를 사용합니다.

```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Component
public @interface Service {


@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Component
public @interface Repository {
```

기능상에 차이가 있는건 아니고 어떤 layer인지 구분하기 위해 사용됩니다.

2021-04-20 12:53 UTC, Hue9010 commented on src/main/java/chess/controller/SpringController.java
> +    }
ResponseEntity\<Object> 보다는  ResponseEntity\<ResponseDto>로 타입을 명시해주세요.
단순하게 생각하면 List\<Object>를 생각하면 됩니다. List와는 달리 더이상 스프링 내에서 사용되지 않는 값이긴 해도 잘못된 타입이 매핑될 일을 막아 줄 수 있습니다.

마찬가지로 위 다른 ResponseEntity도 타입을 명시해주세요! 응답값이 없을 때는 ResponseEntity\<Void>로 명시해줄 수 있습니다.

2021-04-20 12:53 UTC, Hue9010 commented on src/main/java/chess/controller/SpringController.java
> +            HttpStatus.OK);
```java
ResponseEntity.ok(new ResponseDto(ResponseCode.OK, chessService.getAllRooms()));
```
ResponseEntity는 위와 같이 정적 팩토리 메서드나 빌더를 제공해준답니다.

2021-04-20 12:53 UTC, Hue9010 commented on src/main/java/chess/dto/response/ResponseCode.java
> +    private final int code;
HTTP가 웹 서버의 맨 앞과 뒤에만 물려있는 통신 단계인걸 고려해보면 됩니다. 그런점에서 HTTP와 도메인은 굉장히 멀리 떨어져 있는 사이죠. 😄

2021-04-20 13:05 UTC, Hue9010 commented on src/main/java/chess/SpringChessApplication.java
> +	public Response move(@RequestBody MoveRequestDto moveRequestDto) throws SQLException {
> Response를 직접 만들어 주었던 것은 내부의 값을 body 객체에 전달하기 위해서였어요. 

`body 객체`가 정확히 어떤 걸 말씀하시는건지 알 수 있을까요? 🤔
우선 body를 따로 뒀을 때 큰 장점이 있나요? 
에러 응답의 경우 [Spring Guide - Exception 전략](https://cheese10yun.github.io/spring-guide-exception/)에서 설명하는 

> Error Response 객체는 항상 동일한 Error Response를 가져야 합니다. 그렇지 않으면 클라이언트에서 예외 처리를 항상 동일한 로직으로 처리하기 어렵습니다.

를 위해 따로 만들기도 합니다. 하지만 여기서도 표현했다시피 에러 응답에 한해서 입니다.

이유는 정상 응답이면 요청에 따라
```java
private final chess.dto.responsedto.ResponseDto data;
```

위와 같이 공통 응답모델을 둬도 response의 data에 데이터가 담겨있다는 것 밖에는 알려주지 못합니다. 결국 data가 어떤 형태로 오는지는 알 수 없는건 마찬가지입니다.
data 필드가 없어도 클라이언트에선 body에 바로 요청에 대한 데이터가 있다는걸 알 수 있습니다. 그런 점에서 data가 있는 것과 없는 것에 어떤 차이가 있다고 생각하는지 알 수 있을까요? 🤔 

사실 클라이언트 입장에선 

```java
    private final int code;
    private final String message;
    private final chess.dto.responsedto.ResponseDto data;
```
를 통해 만들어진 json 객체 전체를 요청에 대한 데이터로 봐야합니다.

2021-04-20 13:05 UTC, merged

2021-04-20 13:22 UTC, MyaGya commented on src/main/java/chess/service/ChessService.java
> +@Repository
그렇군요, 오늘 브라운 강의에서 repository와 service의 final 문구에 대해 설명했는데 좀 더 공부하고 분리해서 사용해 보겠습니다

2021-04-20 13:22 UTC, MyaGya commented on src/main/java/chess/controller/SpringController.java
> +    }
에궁 이런 부분들 자꾸 나중에 수정해야지 해놓고 빼먹어 버리네요
앞으로는 TODO리스트를 작성해서 제대로 값을 넣겠습니다

2021-04-20 13:23 UTC, MyaGya commented on src/main/java/chess/controller/SpringController.java
> +            HttpStatus.OK);
빌더를 제공해 주는군요 앞으로는 빌더 형식대로 사용하겠습니다