[1, 2단계 - Spring 적용하기] 수리(이다원) 미션 제출합니다.
woowacourse/jwp-chess pull request #252
Opened 2021-04-16 12:45 UTC by DWL5

안녕하세요 코니! 이번 미션을 리뷰 받게 될 수리입니다.
잘 부탁 드려요!

저번 미션에서 체스게임의 상태를 json으로 저장을 했었어요.
이렇게 구현을 하니 하나의 컬럼을 바꾸는데도 체스게임의 상태를 전부 json으로 직렬화해야 했습니다.
그래서 이번에는 테이블 구조를 나눴습니다..!

구조는 각 테이블마다 1:1 매칭인 Dao가 존재합니다.
그리고 Dao 들을 가진 ChessRepository가 존재합니다.
Repository에서는 Dao들로부터 데이터를 가져와 ChessGame, Room 도메인을 만들어 줍니다.
Service에서는 Repository로 부터 전달받은 도메인으로 비즈니스 로직을 수행하도록 해요. 그리고 웹으로 전달 해야 하는 데이터를 리턴합니다. (ResponseEntity)
Controller에서는 매핑된 요청을 받고 서비스로 부터 받은 값을 응답으로 전달합니다.

코니 한가지 질문이 있습니다..!
현재 Room하고 ChessGame이 연관 되어 있어 하나의 레포지토리에서 룸과 체스게임 도메인을 리턴하고 있습니다. 이런 경우에 분리를 하는 것이 좋을까요?

잘 부탁드립니다 :)  ㅎㅎ

2021-04-18 15:45 UTC, choihz requested changes
안녕하세요, 수리! 리뷰어 코니입니다.

스프링을 잘 적용해 주셨네요 👍 피드백 확인 후 궁금한 점 또는 의견이 있으시다면 언제든 DM 또는 코멘트로 알려주세요!

2021-04-18 15:45 UTC, choihz commented on src/main/java/chess/service/ChessService.java
> +            if (chessGame.move(Position.of(moveDto.getFrom()), Position.of(moveDto.getTo()))) {
`move` 메서드는 실제로 말을 움직이면서 움직임 여부까지 리턴해 주고 있네요. 이렇게 되면 이 메서드는 두 가지 역할을 하는 거라고 볼 수 있어요.

2021-04-18 15:45 UTC, choihz commented on src/main/java/chess/service/ChessService.java
> +            throw new IllegalArgumentException("이동할 수 없습니다.");
`move()` 메서드의 반환값이 `false`이면 여기서 예외를 만들어 주고 있는 구조네요. 위에서 코멘트 남긴 것처럼 두 가지 일을 하고 있는 `move()` 메서드는 반환값 없이 말을 움직이는 일만 하도록 하고, `validateMovable()`에서 `boolean`을 리턴하는 대신 움직일 수 없는 경우 예외를 던지도록 수정해 보면 어떨까요? 이전 방식 대비 어떤 장점이 있는지도 경험해 보시고 알려주시면 좋을 것 같아요.

2021-04-18 15:45 UTC, choihz commented on src/main/java/chess/service/ChessService.java
> +        }
1. 여기서 잡아야 하는 예외가 있나요?
2. 콘솔 출력은 의도적인 걸까요?
3. body가 빈다면 `ResponseEntity.badRequest().build();` 이렇게 하면 됩니다.

2021-04-18 15:45 UTC, choihz commented on src/main/java/chess/domain/ChessGame.java
> +    public double calculateScoreByTeam(final int team) {
사용되지 않는 메서드가 몇 개 있는데 확인 후 지워주세요!

2021-04-18 15:45 UTC, choihz commented on src/main/java/chess/repository/ChessRepository.java
> +public class ChessRepository {
`@Repository` 대신 `@Service`를 사용하신 이유가 있나요?

2021-04-18 15:45 UTC, choihz commented on src/main/java/chess/controller/SpringChessController.java
> +    }
`Room` 도메인 객체를 입력 객체로 사용하고 있는데, 둘이 가지는 값들이 지금은 완전히 동일하더라도 별도의 객체로 분리해 주세요. 또한, 방의 이름과 비밀번호를 검증하는 로직이 없어 빈 값도 들어가고 있네요.

2021-04-18 15:45 UTC, choihz commented on src/main/java/chess/repository/ChessRepository.java
> +    public void createRoom(final ChessGame chessGame, final Room room) {
> 현재 Room하고 ChessGame이 연관 되어 있어 하나의 레포지토리에서 룸과 체스게임 도메인을 리턴하고 있습니다. 이런 경우에 분리를 하는 것이 좋을까요?

네 이건 분리하는 것이 더 좋을 것 같네요.

2021-04-18 15:45 UTC, choihz commented on src/main/resources/static/game.js
> +})*/
사용하지 않는 코드는 이렇게 주석으로 처리하지 마시고 지워주세요~

2021-04-18 15:45 UTC, choihz commented
추가 코멘트 몇 개 남겨요.
1. 웹에서 체스 게임을 실행해 보았는데 폰, 룩, 나이트는 잘 움직이는데 킹, 퀸, 비숍은 잘 안 움직이는 경우가 있더라고요. 이 부분 확인 부탁드려요.
2. 이전 코드를 가져올 때 테스트 코드를 빼신 것은 의도하신 부분일까요? 테스트 코드도 가져오고 이번에 구현한 부분에 대해서도 테스트 코드를 작성해 보아요. 스프링이 처음이라면 어려울 수 있으니 너무 부담 갖지 마시고 할 수 있는 데까지만 학습하며 작성하시면 좋을 것 같아요.

2021-04-19 09:45 UTC, daum7766 commented
안녕하세요! 재연링!
이번에 리뷰를 받게된 멍토입니다.

진행하면서 생긴 궁금증입니다.

1. Long과 long의 차이가 무엇일까요?
Long은 long을 박싱한 Wrapper class입니다.

Long은 Wrapper class이기 때문에 null을 가질 수 있다는 차이가 있습니다.
또한 클래스이기 때문에 비교 연산에서 문제가 생길 수 있습니다. 라고 알고있습니다.
그렇다면 jdbc에서 null을 가질 수 있는 특징때문에 primitive type사용을 추천하게 되는것일까요? 아니면 autoboxing과 unboxing때문일까요?

2.  PUT Method는 어떠한 의미를 가질까요? 또한 체스 말을 움직여라라는 기능을 /room/{id}/piece 라는 URL로 의미를 전달할 수 있을지도 고민해보면 좋겠어요.

이러한 내용이 restAPI의 어려움이라고 생각이 듭니다.
어떻게 해야 url과 메소드로만 원하는 내용을 표현할 수 있을지 만들때마다 고민하는것 같습니다.
PUT Method는 수정한다는 의미를 가지고 있습니다. 그래서 저는 piece를 수정한다. 라는 의미로 사용했는데 명확성이 부족한 것 같습니다.
여기서 제가 고민해본 내용은 뒤에 해당 말의 위치를 표시하여 말의 위치를 변경한다. 로 바꾸는 것이 조금 더 명확하다는 생각을 하게 되었습니다.
제가 생각한 내용이 맞을까요?

3. ExceptionHandler에서 관하여
에러처리를 위해 ControllerAdvice와 ExceptionHandler를 이용했습니다.
여기까지는 이해하겠는데 여기서 CustomException을 어떻게 사용해야 할까요?
현재 상황에서 일반적인 에러에 메세지를 담아서 보내는것과 어떤 차이를 가지게 될까요?
아직까지 CustomException의 필요성읠 크게 느끼지 못하여 이런 생각을 가지게 된것 같습니다. 재연링의 생각이 궁금합니다.

감사합니다.

2021-04-21 16:37 UTC, DWL5 commented on src/main/java/chess/controller/SpringChessController.java
> +    ChessService chessService;
https://devlopsquare.tistory.com/115

피드백을 받고 생성자 주입, 필드 주입, 세터 주입에 대해 공부해 보았습니다..!

2021-04-21 16:38 UTC, DWL5 commented on src/main/java/chess/SpringChessApplication.java
>  public class SpringChessApplication {
Room에 대한 요청을 처리하는 ChessRoomController
Game에 대한 요청을 처리하는 ChessGameController
View에 대한 요청을 처리하는 ViewController
로 분리 해 보았습니다.

2021-04-21 16:38 UTC, DWL5 commented on src/main/java/chess/controller/SpringChessController.java
> +    public ResponseEntity<ChessGameDto> movePiece(@PathVariable("id") Long roodId, @RequestBody MoveDto moveDto) {
넵 ㅜㅜ 수정하겠습니다.

2021-04-21 16:41 UTC, DWL5 commented on src/main/java/chess/controller/SpringChessController.java
> +    public ResponseEntity<ChessGameDto> loadGame(@PathVariable("id") Long roodId, @RequestBody Room room) {
비밀번호를 받아오는 요청이라 Post로 처리를 하였습니다.

도메인 Room과 클라이언트로 부터 받은 데이터가 
@RequestBody를 통해 매핑되어 들어와서 사용을 했었습니다..

컨트롤러 단에서 도메인을 노출 시키는 것 보다 RoomRequestDto를 활용하여 수정을 하였습니다.

2021-04-21 16:42 UTC, DWL5 commented on src/main/java/chess/service/ChessService.java
> +    public void createRoom(@RequestBody Room room) {
필요없는 어노테이션이 들어갔습니다... 제거 했습니다..!

2021-04-21 16:47 UTC, DWL5 commented on src/main/java/chess/service/ChessService.java
> +    }
저렇게 처리할 당시에는 컨트롤러는 요청을 받고 서비스로 부터 받은 값들을 응답해주는 역할로써 구현하였습니다.
서비스는 도메인 로직처리를 끝낸 결과를 바로 컨트롤러가 응답할 수 있게끔 만들어주는 역할 이었습니다.

위의 구현은 제가 컨트롤러를 간단하게 만들고자 하여서 나온결과 입니다. 컨트롤러의 역할인 요청과 응답에 대해서는 덜 고민했었습니다 ㅜ

이번 수정에서는 서비스에서는 도메인 로직 처리 후의 상태인 dto를 전달 해 주고 컨틀롤러에서 어떻게 응답하는지를 결정하는 방식으로 진행했습니다.

2021-04-21 16:47 UTC, DWL5 commented on src/main/java/chess/domain/ChessGame.java
> +    public double calculateScoreByTeam(final int team) {
넵..!

2021-04-21 16:47 UTC, DWL5 commented on src/main/resources/static/game.js
> +})*/
네!

2021-04-21 16:51 UTC, DWL5 commented on src/main/java/chess/repository/ChessRepository.java
> +public class ChessRepository {
3개의 dao(game, team, piece)로 부터 체스 게임을 만드는 로직을 서비스로 부터 분리하고 싶었습니다.

그러다가 레포지토리 레이어로 한번 감싸기로 결정하였습니다.

원래 서비스가 하던 책임을 레포지토리로  분리를 한 것 으로 느껴져서 @Service를 붙히기로 했습니다.

사실 도메인 객체 전달의 역할은 Repository라는 의견도 들었어서 혼란스럽습니다.ㅜㅜ

코니는 어떻게 생각하시나요..?

2021-04-21 16:54 UTC, DWL5 commented on src/main/java/chess/repository/ChessRepository.java
> +    public void createRoom(final ChessGame chessGame, final Room room) {
> 추가 코멘트 몇 개 남겨요.
> 
> 1. 웹에서 체스 게임을 실행해 보았는데 폰, 룩, 나이트는 잘 움직이는데 킹, 퀸, 비숍은 잘 안 움직이는 경우가 있더라고요. 이 부분 확인 부탁드려요.
> 2. 이전 코드를 가져올 때 테스트 코드를 빼신 것은 의도하신 부분일까요? 테스트 코드도 가져오고 이번에 구현한 부분에 대해서도 테스트 코드를 작성해 보아요. 스프링이 처음이라면 어려울 수 있으니 너무 부담 갖지 마시고 할 수 있는 데까지만 학습하며 작성하시면 좋을 것 같아요.

2021-04-21 16:55 UTC, DWL5 commented
네 특정기물이 움직이지 않는 현상은 move 시행 후 뷰 단에서 클래스 리스트를 삭제 시키지 않아 발생했습니다. 수정 진행했습니다!

2021-04-22 05:51 UTC, DWL5 commented on src/main/java/chess/controller/SpringChessController.java
> +    }
Valid  어노테이션을 통해서 유효성 검증하는 방법을 사용해 보았습니다.
이번에 처음 공부하는 내용이라 블로그에 정리 해봤어요!

https://devlopsquare.tistory.com/120

2021-04-22 05:52 UTC, DWL5 commented on src/main/java/chess/repository/ChessRepository.java
> +    public void createRoom(final ChessGame chessGame, final Room room) {
각 레포지토리에서 하나의 도메인 생성만 담당하도록 분리해 보았습니다..!

2021-04-22 08:37 UTC, DWL5 commented
# 체스 학습로그

# Request Mapping - 4

- HTTP Method
- Consumable / Produciable
- Parameters
- Headers
- URI 매핑

# 블로그

- https://devlopsquare.tistory.com/113

# HandlerMethod - 4

체스미션 + 스프링 수업에서 공부했던 핸들러 메소드들 입니다. 취소선 붙은 핸들러 메소드는 추후 공부하겠습니다.

- MethodArgument

  - @PathVariable
    - URI teamplate 변수에 접근
    - 스프링 URI pattern을 참고
  - @RequestParam
    - Servlet request parameters에 접근하기 위한 어노테이션

  - @RequestBody
    - Http request body에 접근하기 위한 어노테이션
  - @ModelAttribute
    - 요청 파라미터들을 객체 프로퍼티에 바인딩
    -  Uri패스, 요청 매개변수, 세션등
  - Errors, BindingReuslt
    - 데이터 바인딩에 관한 exception 처리

# 블로그

Handler Method 부분은 정리 중입니다...!

- https://devlopsquare.tistory.com/120

# REST API - 4

- REST의 개념
- REST의 특징
- REST API의 개념
- REST API 설계 규칙
- RESTful의 개념



<details>
  <summary>접기/펼치기 버튼</summary>
  <div>
    - Method Argument
    	- WebRequest, NativeWebRequest
    	- ServletRequest, ServletReponse
    	-  HttpSesstion
    	-  PushBuilder
    	- Principal
    	- HttpMethod
    	- Locale
    	- TimeZone + ZoneId
    	- InputStream, OutputStream
    	- @PathVariable
  		- @MatrixVariable
    	- @RequestParam
    	- @RequestHeader
      -	@CookieValue
    	- @RequestBody
      - HttpEntity<B>
    	-	@RequestPart
    	-	Model, ModelMap
    	-	RedirectAttributes
    	-	@ModelAttribute
    	-	Errors, BindingReuslt
    	- @Valid, @Validated
  		- @SessionAttributes
  		- UriComponentBuilder
  		- @SessionAttribute
  </div>
</details>





- @ReponseBody

- HttpEntity<B>, ResponseEntity<B>

- HttpHeaders

- String

- View

- Model

- @ModelAttribute

- ModelAndView

- void

- Callable<V>

- ListenableFuture<V>, CompletionStage<V>, CompletableFuture<V>

- ResponseBodyEmitter, SseEmitter

- StreamingReponseBody

- ReactiveAdapterRegistry

2021-04-24 08:13 UTC, DWL5 commented on src/main/java/chess/service/ChessService.java
> +            throw new IllegalArgumentException("이동할 수 없습니다.");
해당 피드백에 대해 고민하면서 ExceptionHandler를 적용해 보았습니다.

ChessGame안에서 책임을 지는 움직임 처리에 대해 캡슐화가 좀 더 완벽해 진 것 같습니다..!
수정을 하니, 서비스에서는 움직이고, 해당 데이터를 저장하는 로직 순서를 한눈에 볼 수 있게 되었습니다.

2021-04-25 16:15 UTC, choihz approved these changes
안녕하세요, 수리!

피드백을 잘 반영해 주셨네요~ 이번에 남긴 피드백은 다음 단계를 진행하시며 참고하시면 될 것 같습니다. 또 만나요~

2021-04-25 16:15 UTC, choihz commented on src/main/java/chess/controller/ChessGameController.java
> +        return ResponseEntity.ok().body(chessGameService.move(gameId, moveDto));
```suggestion
        return ResponseEntity.ok(chessGameService.move(gameId, moveDto));
```
이렇게도 가능해요.

2021-04-25 16:15 UTC, choihz commented on src/main/java/chess/controller/ChessRoomController.java
> +    }
`ChessGameController`에서처럼, 단일 생성자이기 때문에 `@Autowired`는 생략이 가능해요.

2021-04-25 16:15 UTC, choihz commented on src/main/java/chess/dao/GameDao.java
> +    private JdbcTemplate jdbcTemplate;
여기서도 생성자 주입을 사용할 수 있겠네요~

2021-04-25 16:15 UTC, choihz commented on src/main/java/chess/repository/ChessGameRepositoryImpl.java
> +        System.out.println(gameId);
이건 확실히 의도적인 출력은 아닐 것 같네요 😉

2021-04-25 16:15 UTC, choihz commented on src/main/java/chess/repository/ChessRoomRepositoryImpl.java
> +public class ChessRoomRepositoryImpl implements ChessRoomRepository {
> 3개의 dao(game, team, piece)로 부터 체스 게임을 만드는 로직을 서비스로 부터 분리하고 싶었습니다.
그러다가 레포지토리 레이어로 한번 감싸기로 결정하였습니다.
원래 서비스가 하던 책임을 레포지토리로 분리를 한 것 으로 느껴져서 `@service`를 붙히기로 했습니다.
사실 도메인 객체 전달의 역할은 Repository라는 의견도 들었어서 혼란스럽습니다.ㅜㅜ
코니는 어떻게 생각하시나요..?

서비스에 있던 로직이 분리되었다고 서비스가 붙는 게 맞는 걸까요? 지금 하는 역할로 봐선 `@Repository`가 더 적절해 보이긴 합니다.

2021-04-25 16:15 UTC, choihz commented on src/main/java/chess/service/game/ChessGameService.java
> +public interface ChessGameService {
서비스도 인터페이스로 분리하신 이유가 무엇일까요?

2021-04-25 16:15 UTC, choihz commented on src/main/java/chess/service/room/ChessRoomServiceImpl.java
> +        throw new IllegalArgumentException();
예외에 아무 것도 담지 않으면 추후에 원인 파악이 가능할까요?

2021-04-25 16:15 UTC, choihz commented on src/main/java/dto/TeamDto.java
> +    }
사용되지 않고 있네요~

2021-04-25 16:15 UTC, merged

2021-04-28 05:22 UTC, DWL5 commented on src/main/java/chess/controller/ChessRoomController.java
> +    }
controller advice를 사용해서 중복 예외 처리를 수정하였습니다..!!!!!!!!

2021-04-28 06:07 UTC, DWL5 commented on src/main/java/chess/controller/ChessRoomController.java
> +            throw new IllegalArgumentException();
네 방 생성 정보가 유효하지 않을 때, 메시지를 담아 예외를 처리하도록 수정 하였습니닷

2021-04-28 06:27 UTC, DWL5 commented on src/main/java/chess/controller/ChessGameController.java
> +    @PutMapping("/game/{id}")
처음 구현 했을 때는 명사만 넣는 것으로 공부를 해서 그렇게 구현을 했었습니다.
정답은 없었는데 말이죠 ㅜㅜ

저도 이번 미션을 수행하면서 API를 조금 더 명확하게 만드는 것이 좋을 것 같다고 생각했습니다.
피드백 주신 move 뿐만아니라
RoomService의 enter, exit 또한 API를 조금 더 명확하게 수정하였습니다.

2021-04-28 06:31 UTC, DWL5 commented on src/main/java/chess/controller/ChessGameController.java
> +        return ResponseEntity.ok().body(chessGameService.move(gameId, moveDto));
오 이런 꿀팁이...! 변경했습니다.  👍

2021-04-28 06:42 UTC, DWL5 commented on src/main/java/chess/dao/GameDao.java
> +    private JdbcTemplate jdbcTemplate;
네 dao도 생성자 주입으로 수정하였습니다.

2021-04-28 06:54 UTC, DWL5 commented on src/main/java/chess/repository/ChessGameRepositoryImpl.java
> +        System.out.println(gameId);
앗 수정 하였습니다. 😱

2021-04-28 07:22 UTC, DWL5 commented on src/main/java/chess/service/game/ChessGameService.java
> +public interface ChessGameService {
구현체는 로직이 들어가 있어서 어떤 역할을 하는지 한눈에 보기가 어려웠습니다.
해당 서비스가 어떤 일을 하는지 보고 싶어서 인터페이스를 먼저 만들고 구현을 했습니다.

2021-04-28 07:22 UTC, DWL5 commented on src/main/java/dto/TeamDto.java
> +    }
제거했습니다...!

2021-04-28 07:29 UTC, DWL5 commented on src/main/java/chess/repository/ChessRoomRepositoryImpl.java
> +public class ChessRoomRepositoryImpl implements ChessRoomRepository {
저의 경우에는 서비스에서 데이터를 가져와 도메인을 만드는 작업까지 수행을 하도록 처음에 구현을 했었습니다. 다른 분들은 DAO에서 도메인을 리턴하도록 구현하신 분도 있었습니다.

서비스가 비즈니스 로직들을 조합하여 의미있는 순서를 만드는데 집중을 하게 하고 싶었습니다.
그래서 분리를 하였는데... 미션을 수행하면서 

데이터 소스로 부터 데이터를 가져와 도메인을 만드는 작업이 Repository에 조금 더 적합하다는 생각이 되었습니다. (@Repository) 

해당 부분은 변경 하겠습니닷

2021-04-28 07:31 UTC, DWL5 commented on src/main/java/chess/service/room/ChessRoomServiceImpl.java
> +        throw new IllegalArgumentException();
예외에 메시지를 던지도록 수정하였습니닷..!

2021-04-28 07:43 UTC, DWL5 commented on build.gradle
> +    implementation 'junit:junit:4.12'
스프링 테스트가 처음이라 블로그를 참조했습니다. ㅜㅜ

@RunWith(SpringRunner.class)
이게 Junit4에서 사용했던 어노테이션이라고 합니다....!

2021-04-28 07:44 UTC, DWL5 commented on src/test/java/chess/controller/ChessRoomControllerTest.java
> +                .andExpect(status().isBadRequest());
앗 네 다음 pr 때는 테스트를 조금 더 추가해보도록 하겠습니다 ㅎㅎ