Step1
woowacourse/jwp-chess pull request #266
Opened 2021-04-19 08:21 UTC by ggyool

안녕하세요 게이츠~ 우연히 연속으로 리뷰어로 만났네요! 잘 부탁드려요👍
이번 미션은 기존 체스에 스프링을 적용하는 미션이었습니다.
미션을 진행하면서 도메인 부분은 페어의 코드를 가져오고, 프론트 부분은 제 코드를 가져와서 합쳤습니다.
스프링 학습에 집중하고자 웹 관련한 부분은 의논하며 새로 만들기로 하였고, 그 과정에서 스프링에 조금 가까워진 느낌이 듭니다.
Dao와 Service의 테스트 코드는 따로 만들지 않았습니다.
아마 이번주 수업내용에 테스트 관련한 부분이 있을 것 같아, 수업을 듣고 추후에 추가하도록 하겠습니다.

**미션 중 생겼던 의문 두 가지**

1. 요청은 성공했지만 실행중 문제가 발생시 응답은 어떻게 보내야 하는지
처음 만들었던 UserController 에서는 성공시 200이나 201을 응답하고, DataAccessException 발생시 400에러를 발생시켰습니다.
하지만 JS코드를 만들다 보니 실행 중 실패한 경우도 응답을 200으로 하고 응답 body에 내용을 추가하는게 뭔가 확실하게 체크할 수 있을 것 같았습니다.
현업에서 어떤식으로 응답을 보내는지 궁금합니다. 😢

2. 클라이언트에서 요청할 때 현재 페이지가 /gams/1 이고 /games/1/move 에 POST 요청을 보내야 하는 상황에서
아래와 같이 URI의 1을 파싱하여 서버로 보낼 주소에 이용했습니다.
이유는 잘 모르겠지만 만들고 보니 뭔가 꺼림직해서 이렇게 하는 게 문제가 없는지 궁금합니다.
```javascript
#findGameIdInUri() {
  const path = window.location.pathname
  const gameId = path.substr(path.lastIndexOf("/") + 1);
  return gameId;
}
```

**리뷰하실 때 도움 될만한 내용**
1. ddl 이라는 폴더에 sql을 넣어두었습니다.
2. swagger를 추가해 두었습니다. http://localhost:8080/swagger-ui.html 
3. 게임진행 흐름
- 회원가입을 한다. (이름이 겹치면 안된다.)
- 방만들기를 한다. (존재하는 이름의 회원이어야 한다.)
- 이어하기에는 방번호를 입력해야 한다. (추후에 수정할 계획)

**ERD**
<img width="669" alt="erd" src="https://user-images.githubusercontent.com/12393067/115204103-1739cc80-a133-11eb-875e-ab0ac7b2f2d1.png">

**home**
<img width="1791" alt="home" src="https://user-images.githubusercontent.com/12393067/115204165-24ef5200-a133-11eb-993a-273aeb4be1b2.png">

2021-04-20 23:42 UTC, serverwizard requested changes
중간곰 안녕하세요! 이번에 리뷰를 맡게 된 (빌)게이츠입니다 🙇♂️
Spring 적용하기 미션 구현 잘 해주셨네요  👍

몇 가지 코멘트 남겼어요. 확인부탁드릴게요!
궁금한점 있다면 언제든 DM주세요!

2021-04-20 23:42 UTC, serverwizard commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
View를 반환하는 Controller와 Json을 반환하는 RestController를 나누는 건 어떨까요?
현재1개의 컨트롤러에서 모두 관리하고 있는 것 같아서요.

2021-04-20 23:42 UTC, serverwizard commented on src/main/java/chess/controller/ChessController.java
> +    @PostMapping("/creation")
URI에 굳이 `/creation`을 붙이지 않고, HTTP 요청 메소드(주어진 리소스에 수행하길 원하는 행동)도 의미를 가지니 `POST /chess`라고 표현할 수는 없는 걸까요?

2021-04-20 23:42 UTC, serverwizard commented on src/main/java/chess/controller/ChessController.java
> +    public ResponseEntity<Map<String, Boolean>> checkMovement(@PathVariable long gameId,
Map으로 응답 값을 리턴할 수도 있지만, 객체를 통해 응답 값을 리턴하는 건 어떨까요?
이렇게 되면, 객체 내 필드명이 있기 때문에 해당 데이터가 무엇을 의미하는지 좀 더 명확히 알 수 있을 것 같아서요.

2021-04-20 23:42 UTC, serverwizard commented on src/main/java/chess/dao/GameDao.java
> +public class GameDao {
Repository와 Dao의 차이는 무엇일까요?

2021-04-20 23:42 UTC, serverwizard commented on src/main/java/chess/service/ChessService.java
> +@Transactional
트랜잭션 사용 👍 

시간이 되신다면 트랜잭션의 isolation level과 propagation 옵션에 대해서도 학습해보시면 좋을 것 같아요.

2021-04-20 23:42 UTC, serverwizard commented on src/main/java/chess/exception/CommonExceptionAdvice.java
> +public class CommonExceptionAdvice {
ControllerAdvice 👍

2021-04-22 18:28 UTC, ggyool commented
# 학습로그 (후에 더 추가할 예정)
<br>

## GET과 POST요청 성공과 실패에 따른 응답코드
- GET의 경우 성공 시 200 (ok) 상태 코드와 적절한 body를 반환
- POST의 경우 성공 시 201 (created) 상태 코드와 Location 헤더에 자원의 생성 위치 포함
- 성공한 경우는 별다른 고민 없이 떠올릴 수 있었다.
- 하지만 요청에 실패한 경우 어떤 응답 코드와 body를 반환해야 할지 고민이 됐다.
- 페어와 의논한 결과 400 (bad request) 상태 코드를 반환하기로 하였다.
- https://docs.microsoft.com/ko-kr/azure/architecture/best-practices/api-design
- 그러던 중 위의 링크를 보게 되었고, GET 요청에 실패했을 경우 자원이 생성되지 않을 테니 404 (not found)를 반환하는 것은 상당히 타당해 보인다.
- 그렇지만 POST 요청에 실패하는 경우 여러 이유가 있을 수 있기 떄문에
- 클라이언트에서 보낸 데이터의 문제였다면 400 (bad request)를 반환하는 게 좋아보이고
- 서버에서의 문제라면 50x에러를 반환하는게 좋아보인다.
## 태그
- HTTP, HTTP Status Code

<br>

## DTO의 사용 계층
- DTO와 도메인의 변환을 어느 계층에서 할지 고민하였다.
- 우리가 일반적으로 사용하는 DTO는 클라이언트와 서버간 전송하는 데이터를 담는 객체라고 생각했고, 우리가 만드는 앱의 API에 의존적 이라고 생각한다.
- 그러한 이유로 Web 요청과 응답을 담당하는 Controller에서 도메인 변환을 하는게 가장 적절하다는 생각이 들었고, 그렇게 만든다면 하나의 Service를 여러 Controller가 사용할 수 있다는 장점이 있어 보였다.
- 하지만 Controller에서 도메인 변환이 이루어지면 도메인의 존재를 몰라도 되는 Controller도 도메인의 존재를 알게 되는 불안한 점이 존재한다. 도메인을 노출하기 싫다면 DTO의 필드들을 하나하나 풀어서 Service 메서드로 전달하면 되겠지만 인자의 수가 많아지면 컬렉션에 넣어서 전달한다든지 불편한 방법을 사용해야 할 것 같다.
- 이번 미션에서는 위의 이유에 무게를 두어 Service 레이어에서 DTO와 도메인을 변환하였다.
## 태크
- DTO

2021-04-28 17:51 UTC, ggyool commented on src/main/java/chess/controller/ChessController.java
> +public class ChessController {
분리했습니다👍

2021-04-28 17:54 UTC, ggyool commented on src/main/java/chess/controller/ChessController.java
> +    @PostMapping("/creation")
리팩토링 하면서 구조가 바뀌었고 ChessController가 사라졌습니다.
resource를 DB와 연결지어서 생각했었습니다. 수업을 들으며 그렇지 않다는 것을 깨달았습니다.
리패토링 /games   /users는 당연시하게 POST




chess라는 테이블이 없어서 어색함을 느ㄱ

2021-04-28 18:08 UTC, ggyool commented on src/main/java/chess/controller/ChessController.java
> +    public ResponseEntity<Map<String, Boolean>> checkMovement(@PathVariable long gameId,
이 부분을 제외하면 모든 요청과 응답에서 DTO를 사용했습니다. 페어 진행시 이 부분을 Map으로 처리한 이유는 필드가 1개인데 클래스를 만드는 것에 대한 어색함 때문이었습니다.
하지만 웹 API라는 게 변하기 마련이고 (계속 1개일 거라는 보장도 없고) DTO를 사용한다면 요청과 응답에 대한 API도 눈에 확 들어오고, Map을 사용하여 값을 가져오면 실수하면 디버깅도 힘들기 때문에 장점이 더 많아 보였습니다.

2021-04-28 19:15 UTC, ggyool commented on src/main/java/chess/dao/GameDao.java
> +public class GameDao {
뷰를 받기 전에도 크루들 사이에서 Repository와 Dao이 뜨거운 감자라는 걸 알고 있었지만,
Repository라는 용어가 DDD에서 나오는 개념이라고 들었고, DDD를 공부할 단계는 아니라고 생각하여 회피하고 있었습니다.
그러던 중 이 리뷰를 받았고 살짝 Repository와 Dao의 차이 정도는 알고 넘어갈까? 로 시작했는데
DDD에 배경지식이 전무한 상황에서 헤딩하다보니 개념을 잡는데 시간을 많이 소비했습니다.

포비와 코치분들이 지금 단계에서는 Repository와 Dao를 같다고 생각해도 된다고 하셔서 넘어갈까도 생각했지만..
리팩토링 전 코드는 Service에 로직이 많았고 도메인은 Anemic 했기 때문에 이 부분을 개선하고 싶었습니다.
자연스레 DDD에 관한 자료들을 많이 접했고 학습했지만 DDD를 공부한다기보다는 도메인에 로직을 넣어 객체지향적인 코드를 만들고 싶었습니다.

리팩토링하며 달라진 구조
1. Service에 로직이 없어졌습니다.
2. Repository를 통해 도메인에 접근합니다.
3.  도메인에서 비즈니스 로직을 실행합니다.
4. Repository는 해당 애그리거트의 영속성을 관리합니다.

이전 코드에 비하면 리팩토링 후 구조가 깔끔해졌다고 생각합니다.
개인적으로 구조 설계에 대한 시야도 넓어진 것 같습니다. 감사합니다. 👍
혹시 이상한 부분 있으면 알려주시면 개선하겠습니다😢

Repository와 Dao의 차이에 대해..
이론적인 공부가 부족하여 주관적인 의견을 쓸 것 같아 적지는 않겠습니다.😭 시간될 때 책을 보려고 합니다.
Repository나 Dao는 개념적으로 다르지만 상황에 따라 같을수도 있다고 생각합니다.
DDD를 적용하려는 사람 입장에서는 당연히 많은 차이가 있겠고,
저의 리팩토링 이전 코드 처럼 Service에 로직을 넣고 DAO를 쓰는 방식으로 구조를 짠다면 군집 단위로 영속성을 관리할 필요를 못 느낄 것이기 때문에 곧 DAO가 Repository라고 말해도 된다고 생각합니다. (주관적인 생각)

2021-04-29 02:33 UTC, ggyool commented
안녕하세요~게이츠 피드백 남기신 부분에 답변 달았습니다 !!
그리고 저번에 남긴 질문에 대해 답변을 주신다고 하고 안 주셨어요 😭😭😭
1번 질문은 어느정도 방향을 잡아서 학습로그에 적어두었고, 2번 질문은 아직 궁금합니다!
이번에 구조를 완전히 갈아 엎었는데 이상한 부분 있으면 알려주세요 🙏

2021-05-01 07:57 UTC, serverwizard commented
```
요청은 성공했지만 실행중 문제가 발생시 응답은 어떻게 보내야 하는지
처음 만들었던 UserController 에서는 성공시 200이나 201을 응답하고, DataAccessException 발생시 400에러를 발생시켰습니다.
하지만 JS코드를 만들다 보니 실행 중 실패한 경우도 응답을 200으로 하고 응답 body에 내용을 추가하는게 뭔가 확실하게 체크할 수 있을 것 같았습니다.
현업에서 어떤식으로 응답을 보내는지 궁금합니다. 😢
```
좋은 질문이네요!

근데 설계에 정답이 없듯 이 부분도 명확한 정답은 없는 것 같아요!
말씀하신 것처럼 실패한 경우에도 응답은 200으로 주되 response body에 에러 내용을 담아서 보내는 경우도 봤구요
또 다른 곳에서는 애초에 4xx대 에러를 내려주기도 하더라구요.

제가 담당하고있는 서비스에서는 4xx대 에러를 내려주고 있어요!

```
클라이언트에서 요청할 때 현재 페이지가 /gams/1 이고 /games/1/move 에 POST 요청을 보내야 하는 상황에서
아래와 같이 URI의 1을 파싱하여 서버로 보낼 주소에 이용했습니다.
이유는 잘 모르겠지만 만들고 보니 뭔가 꺼림직해서 이렇게 하는 게 문제가 없는지 궁금합니다.
```

2021-05-01 08:24 UTC, serverwizard approved these changes
중간곰 1,2단계 진행하시느라 고생하셨습니다 👍 

질문에 대한 답변만 다음단계 진행하실 때 확인 부탁드릴게요.
이번 단계는 여기서 머지할게요!

다음 단계 진행해주세요~!
고생하셨습니다 👍

2021-05-01 08:24 UTC, serverwizard commented on src/main/java/chess/dao/GameDao.java
> +public class GameDao {
일단, 코멘트를 드린 이유는 클래스명은 Dao라고 하셨는데 애노테이션으로 @repository를 사용하셨더라구요.
그래서 이참에 학습해보면 좋지 않을까 생각했어요~ (코드 수정하라는 의미는 아니었어요)

그리고 학습 정말 잘해주셨어요 👍

제 개인적으로는 DAO는 데이터베이스의 CRUD 쿼리와 1:1 매칭되는 세밀한 단위의 오퍼레이션을 제공하고. 반면 Repository는 메모리에 로드된 객체 컬렉션에 대한 집합 처리(추후 배우게 될 영속성 컨텍스트)를 위한 인터페이스를 제공하는 개념으로 알고 있어요.

사실 이 둘은 거의 동일시 돼 사용되긴 하는데요.
앞으로 DDD/JPA를 학습할 때 이 둘의 차이점을 배울 기회가 있을거에요. :)

2021-05-01 08:24 UTC, serverwizard commented on src/main/java/chess/service/UserService.java
> +public class UserService {
시간이 되신다면 트랜잭션 개념과 트랜잭션의 isolation level과 propagation 옵션에 대해서도 학습해보시면 좋을 것 같아요.
면접에서 많이 나오는 질문이기도 하고 중요한 부분이거든요.

2021-05-01 08:24 UTC, serverwizard commented on src/main/java/chess/web/apicontroller/UserApiController.java
> +@RequestMapping("/api/users")
실무에서는 `/api/v1(버전)/users` 식으로 버전 정보도 명시해준답니다.

API URI에 버전 정보를 붙여주는 이유는
v1으로 만든 API를 운영에 배포한 상태에서, 요구사항이 변경된 경우 v1을 수정하는게 아니라(행여 기존에 해당 API를 사용하고 있는 서비스에 영향을 주지 않기 위함) v2를 새로 만드는 식으로 하기 위함이에요.

2021-05-01 08:24 UTC, serverwizard commented on src/main/java/chess/web/controller/ControllerExceptionHandler.java
> +public class ControllerExceptionHandler {
ControllerAdvice 👍

2021-05-01 08:24 UTC, merged

2021-05-01 08:24 UTC, serverwizard commented
```
요청은 성공했지만 실행중 문제가 발생시 응답은 어떻게 보내야 하는지
처음 만들었던 UserController 에서는 성공시 200이나 201을 응답하고, DataAccessException 발생시 400에러를 발생시켰습니다.
하지만 JS코드를 만들다 보니 실행 중 실패한 경우도 응답을 200으로 하고 응답 body에 내용을 추가하는게 뭔가 확실하게 체크할 수 있을 것 같았습니다.
현업에서 어떤식으로 응답을 보내는지 궁금합니다. 😢
```
좋은 질문이네요!

설계에 정답이 없듯 이 부분도 명확한 정답은 없는 것 같아요!

말씀하신 것처럼 클라이언트 요청이 서버에서 정상적으로 처리가 안 됐을 때 HTTP 응답 코드는 200, response body에 에러 메시지를 담아서 보내주는 경우도 봤었고 또 다른 쪽에서는 애초에 4xx대 에러를 내려주는 것도 봤었거든요.

따라서, 이 부분은 함께 일하고 있는 동료들과 정하면 좋을 것 같아요.

참고로 제가 담당하고있는 서비스에서는 4xx대 에러를 내려주고 있답니다!

```
클라이언트에서 요청할 때 현재 페이지가 /gams/1 이고 /games/1/move 에 POST 요청을 보내야 하는 상황에서
아래와 같이 URI의 1을 파싱하여 서버로 보낼 주소에 이용했습니다.
이유는 잘 모르겠지만 만들고 보니 뭔가 꺼림직해서 이렇게 하는 게 문제가 없는지 궁금합니다.
```
제가 이해한 것이 맞는지는 모르겠지만

전체 사용자를 조회하는 API URI는 보통 `GET /users` 식으로 많이 사용하고 있고, 전체 사용자가 아닌 특정 사용자를 조회하는 API URI는`GET /users/1`형태로 많이들 사용한답니다.

따라서, id 값을 URI에 사용하는 경우는 흔한 일이에요~

단, 위에서 말씀 주신 `GET /games/1` URI라고 한다면 여러 게임들이 있는데 그 중에 1번 게임을 조회하는 API 구나라는 생각이 들어요