[1, 2단계 - Spring 적용하기] 소롱(최솔지) 미션 제출합니다.
woowacourse/jwp-chess pull request #270
Opened 2021-04-19 15:23 UTC by soulgchoi

안녕하세요 데이브! 또 뵙게 되어서 기쁩니다🥰🥰

프론트에 투자를 좀 해서 시간은 많이 걸렸지만, 다양한 요청을 보내면서 스프링을 빨리 배울 수 있었다고 생각합니다!
질문 몇개 남겨놓겠습니다.

1. LobbyController에서 `roomName`을 POST 요청으로 보내는 로직이 몇 개 있는데요,    POST는 뭔가 데이터를 넣고 삽입, 수정 등 조작하는 메서드라고 생각해서 이 부분이 걸립니다.
   요청은 POST로 보내지만 조회 역할이므로 GET이 맞다고 생각했어요.    하지만 데이터 전달과 `@Valid` 사용을 위해 일단 body에 넣어 구현하게 되었습니다. 이렇게 하는게 맞는지 다른 방법이 있는지 궁금합니다!

2. 컨트롤러에서 DTO로 데이터를 받을 때 에러가 발생해서 꽤 오래 고생했는데 빈 생성자가 없어서였어요.
   모든 DTO는 빈 생성자가 필수인가요? 왜 그런지도 알려주시면 감사하겠습니다.

3. > 저는 WebUIApplication은 Controller의 설정을 셋팅을 해주고 있고 WebController가 Controller, Servcie역할 모두 수행 하고 있다고 생각이 들어요. 만약 소롱 말씀대로 서비스처럼 동작하고 있다면 객체명이 WebController면 안될 것 같다는 생각이 드네요 🤔 
   > WebUIApplication은 Controller의 설정을 셋팅을 해주고 있고 이 부분이 받아들이지 않는다면 WebController 내부에 init() 메소드를 만들고 Main의 get("/lobby/new", webController::newGame); 같은 Path와 수행할 메소드를 매칭 해주는 로직을 옮기는 것도 좋을 것 같아요 :)

     지난번에 이런 코멘트를 주셨는데 지금 Contoller, Service는 제 역할을 하고 있는걸까요?
     레벨 1 체스 미션의 WebUIApplication이 Controller 역할을 하고 Service를 분리했다고 생각하는데 맞는지 궁금합니다.

4. Serializer의 위치는 어디가 좋을까요? 나중에 Selrializer가 많아지면 분리해서 한 곳에 관리하게 되나요?
5. 같은 로직을 수행하는데 api만 달라지게 만들어도 되나요? 저희는 `roomName`으로 보낼 때와 `roomId`로 보낼 때 같은 Service를 사용하는 경우가 있었어요.
6. 체스 말이 움직일 수 없을 때 에러를 보내는데 콘솔에 계속 뜨는 게 신경쓰이더라구요. 이런건 프론트에서 처리하는 게 좋은가요 아니면 백에서 상태는 200으로 보내되 boolean이나 다른 값을 주는 편이 나은가요?
7. 체스 게임의 이름, 아이디, 점수 상황, 종료 여부 등을 각각의 요청을 보내서 가져오고 있어요. 공부하는 데는 좋았지만 요청이 이렇게 많아도 되나..? 하는 생각 들었습니다. 데이터를 한 번에 주고 프론트에서 다 처리하는 게 좋은지도 궁금합니다!!

피드백 늘 큰 도움이 되고 있습니다.
이번에도 잘 부탁드려요😆

2021-04-20 23:52 UTC, dave915 requested changes
소롱 안녕하세요! 레벨2도 함께 하네요 ㅎㅎ
미션 구현 잘 해주셨습니다 :) 
몇가지 코멘트 남겼어요. 확인 부탁드려요! 
궁금한점 있으면 언제든지 질문주세요!

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/LobbyController.java
> +        }
이 부분은 ExceptionController에서 처리해도 될 것 같아요 :)

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/LobbyController.java
> +@Controller
페이지 이동 관련된 Controller를 따로 분리하고 @RestController를 사용해도 될 것 같아요 😁

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/LobbyController.java
> +    public ResponseEntity isDuplicate(@RequestBody TitleDTO titleDTO) {
전 명시적으로 리턴타입을 정해주는 편이에요 :) 
```suggestion
    public ResponseEntity<DuplicateDTO> isDuplicate(@RequestBody TitleDTO titleDTO) {
```

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/ExceptionController.java
> +    public ResponseEntity illegalArgumentException(IllegalArgumentException error) {
```suggestion
    public ResponseEntity<Void> illegalArgumentException(IllegalArgumentException error) {
```

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/GameController.java
> +    @GetMapping("/turn/{gameId}")
ID이기 때문에 String으로 받아도 무관하다고 생각해요 :)

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/GameController.java
> +    }
이 부분도 ExceptionController에서 처리해주세요 :)

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/dto/TitleDTO.java
> +    @Size(min = 1, max = 20, message = "방 이름은 1글자 이상 20글자 이하여야 합니다.")
👍

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/ExceptionController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
예상하지 못한 Exception을 처리하기 위해 @ExceptionHandler(Exception.class)를 처리해주는 메소드도 만들어주세요!

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/GameController.java
> +    @PostMapping("/finish/{gameId}")
특정 game의 finish 상태를 바꾸는 것이기 때문에 `/game/{gameId}/finish` 로 하는 것이 더 명확하지 않을까요?

2021-04-20 23:52 UTC, dave915 commented on src/main/java/chess/controller/GameController.java
> +    @GetMapping("/scoreById/{gameId}")
`/game/{gameId}/score` 는 어떠신가요? 
아래 링크도 읽어보시면 좋을 것 같아요 :) 

https://meetup.toast.com/posts/92

2021-04-20 23:53 UTC, dave915 commented
>LobbyController에서 roomName을 POST 요청으로 보내는 로직이 몇 개 있는데요, POST는 뭔가 데이터를 넣고 삽입, 수정 등 조작하는 메서드라고 생각해서 이 부분이 걸립니다.
요청은 POST로 보내지만 조회 역할이므로 GET이 맞다고 생각했어요. 하지만 데이터 전달과 @Valid 사용을 위해 일단 body에 넣어 구현하게 되었습니다. 이렇게 하는게 맞는지 다른 방법이 있는지 궁금합니다!

조회 API 라면 Get을 사용하는것이 좋을 것 같아요! @Validate를 사용하면 PathVariable로 들어오는 값도 체크할수있어요.
https://jeong-pro.tistory.com/203

>컨트롤러에서 DTO로 데이터를 받을 때 에러가 발생해서 꽤 오래 고생했는데 빈 생성자가 없어서였어요.
모든 DTO는 빈 생성자가 필수인가요? 왜 그런지도 알려주시면 감사하겠습니다.

Json을 DTO로 맵핑시켜주는 Jackson에서 기본 생성자를 사용 하는것 같아요. 또 다른 방법으로 @JsonCreator 를 사용하면 됩니다 ㅎㅎ 

>지난번에 이런 코멘트를 주셨는데 지금 Contoller, Service는 제 역할을 하고 있는걸까요?
레벨 1 체스 미션의 WebUIApplication이 Controller 역할을 하고 Service를 분리했다고 생각하는데 맞는지 궁금합니다.

역할에 맞게 분리 하신것으로 보이네요 :) 

>Serializer의 위치는 어디가 좋을까요? 나중에 Selrializer가 많아지면 분리해서 한 곳에 관리하게 되나요?

Serializer는 현재 ChessBoard 상태를 저장을 위한 String <-> Object 변환에 사용되는 객체 같은데 저는 ChessGame 내부에 넣었을 것 같아요! 
하지만 Serializer로 객체 분리한다면 저는 Domain하위에 serializer 패키지를 두고 해당 패키지 내에 여러 Serializer를 둘 것 같아요.

>같은 로직을 수행하는데 api만 달라지게 만들어도 되나요? 저희는 roomName으로 보낼 때와 roomId로 보낼 때 같은 Service를 사용하는 경우가 있었어요.

그럼요! 가능합니다. 그렇기 때문에 한 Service가 특정 Controller에 의존성이 생기지 않게 구현하는것이 중요해요. 

>체스 말이 움직일 수 없을 때 에러를 보내는데 콘솔에 계속 뜨는 게 신경쓰이더라구요. 이런건 프론트에서 처리하는 게 좋은가요 아니면 백에서 상태는 200으로 보내되 boolean이나 다른 값을 주는 편이 나은가요?

음.. 처리 방법은 여러가지겠지만 저는 api가 성공일때만 status 200을 사용하고 있어요. 

>체스 게임의 이름, 아이디, 점수 상황, 종료 여부 등을 각각의 요청을 보내서 가져오고 있어요. 공부하는 데는 좋았지만 요청이 이렇게 많아도 되나..? 하는 생각 들었습니다. 데이터를 한 번에 주고 프론트에서 다 처리하는 게 좋은지도 궁금합니다!!

한 요청으로 처리 할 수 있다면 한번에 데이터를 받아오는것이 좋다고 생각합니다 :) 


몇가지 코멘트 더 남길게요!
1. 혹시 mysql 대신 h2를 사용해보실 생각 있으신가요?
h2인 경우 메모리에 올라가는 DB이기 때문에 각 개발자 로컬에서 개인적으로 DB 셋팅을 안해줘도 되기 때문에, 테스트 또는 지금처럼 학습용 프로젝트에서 많이 쓰이고 있어요 :)
https://www.baeldung.com/spring-boot-h2-database

2. Controller, Service, Repository Layer에 관한 테스트도 추가하면 좋을 것 같아요!

3. Spring 관련해서 공부해보셨으면 하는 점도 몇개 남겨둘게요! (이 부분은 코드에 반영할건 아니고, Spring하면 기본적으로 알아야 한다고 생각해서 남겼어요 ㅎㅎ )

- Spring에서 request 처리 과정
- @responsebody는 어떤 역할을 해줄까?
- @componentscan과 빈 주입 방법 (@Autowired, 생성자 주입)

2021-04-27 12:43 UTC, soulgchoi commented
안녕하세요 데이브~!
코드 리팩토링 및 테스트 추가 완료했습니다. 리팩토링 과정까지 페어와 함께했어요.

아래는 피드백 반영하여 변경된 내용들입니다.

1. 방 이름 뒤에 빈칸이 있을 시 실행이 제대로 안되는 버그가 있어서 수정했습니다.
2. Controller와 RestController 말씀하신 대로 분리했습니다. 코드가 더 보기 편해져서 좋아요.
3. ReponseEntity에 모두 타입 지정했습니다.
4. Exception.class 까지 ExceptionController에서 핸들링하도록 수정했습니다.
5. API를 많이 정리했습니다. room 이라는 리소스로 묶고 나머지 작업들을 수행합니다. 그러면서 API가 많이 줄고, HTTP 메서드가 잘못 됐던 부분들(GET을 쓰고 싶었는데 POST를 했다거나) 하는 부분들은 자연스럽게 고쳤습니다!
6. 생성자가 하나일 때 @Autowired 생략했습니다.
7. 테스트 코드를 추가했습니다!
   - DB를 h2로 변경해보라고 하셨는데, 테스트 코드에 h2를 적용했습니다. 두 가지 모두 경험할 수 있어서 좋았습니다! 
   - 기본적으로 MockMvc로 구현했습니다.
   - 테스트마다 일관성이 조금 부족하다고 느껴지는데 어떤지 모르겠어요. 피드백 부탁드립니다~!!

오래 걸렸지만 많이 고치고 뿌듯한 시간이었습니다.
이번에도 잘 부탁드려요😆

2021-04-29 16:09 UTC, dave915 approved these changes
소롱 안녕하세요! 
피드백 반영한 부분 확인했습니다 👍 
고생 많으셨네요 ㅎㅎ 
이번 단계는 이만 머지할게요! 
혹시 궁금한점 있으면 편하게 질문주세요 😁

2021-04-29 16:09 UTC, dave915 commented on src/main/java/chess/controller/HomeController.java
> +        return "./index";
`{id}` 는 사용하지 않는걸까요?

2021-04-29 16:09 UTC, dave915 commented on src/main/java/chess/controller/api/GameController.java
> +@RequestMapping("/room")
👍

2021-04-29 16:09 UTC, dave915 commented on src/test/resources/application-test.properties
> +spring.datasource.url=jdbc:h2:tcp://localhost/~/test;MODE=MySQL;DB_CLOSE_DELAY=-1
Test일 경우 파일DB를 사용하기 보단 테스트 마다 초기화 되는 메모리DB가 좋을 것 같아요 :)

2021-04-29 16:09 UTC, dave915 commented on src/test/java/chess/service/GameServiceTest.java
> +        chessGame.move(Position.of("f6"), Position.of("e8"));
테스트 전 게임을 진행된 상태로 맞추기 위해 한 작업 같아요! 
`@Sql` 을 이용해서 데이터를 미리 넣어두는 방법도 한번 찾아보세요!

2021-04-29 16:10 UTC, merged