[체스 - 3단계, 추가미션] 인비(김태희) 미션 제출합니다.
woowacourse/jwp-chess pull request #271
Opened 2021-04-19 18:34 UTC by taehee-kim-dev

### 안녕하세요, 김고래!! 😄 

3단계와 추가미션까지 남은 모든 미션들을 구현했습니다.

혹시 까먹으셨을 수도 있으니, 실행 안내 사항 다시 남겨둘게요 😆 

## Spring Web Application 실행 안내 사항
- __사전에__ MySQL에서 `jwp-chess/chess_game.sql` 파일의 쿼리들을 맨 위에서부터 맨 아래까지 차례대로 실행해야 합니다. 이 과정을 먼저 마쳐야, `WebApplication.java` 를 실행할 수 있습니다. 테스트는 H2 DB가 적용되어있어 그냥 돌려도 되고, 콘솔 게임은  `ConsoleApplication.java` 을 실행하면 됩니다!!

`"말을 움직일 때 마다 각 플레이어의 비밀번호를 확인한다."` 이 요구사항을 처음 봤을 때, 보안을 생각해서 '세션으로 구현해야 하나?'라고 생각했지만, 이어지는 요구사항 `"클라이언트에서 비밀번호를 가지고 있다가 말을 옮길 때 마다 비밀번호를 함께 넘겨줌."` 도 만족시키려다보니, 쿠키를 사용하게 됐어요.

비밀번호 본문을 DB와 쿠키에 저장하는것은 보안상 매우 위험하기 때문에, 이를 Hash 암호화 해서 DB에 저장하고, 쿠키에 담아 발급하도록 했습니다.

이전 단계에서 merge 해주실 때 남겨주셨던 피드백들도 모두 반영했습니다!!
해당 내용과, 이번 미션 관련 학습 내용은 아래의 제 학습로그에 있어요. 😃 

[우아한테크코스 3기 백엔드 Lv2 [체스 - 3단계, 추가미션] 최초 PR 학습로그](https://velog.io/@taehee-kim-dev/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-3%EA%B8%B0-%EB%B0%B1%EC%97%94%EB%93%9C-Lv2-%EC%B2%B4%EC%8A%A4-3%EB%8B%A8%EA%B3%84-%EC%B6%94%EA%B0%80%EB%AF%B8%EC%85%98-%EC%B5%9C%EC%B4%88-PR-%ED%95%99%EC%8A%B5%EB%A1%9C%EA%B7%B8)

소중한 시간 내어 제 코드 리뷰해 주셔서 감사합니다. 🙇

2021-04-22 02:58 UTC, ep1stas1s requested changes
3단계도 빠르게 진행해주셨네요 👍 
항상 제출대비 늦어져서 죄송합니다ㅠ_ㅠ
이번에도 역시 잘 해주셔서 몇가지 코멘트만 남겼으니 참고해주세요~!

2021-04-22 09:40 UTC, taehee-kim-dev commented
### 안녕하세요, 김고래!! 🐳 

좋은 피드백들 정말 감사합니다. 🙇 
김고래의 피드백들 덕분에 제 코드가 많이 성장하고 깔끔해졌어요. 😆 👍 👍 

해 주신 피드백들 모두 반영했습니다!!

보안 관점에서 비밀번호 불일치에 대한 에러 문구는 추상적으로 하는게 좋다고 배웠습니다. 
그래서 비밀번호와 관련된 Cookie가 없을 때도, 비밀번호가 Cookie에 존재하지만 불일치한 경우와 같은 에러문구(`"비밀번호가 일치하지 않습니다."`)를 내려주도록 했습니다.

이전에는 게임 정보를 `model.addAttribute()`를 통해 전달해 html element의 `innerText`값으로 모두 세팅했습니다.
그리고 해당 html element들의 css 속성을 `display: none`으로 감췄어요.
그 후에 javascript에서 해당 html element들을 `document.getElementById()`로 읽어와 view의 로직들을 처리했습니다. 😅 

김고래가 주신 피드백대로 게임 정보들을 Cookie를 통해 전달하니, 이런 과정들을 모두 제거할 수 있었어요!! 😄 👍 👍 

그냥 javascript에서 바로 cookie값들을 읽어와 view 로직들을 처리하게 했습니다.

소중한 시간 내어 코드리뷰 해 주셔서 감사합니다!! 🙏 🙇

2021-04-24 14:24 UTC, ep1stas1s approved these changes
1,2,3 단계에 추가미션까지... 모두 빠르게 진행해주셨네요 💯 
추상적으로 남긴 코멘트들도 찰떡같이 반영해주셔서 감사합니다ㅎㅎ
스프링 미션 진행하시느라 고생하셨습니다~

2021-04-24 14:24 UTC, ep1stas1s commented on src/main/java/chess/web/service/ChessGameService.java
> +            .orElseThrow(GameNotExistsException::new);
요런건 반복이 많으니 서비스 내에 메서드로 빼도 좋겠네요ㅎㅎ

2021-04-24 14:24 UTC, ep1stas1s commented on src/main/java/chess/repository/dao/ChessGameDao.java
> +    public Optional<ChessGame> findById(Long gameId) {
잘 적용해주셨네요 👍

2021-04-24 14:24 UTC, ep1stas1s commented on src/main/java/chess/web/controller/ChessGameController.java
> +    private List<Cookie> getCookiesAboutGame(GameStatusResponseDto gameStatusResponseDto) {
사실... 이정도로 많은 정보를 담는것까지 생각한건 아닌데요ㅎㅎㅎ
리프레쉬가 필요한 정보들은 dto로 내려주고, 그러지 않는 정보들만 가지고 있는게 좋을 것 같아요 :)
예를 들면 gameId, password정도가 있겠네요

2021-04-24 14:24 UTC, ep1stas1s commented on src/main/java/chess/web/controller/ChessGameController.java
> +        return new ArrayList<>(Arrays.asList(
Arrays.asList로만 감싸줘도 될것같습니다

2021-04-24 14:24 UTC, merged

2021-04-24 14:34 UTC, taehee-kim-dev commented
김고래의 소중한 피드백들 덕분에 정말 많이 성장할 수 있었습니다.
감사합니다!!! :smile: :bow:

2021-05-17 04:36 UTC, taehee-kim-dev commented
[우아한테크코스 3기 백엔드 Lv2 [체스 - 3단계, 추가미션] 학습로그](https://velog.io/@taehee-kim-dev/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-3%EA%B8%B0-%EB%B0%B1%EC%97%94%EB%93%9C-Lv2-%EC%B2%B4%EC%8A%A4-3%EB%8B%A8%EA%B3%84-%EC%B6%94%EA%B0%80%EB%AF%B8%EC%85%98-%EC%B5%9C%EC%B4%88-PR-%ED%95%99%EC%8A%B5%EB%A1%9C%EA%B7%B8)