[Spring 체스 - 3단계] 아론(장세환) 미션 제출합니다.
woowacourse/jwp-chess pull request #280
Opened 2021-04-22 07:49 UTC by Sehwan-Jang

안녕하세요 지노!
3단계 미션의 요구사항은 여러개의 체스 방을 만들고, 각 방의 방 제목도 설정할 수 있도록 하는 것인데요,
1, 2단계의 db는 `room_id`와 `command`만 저장되는 형태였기 때문에 방을 생성할 수도, 제목을 설정할 수도 없었습니다. 
따라서 3단계를 진행하면서 db에 방 id와 제목을 저장하는 `chessroom` 이라는 새로운 테이블을 만들어 기능을 구현했습니다.

추가적으로, 1-2 단계 미션때 지노가 코멘트 남겨주신 REST API 와 그에 맞는 메소드 매핑을 리팩토링 해봤습니다. (글 링크 정말 감사드려요 😊)
그런데 게임종료 시 보드를 초기화 하던 `clear()` 메소드를 get매핑에서 delete 매핑으로 수정하니,
```
function clearRoom() {
    clearBoard();
    window.location.href = "/clear/" + $roomId;
}
```
이렇게 간단했던 js 코드가 
```
function clearRoom() {
    clearBoard();
    fetch("/clear/" + $roomId, {
        method: 'delete'
    }).then(res => {
        return res.url
    }).then(url => {
        window.location.href = url;
    });
}
```
와 같이 비대해지더라구요. 

이에 대해 제가 fetch 메소드를 비효율적으로 사용하고 있는 것인지,  
이정도 불편함은 REST 를 위하여 감수해야 하는 것인지,  
아니면 위의 코드처럼 간단한 경우는 현업에서 get매핑으로 사용하는 경우도 있는지 등등 여러 궁금증들이 생겨 지노에게 여쭤보고 싶었어요. 

마지막까지 제 코드 봐주셔서 정말 감사합니다!

2021-04-24 18:04 UTC, hyunssooo requested changes
안녕하세요 아론! 지노입니다.
몇 가지 코멘트 남겼어요! 
확인 부탁드려요! 
늦어서 죄송합니다. 🙇‍♂️😭

2021-04-26 07:53 UTC, Sehwan-Jang commented on src/main/resources/application-test.properties
> +spring.datasource.password=root
chess_test 라는 db를 workbench에서 생성하여 사용했습니다.

2021-04-26 07:54 UTC, Sehwan-Jang commented on src/main/resources/schema.sql
> +
인텔리제이의 자동정렬 기능을 사용하면 저렇게 되네요 ㅠㅠ
지적 감사합니다 😊

2021-04-26 08:10 UTC, Sehwan-Jang commented on src/main/java/chess/controller/SpringChessRestController.java
>  public class SpringChessRestController {
rest api 디자인 가이드를 한번 쭉 읽고 이전에 제가 사용하던 url 경로들은 리소스들 간의 관계를 모호하게 표현하고 있었다는 생각이 들었습니다. 예를 들어 10번 방의 체스보드를 가져온다면 `10번 방`이라는  명확한 정보를 url에서는 표현하고 있지 않았다고 생각했습니다.

따라서 이번 리팩토링 단계에서 최대한 url 안에 명확한 의미와 리소스들간의 관계에 대한 정보를 담으려 노력했습니다.
* `/game/id `-> GET `/room/id`
* `/game/clear/id` -> DELETE `/room/id/commands` : db에 command 들을 저장하는 구조이므로.
* `/game/board/id` -> GET `/room/id/current-board`
* `/game/move` -> POST `/room/id/command`
* `/game/movable` -> GET `/room/id/path`
* `/game/score` -> GET `/room/id/status` : 점수 뿐만 아니라 턴 정보도 함께 관리하기 때문에.

이렇게 바꾼다면 조금더 restful 해졌다고 볼수 있을까요...? 😥

2021-04-27 07:00 UTC, Sehwan-Jang commented on src/main/java/chess/controller/SpringChessRestController.java
>          try {
디버깅 하던게 남아있었네요..
삭제했습니다!

2021-04-28 15:14 UTC, hyunssooo approved these changes
안녕하세요 아론 
레벨1, 2 체스 미션 저와 함께 하신다고 정말 수고 많으셨습니다! 👍
빠르게 반영해주셨는데 제가 확인이 늦었네요. 😭
남은 미션들도 잘 진행해주세요! 👍

2021-04-28 15:14 UTC, hyunssooo commented on src/main/java/chess/service/SpringChessService.java
>      }
앞으로 자주 사용할 `@Transactional` 도 찾아보면 좋을 것 같습니다 🙂

2021-04-28 15:17 UTC, hyunssooo commented on src/main/java/chess/controller/SpringChessRestController.java
>  public class SpringChessRestController {
고민을 많이 하신거 같아요 💯
완벽히 rest의 제약사항들을 다 지키기는 어렵다고 생각해요 :) 
상황에 맞게 유연하게 대처하는 것도 저는 중요하다고 생각해요.

저는 https://www.youtube.com/watch?v=RP_f5dMoHFc 이 영상 보고 많이 생각했던 거 같습니다.
쉬운 내용은 아니지만 시간 나실 때 참고해보시면 좋을 것 같아요. 저는 우테코 과정이 끝나고 본 거 같습니다. ㅎㅎ

2021-04-28 15:18 UTC, merged