[Spring 체스 - 3단계] 멍토(김유기) 미션 제출합니다.
woowacourse/jwp-chess pull request #307
Opened 2021-04-26 14:45 UTC by daum7766

안녕하세요. 재연링!

체스 1, 2단계 때 방을 나누는 기능까지 같이 해버려서 어떤 걸 해야 하나 고민했어요.
그래서 이번 미션에서는 Spring 테스트코드를 추가했어요
DB는 H2를 이용하여 작성해서 따로 Mysql을 사용하지 않으셔도 동작하게 하였어요

그리고 저번에 이야기해주신 에러 상황에 따른 ENUM을 작성해 보았어요.
상황에 따라서 출력되는 에러메시지에 따라 어디서 문제가 생겼는지 특정할 수 있어서
문제 해결을 할 때 좋을 것 같다는 생각이 들었습니다.

부족한 부분 많은 지적 부탁합니다.
감사합니다.

2021-04-27 13:25 UTC, jaeyeonling requested changes
3단계 요구사항도 잘 반영해주셨어요 👍 
피드백 남겨두었으니 확인 후 반영해주세요!

2021-04-27 16:18 UTC, daum7766 commented on src/main/java/chess/advice/ChessAdvice.java
>  public class ChessAdvice {
조금 더 공부해보겠습니다!

2021-04-28 06:32 UTC, daum7766 commented on src/main/java/chess/advice/ChessAdvice.java
> +        ExceptionState exceptionState = ExceptionState.NULL_POINTER;
현재 작성한 프로그램에서 제가 확인한 NULL_POINTER 에러는 game 테이블에서 끝났는지 여부를 가져올 때 없는 게임을 참조하면 생기는 에러입니다.
사전에 Room에서 걸러내기 때문에 발생하기 힘든 에러입니다. (테이블이 깨졌을때나 발생이 가능할 것으로 예상)
따라서 500 에러와 위한 비어있는 데이터를 참조했다는 문구로 수정했습니다.

2021-04-28 06:36 UTC, daum7766 commented on src/main/java/chess/advice/ExceptionState.java
> +    EXCEPTION(400, "기타 에러입니다.");
저는 위와 같은 에러는 사용자들이 잘못된 요청을 보냈을때 생기는 에러라고 생각하여 400으로 정의했었습니다.
그렇지만 리뷰를 보고 좀더 세분화를 해야겠다 라는 생각이 들어서 나눠보았습니다.

게임진행을 제대로 못할 입력이 들어올때(ex: 상대턴일때 이동하기, 잘못된 위치로 이동하기) -> 400에러
로그인 실패 -> 401에러
없는 데이터베이스 데이터를 참조할때(ex: 없는 101번방을 들어가려 할떄) -> 404에러
NullPointer -> 서버의 문제라고 생각하여 500
제가 생각하지 못했던 에러 -> 500

2021-04-28 06:37 UTC, daum7766 commented on src/main/java/chess/advice/ChessAdvice.java
> +    public ResponseEntity illegalArgumentExceptionHandler() {
리뷰를 보고 ChessGame 도메인에 적용하면 된다고 이해를 했습니다.
현재 chessGame 도메인에서 발생하는 에러는 IllegalArgumentException 하나였는데 위와 같이 적용하기 비밀번호 인증실패와 같은 내용을 나눠서 만들 수 있었습니다.

2021-04-28 07:10 UTC, daum7766 commented
재연링 안녕하세요
리뷰를 받고 있는 멍토입니다.

아래와 같은 내용에 대한 저의 생각입니다.
Service Layer에 비즈니스 로직이 포함되어 있다고 한 내용입니다.
저는 Service Layer는 Java로만 했을 때 Controller의 역할을 하고 있다고 생각합니다.
모델을 호출하는 순서를 보장하는 성격이 강하다고 생각하고 있습니다.
순서를 보장하는 또한 비즈니스 로직인가? 라고 생각할 수 있지만
저는 그것 또한 비즈니스 로직이 아닌가? 라고 생각하여 그렇게 적었습니다.
따라서 Service Layer에 도메인은 포함보다는 의존하고 있다고 생각합니다.
그렇다면 도메인은 어디에 있을까? 라고 생각을 해봤습니다.
도메인을 사용하는 부분은 Service Layer와 Persistence Layer에서 도메인을 사용하고 있습니다.
따라서 도메인은 Service Layer와 PersistenceLayer와 겹쳐있다고 생각합니다.
제가 틀린 부분이나 의견이 다른 부분에 대해서 많이 많이 알려주세요! 감사합니다.

2021-04-29 03:46 UTC, jaeyeonling requested changes
피드백을 잘 반영해주셨어요 👍 
질문에 대한 답변 남겨두었는데 확인 부탁드립니다!

2021-04-29 04:58 UTC, daum7766 commented on src/main/java/chess/advice/ChessAdvice.java
> +    @ExceptionHandler(NullPointerException.class)
그렇네요!
DB말고도 다른곳에서 생길 수 있으니 구분하기 위해 분리를 하면 좋을것 같네요.
ChessException에서 TABLE이라는 내용을 추가해서 만들었습니다.

2021-04-29 05:00 UTC, daum7766 commented on src/main/java/chess/advice/ChessAdvice.java
>  public class ChessAdvice {
저는 DDD에 대해서는 아직 공부를 하지않아서 정확한 내용은 아직 모르고있습니다.
그렇지만 실제업무를 수행하는 내용은 도메인에서 수행해야 한다는 내용은 공감합니다.
레이어에 대해서는 많이 부족한것 같습니다.
더 많이 공부해보겠습니다.

2021-04-29 05:09 UTC, daum7766 commented
안녕하세요 재연링!
좋은내용 많이 알려주셔서 정말 감사합니다!

저는 DDD에 대해서는 아직 공부를 하지않아서 정확한 내용은 아직 모르고있습니다.
그렇지만 실제업무를 수행하는 내용은 도메인에서 수행해야 한다는 내용은 공감합니다.

Service에서 비즈니스로직을 수행한다면 Service가 강하게 종속되어 프레임워크를 바꾸거나(그런일은 드물지만)
도메인만 따로 옮겨서 사용할때 수정사항이 많이생길수 있다고 추측이 됩니다.(결합이 강하게 되었기때문에)
그래서 저 역시 업무를 수행하는 비즈니스 로직은 도메인에서 수행하는것이 좋다고 생각합니다.

레이어에 대해서입니다.
제가 봤던 레이어는 3개의 레이어층으로 되어있는 레이어였습니다.
찾아보는 레이어마다 모두 다른 내용이어서 어떤걸 잡고 공부를 해야할지 감을 못잡고 있었습니다.
재연링의 이야기를 들어보니 레이어에 대해서는 많이 부족한것 같습니다.
더 많이 공부해보겠습니다.

감사합니다.

2021-04-29 08:10 UTC, jaeyeonling commented
Q1. 저는 DDD에 대해서는 아직 공부를 하지않아서 정확한 내용은 아직 모르고있습니다.
A1. 아직 DDD를 따로 학습할 필요는 없고 이러한 개념이 있구나! 하고 넘어가셔도 됩니다 ㅎㅎ
지금은 DDD 자체를 공부하는 것 보다 왜 저렇게 설계했을까? 라는 고민이 더욱 도움이 되실 것 같아요

Q2. 레이어에 대해서입니다.
제가 봤던 레이어는 3개의 레이어층으로 되어있는 레이어였습니다.
찾아보는 레이어마다 모두 다른 내용이어서 어떤걸 잡고 공부를 해야할지 감을 못잡고 있었습니다.
A2. 어떠한 레이어로 공부했는지 모르겠다라고 한 이유는 레이어를 알아야 한다! 라는 의미 보다는 어떠한 레이어를 공부했는지 알아야 해당 레이어가 어떠한 이유로 그러한 설계를 했는지 알 수 있어 여쭤봤습니다 ㅎㅎ

Q3. 재연링의 이야기를 들어보니 레이어에 대해서는 많이 부족한것 같습니다.
더 많이 공부해보겠습니다.
혹시 레이어에 대한 추천해줄만한 자료가 있다면 추천 부탁드립니다!
A3. 사실 레이어에 대해 공부하는 것 보다 중요한 것은 도메인을 어떻게 보호할까? 라는 관점을 유지하는게 중요할 것 같습니다 
관례적으로 사용하는 Controller - Service - Repository 구조 자체가 좋은 구조기 때문에 해당 레이어에서 비즈니스 로직에 대한 부분만 도메인으로 옮겨주면 될 것 같아요 ㅎㅎ

즉, 
어떠한 레이어가 있을까? 라는 접근으로 레이어들을 공부하기 보다는 
레이어들을 왜 구성할까? -> 도메인을 보호하기 위해서
도메인을 보호하기 위한 방법은 무엇일까? -> 가장 중요한 도메인을 중심으로 두고 감싸 보호한다
레이어들이 많이 있는데 레이어들이 다른 이유는 무엇일까? -> 도메인을 보호하는 방법에 대한 관점이 다르다

핵심은 도메인을 감싼다는 것이고, 모든 레이어들이 도메인을 감싼다는 것은 동일하니 해당 부분이 핵심이다!
핵심을 알았으니 넘어간다! 

교육을 받다보면 공부해야 할 부분이 많을텐데 위와 같은 접근으로 핵심을 공부하면 장기적인 관점으로 봤을 때 도움이 될 것 같습니다 :)

2021-05-02 11:43 UTC, daum7766 commented
## 1. 답변을 듣고 한 생각

레이어들을 왜 구성할까?

우리의 과제는 원하는 기능을 동작하는 것이다. 원하는 기능을 동작하게 하기위해 비즈니스 로직을 만들고 도메인 모델을 만든다. 그렇다면 가장 중요한 부분은 도메인 모델이라고 볼 수 있다.

그런데  도메인들만 있다면 외부에서 사용할때 외부에서 필요한 출력값이나 입력이 변경된다면 도메인이 바뀐다는 문제가 생긴다.

따라서 도메인의 변경을 최소화 하기위해 도메인과 외부의 연결을 분리하기 시작했다.

그래서 레이어들을 구성하여 도메인을 보호한다고 생각된다.



이와 비슷하게 OSI 7계층으로 생각해보면 관심사를 분리함으로써 책임부분을 나누어 특정부분(layer)만 바꿀때 다른곳에 영향을 미치지 않고 낮은 비용으로 유지보수를 할 수 있게 도와준다.

이것을 생각해볼때 Spring에서 레이어를 나누는 이유를 아래와 같이 유추해볼 수 있다

하나로 묶여있다면 입출력 부분이 바뀔때, 전체적인 수정이 일어나며 그것에 대한 사이트 이팩트까지 고려를 해야한다.

layer를 나누게 되면 수정이 일어날때 해당 layer만 수정함으로써 다른 부분에 대한 사이드 이펙트를 줄이고 유지보수를 용이하게 해준다.



인터넷에서 layer를 공부하기 위해 찾아보면 사람들 마다 올라와있는 layer들이 다르다.

이것은 도메인을 보호하기 위해 바라보는 관점이 달라서 생겼다.(라고 들었다)



결국 핵심은 도메인을 감싼다는 것이다!!



그래서 지금은 layer의 역할에 대해서 생각해 보기 보다는 도메인을 보호하기 위해서 layer가 존재한다 정도까지만 이해하고 넘어가기로 했다.



## 2. 답변을 듣고 생긴 궁금증

Repository는 어디에 있어야 하는지 아직도 모르겠다. - 추가공부가 필요함.

-> 에 대한 답을 먼저 말씀드리면, Repository에 대한 인터페이스는 Domain Layer에 해당하고 구현체는 Persistence Layer(Infrastructure Layer)에 해당합니다!



이거와 관련되어 우테코에서 많은 이야기들이 있었습니다

결국 포비와 제이슨 등의 많은 코치들이 아직 거기에 대해서 생각하지 않아도 된다고 했지만

이미 생겨버린 궁금증은 어쩔 수 없었던것 같습니다

 

### 2-1. Repository는  어떤 역할을 하는 것일까요?

우테코에서도 보면 사람마다 사용한 방식이 달랐습니다.

1. 특정 객체들을 관리하기 위해서 사용한 사람들이 있고

2. dao가 나눠져 있어 repository를 만들어 dao를 묶어 처리한 사람도 있었습니다.

JPA를 사용한다면 1번이 맞을것 같지만(우테코에서 이야기를 하며 나온것) 저희의 경우는 dao를 쓰고있으므로 애매해졌다고 생각합니다.

 

### 2. 인터페이스와 구현체의 위치

Repository에 대한 인터페이스는 Domain Layer에 해당한다

-> Repository 인터페이스를 통해 Domain 객체를 가져오기 때문에 Domain Layer라고 바라보는 걸까요?

구현체는 Persistence Layer(Infrastructure Layer)에 해당합니다

-> Repository가 객체를 만들기 위해 데이터가 필요한데 데이터는 데이터베이스에서 가져와야 하므로 구현체는 Persistence Layer에 있다고 하는걸까요?



감사합니다.

2021-05-05 11:14 UTC, daum7766 commented
DM으로 받은 답변 남겨둡니다.
Repository가 Domain layer에 해당하고 구현체가 Persistence Layer에 해당하는 이유를 먼저 설명드린다면 Repository는 단순 `집합처리`를 위한 인터페이스를 제공합니다
즉, Repository 자체로 봤을 때 DB와 관련된 내용이 하나도 없는 것을 볼 수 있는데요
이러한 Repository 인터페이스의 `집합처리`를 제공하며 저장되는 공간이 DB라면 해당 구현체가 Persistence Layer에 위치하게 된다고 볼 수 있습니다.
위 내용으로 본다면 Repository는 `집합처리`를 한다. 라는 것을 알 수 있을 것 같아요
이번 미션에서는 Repository의 개념적인 내용의 중요도 보다는 어떠한 방식으로 설계하고 구현했느냐가 중점이였기 때문에 사람마다 구현이 많이 달랐을 수 있을거라 생각해요
위에 말한 `집합처리`를 만족하는 과정에서 DAO를 묶어 Repository를 구성하는 것은 문제가 되지 않습니다 ㅎㅎ
Repository는 개념적인 내용이 강하기 때문에 용어에 대한 중요도도 높지 않고 관련해서 나오는 더 어려운 개념들이 많기 때문에 더 이상 공부하는 것은 비효율적일 수 있을 것 같아요
포비와 제이슨이 거기에 대해 생각하지 않아도 된다고 한 이유는 지금 단계에서 해당 정보를 습득하는 것이 오히려 생각에 방해가 될 수 있다고 판단했을거라 예상이 되네요!
지금의 단계에서는 Repository는 위 개념 정도만 익혀두고 넘어가셔도 될 것 같습니다 ㅎㅎ

2021-05-05 11:15 UTC, daum7766 commented
안녕하세요 재연링!
저번에 수정하라는 부분을 수정했습니다.
혹시 변경해야 할 것들이 더 있을까요?

2021-05-05 11:43 UTC, jaeyeonling approved these changes
수 많은 피드백 반영하시느라 고생 많으셨습니다 💯 
해당 요청은 머지하도록 할게요~
다음 미션 화이팅입니다!!

2021-05-05 11:43 UTC, merged