[Spring 체스 - 3단계, 추가미션] 현구막(최현구) 미션 제출합니다.
woowacourse/jwp-chess pull request #312
Opened 2021-04-26 16:47 UTC by Hyeon9mak

안녕하세요 게이츠! 체스 3단계와 추가미션을 진행했습니다!

3단계의 경우 이미 기존에 체스방이 구현되어 있었기 때문에 거의 생략되었고, 추가 미션에 집중했어요.
스프링도 익숙치않고, 스프링 쿠키는 더더욱 익숙치 않아서 사용법을 익혀본다는 느낌으로 단순 구현만 진행했습니다!

> ### 체스방 게임하기
> - 말을 움직일 때 마다 각 플레이어의 비밀번호를 확인한다.
> - 비밀번호 확인 시 매번 입력받는 방식이 아님
> - **클라이언트에서 비밀번호를 가지고 있다가 말을 옮길 때 마다 비밀번호를 함께 넘겨줌**
> - 인증 방법에 대한 추가학습을 하기 보다는 인증에 대한 필요성을 느낄 수 있으면 좋음
> - 플레이어1과 플레이어2의 차례에 맞게 말을 옮기고 자기 차례가 아닐 경우 에러를 응답한다.

`클라이언트에서 비밀번호를 가지고 있다`에 집중해서 서버에서 모든 move명령에 대해 인증을 요구하고,
브라우저에 저장한 쿠키를 통해 인증을 진행하는 방식을 채택했어요!
아래는 동작 예시입니다!

---

### 1. `방 만들기` 버튼으로 방제목/백색유저아이디/백색유저비밀번호 3가지 정보를 전달하게 되고,
![image](https://user-images.githubusercontent.com/37354145/116119447-6b2b4f00-a6f9-11eb-900f-80af70aca2ec.png)

### 2. 흑색 유저 칸에 생성되는 `입장` 버튼으로 흑색유저아이디/흑색유저비밀번호 2가지 정보를 전달하면서 방에 입장하게 됩니다.
![image](https://user-images.githubusercontent.com/37354145/116119531-81390f80-a6f9-11eb-8176-a9f5699f2de4.png)
![image](https://user-images.githubusercontent.com/37354145/116119799-c8bf9b80-a6f9-11eb-9def-8fe2b4d3e8b8.png)

### 3. `새로운 게임` 또는 `이어하기` 버튼을 클릭해서 게임을 진행하게 됩니다.
![image](https://user-images.githubusercontent.com/37354145/116119885-decd5c00-a6f9-11eb-8c78-488448cb8d48.png)

### 4. 쿠키를 이용해서 턴이 일치하지 않은 브라우저에선 체스말의 이동을 막습니다.
![image](https://user-images.githubusercontent.com/37354145/116120011-0c1a0a00-a6fa-11eb-8589-1c0eff42643c.png)

---

<br>

동작원리 등을 고민하기보다 사용법을 익히는 수준이었어서, 이번 PR에는 질문이 없습니다.. 😅 
대신 따끔한 피드백 부탁드리겠습니다! 감사합니다!

2021-05-01 07:47 UTC, serverwizard requested changes
큰 구조 변경 없이 3단계 미션 잘 수행해주셨어요 💯 

한 번 더 생각해봤음 하는 부분이 있어 몇가지 코멘트 남겼으니 이 부분만 확인 부탁드릴게요.

감사합니다. 🙇

2021-05-01 07:47 UTC, serverwizard commented on src/main/java/chess/controller/SpringChessGameController.java
> +        Cookie cookie = new Cookie("password", requestDTO.getPassword());
쿠키의 단점 중 하나는 보안에 취약하다는 점이라고 생각하는데요. (유출 및 조작 될 수 있음)
이런 곳에 password를 담아 둬도 괜찮을까요?

플러스 알파로 웹브라우저를 끄면 사라지는 쿠키를 Session cookie라 하고, 웹브라우저를 꺼도 사라지지 않는 쿠키를 Permanent 쿠키라고 하는데요. 각각 언제 사용되는지에 대해서도 학습해보시면 좋을 것 같아요.

2021-05-01 07:47 UTC, serverwizard commented on src/main/java/chess/controller/SpringChessGameController.java
> +    public String enterWhite(@ModelAttribute final EnterRoomRequestDTO requestDTO,
현재 enterBlack메소드와 enterWhite 메소드가 거의 똑같은 작업을 처리하고 있는 것 같은데요
이럴 경우 새로운 메소드를 만들어 처리하기 보단 EnterRoomRequestDTO에 black/white를 구분할 수 있는 필드를 추가해서 이를 통해 처리하는 건 어떨까요?

2021-05-03 02:09 UTC, Hyeon9mak commented on src/main/java/chess/controller/SpringChessGameController.java
> +    public String enterWhite(@ModelAttribute final EnterRoomRequestDTO requestDTO,
방에 입장하는 유저가 흑색/백색으로 갈라지면서 분명한 구분이 필요한데, 마땅한 방법을 떠올리지 못해 `/enter-white`, `/enter-black` 으로 구현했었어요. '이정도 중복은 괜찮겠지...' 라고 합리화해버린 저의 분명한 잘못입니다 😭 

말씀해주신대로 `EnterRoomRequestDTO`에 `color` 필드를 추가하고, main.hbs 파일 쪽에 `<input type='hidden' ...>` 으로 color를 주입해주니 간단하게 해결 할 수 있었습니다!

컨트롤러 쪽에서는 말끔하게 해결되었지만 서비스와 DAO쪽에 다시 고민이 생겼는데요, 결국 전달받은 color 를 구별해야하는데
이걸 서비스 단에서 하는게 나은지, DAO에서 하는게 나은지 고민입니다.
DAO는 최대한 원시적으로 DB CRUD 동작만 진행하고, 사용자나 개발자가 원하는 추상적인 명령은 서비스가 소화해야한다고 생각해서 
현재는 서비스 단에서 color를 구별하고, 'black'일 경우 `DAO.enrollBlackUser`, 'white'일 경우 `DAO.enrollWhiteUser` 메서드를 수행하도록 했습니다. 올바른 접근이었을까요?

2021-05-03 02:25 UTC, Hyeon9mak commented on src/main/java/chess/controller/SpringChessGameController.java
> +        Cookie cookie = new Cookie("password", requestDTO.getPassword());
Session 쿠키는 브라우저가 종료되면 사라지는 쿠키, Permanent 쿠키는 브라우저가 종료되어도 유지되는 쿠키

공식 문서에 따르면 사용 방법 자체는 Set-Cookie로 동일하고, 추가로 옵션을 어떻게 주느냐에 따라 달라지는거 같아요.
Permanent 쿠키로 만드려면 `Expires` 또는 `Max-Age` 옵션을 추가해주어야하는데, `Expires`는 쿠키가 언제 만료될 것인지(만료 시점)을 지정하고, `Max-Age` 는 얼마동안 쿠키를 살려둘 것인가(현재 시점 기준 얼마나)로 지정하는 차이가 있네요!

Session 쿠키는 흔히 로그인 유지를 위해 사용되는걸 자주 봤던거 같고, Permanent 쿠키는 "(팝업)오늘 하루 동안 보지 않기" 등에서 자주 봤던거 같습니다!

https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Set-Cookie
https://opentutorials.org/course/3387/21743

2021-05-03 02:31 UTC, Hyeon9mak commented on src/main/java/chess/controller/SpringChessGameController.java
> +        Cookie cookie = new Cookie("password", requestDTO.getPassword());
> 쿠키의 단점 중 하나는 보안에 취약하다는 점이라고 생각하는데요. (유출 및 조작 될 수 있음)
이런 곳에 password를 담아 둬도 괜찮을까요?

말씀해주신 의도는 아무래도 쿠키보다 세션을 적용해보라는 말씀이신거같아요!
`클라이언트에서 비밀번호를 가지고 있다` 는 요구사항에 집중해서 세션이 아닌 쿠키를 사용했습니다.
세션을 적용하는 순간 클라이언트가 아닌 서버가 비밀번호를 가지고 있게 된다고 생각하고 있어요! (혹시 제가 잘못 이해하고 있는걸까요?)

쿠키에 비밀번호를 저장한다는 요구사항도 지키면서 보안도 챙길 수 있는 방법이 있을까 고민하던 차에, 쿠키에 저장되는 비밀번호 자체를 암호화하면 어떨까 생각하게 되었어요! 괜찮은 방법일까요?

2021-05-03 04:36 UTC, Hyeon9mak commented
오랜만에 PR드립니다 게이츠! 
피드백 주신 부분들에 대해 적용하고 RestController의 `ResponseEntity` 반환을 적용해보았어요!
그 과정에서 몇 가지 궁금증이 생겼습니다!

<br>

## 1. 쿠키 암호화
`클라이언트에서 비밀번호를 가지고 있다` 라는 요구사항을 충족하기 위해서 세션이 아닌 쿠키를 사용했어요.
요구사항을 충족함과 동시에 쿠키 보안을 지키기 위해선 쿠키를 암호화하는게 옳다고 생각했고,
복호화가 불가능한 **RSA-256**을 이용한 암호화를 진행했어요!
사용자로부터 비밀번호를 전달 받으면 암호화부터 진행하고, 암호화된 비밀번호를 DB와 쿠키로 넘겨주는 방식입니다.

궁금한 부분은 "과연 이걸로 안전한가?" 입니다.
암호화를 통해 비밀번호 그 자체는 안전해졌지만 암호화된 비밀번호 자체가 클라이언트 쪽에 노출되어 있는 상태고,
서버 쪽에서 암호화된 비밀번호를 직접 전달 받진 않지만 쿠키 저장소를 조작하면 암호화된 비밀번호를 통해 충분히 인가 받을 수 있는 
(노출되어 있는) 상태라고 생각돼요...

쿠키로 지킬 수 있는 보안의 한계일까요? 아니면 제가 모르는 다른 방법이 더 있을까요?!

<br>

## 2. DTO로 전달된 필드 판별
말씀해주셨던 `/enter-black`, `/enter-white` 중복 메서드 문제를 DTO에 필드를 추가함으로서 해결할 수 있었어요!

그렇지만 서비스와 DAO쪽에 다시 고민이 생겼는데요, 결국 전달받은 color 필드를 구별해야하는데
이걸 서비스 단에서 하는게 나은지, DAO에서 하는게 나은지 잘 모르겠어요.

DAO는 최대한 원시적으로 DB CRUD 동작만 진행하고, 사용자나 개발자가 원하는 추상적인 명령은 서비스가 소화해야한다고 생각해서
현재는 서비스 단에서 color를 구별하고, 'black'일 경우 DAO.enrollBlackUser, 'white'일 경우 DAO.enrollWhiteUser 메서드를 수행하도록 했습니다. 올바른 접근이었을까요?

<br>

## 3. ResponseEntity 와 new ResponseEntity의 차이
RestController 메서드들의 반환 값에 상태 코드를 함께 부여하고 싶어 ResponseEntity 를 사용하게 됐습니다!
그런데 static하게 사용하는 방법과, new 키워드를 이용하는 방법이 있더라구요.

```java
    @PostMapping("/movable-positions")
    public ResponseEntity<List<String>> findMovablePosition(@RequestBody final SectionDTO sectionDTO) {
        ChessGame chessGame = roomService.loadGameByRoomId(sectionDTO.getRoomId());
        List<String> positions = chessGame.movablePositionsByStartPoint(sectionDTO.getClickedSection());
        return ResponseEntity.status(HttpStatus.OK).body(positions);
    }
```
```java
    @PostMapping("/movable-positions")
    public ResponseEntity findMovablePosition(@RequestBody final SectionDTO sectionDTO) {
        ChessGame chessGame = roomService.loadGameByRoomId(sectionDTO.getRoomId());
        List<String> positions = chessGame.movablePositionsByStartPoint(sectionDTO.getClickedSection());
        return new ResponseEntity<>(positions, HttpStatus.OK);
    }
```

static 하게 이용하는 방법이 조금 더 명시적인거 같아서 (`.status().body`) 적용했는데, 
정확히 어떤 차이가 있고, 언제 사용하는 것인지 알고 싶습니다!

<br>

감사합니다!

2021-05-06 00:00 UTC, serverwizard commented on src/main/java/chess/controller/SpringChessGameController.java
> +    public String enterWhite(@ModelAttribute final EnterRoomRequestDTO requestDTO,
제가 드리는 코멘트는 이 방법이 틀렸어라기 보단, 이런 케이스도 있지 않을까요?라는 생각의 기회를 드리기 위함이었어요.
현구막이 구현한 방법으로 구현은 충분히 가능합니다. :) 

그리고 User 테이블에다가 색깔을 구분할 수 있는 컬럼을 추가하고, 이런 경우라면 Room테이블에서는 User테이블에 대한 FK를 하나만 가지게 하는 건 안됐을까요?

2021-05-06 00:09 UTC, serverwizard commented on src/main/java/chess/controller/SpringChessGameController.java
> +        Cookie cookie = new Cookie("password", requestDTO.getPassword());
```
클라이언트에서 비밀번호를 가지고 있다 는 요구사항에 집중해서 세션이 아닌 쿠키를 사용했습니다.
세션을 적용하는 순간 클라이언트가 아닌 서버가 비밀번호를 가지고 있게 된다고 생각하고 있어요! (혹시 제가 잘못 이해하고 있는걸까요?)
```
현구막이 이해한 게 맞아요!
다만, 현구막이 이런 고민도 충분히 할 수 있다는 생각이 들어서 코멘트를 드렸어요.

```
쿠키에 비밀번호를 저장한다는 요구사항도 지키면서 보안도 챙길 수 있는 방법이 있을까 고민하던 차에, 쿠키에 저장되는 비밀번호 자체를 암호화하면 어떨까 생각하게 되었어요! 괜찮은 방법일까요?
```
쿠키에 비밀번호를 저장한다는 요구사항을 지키면서 보안도 챙길 수 있는 방법이 무엇일까 고민한 것도 좋았고,
이러한 방법으로 암호화를 생각한 부분도 너무 좋은 것 같네요.

2021-05-06 00:13 UTC, serverwizard approved these changes
안녕하세요, 현구막!

피드백을 잘 반영해 주셨네요 👍 

코멘트 질문에 대한 답변은 남겨뒀으니 확인 부탁드릴게요.

체스 미션은 여기서 마무리하도록 할게요. 
정말 고생 많으셨고, 다음에 또 만나요~ 👋

2021-05-06 00:13 UTC, merged