[Spring 체스 - 3단계, 추가미션] 웨지(성시형) 미션 제출합니다.
woowacourse/jwp-chess pull request #316
Opened 2021-04-26 19:01 UTC by sihyung92

안녕하세요!!!!!!!!!!!! 일찍 리뷰 주셨는데 많이 늦었습니다!!

방을 생성한 유저는 흰색, 비밀번호를 입력하여 입장한 유저는 검은색 진영을 맡게 됩니다.
입장할 때 비밀번호가 일치하면 같은 유저라고 판단합니다.

구현에 급급하여 테스트 작성이 잘 안 되었는데, 내일 크루들과 RestAssured 학습을 해보기로 했습니다!
틈틈히 테스트를 보강하여 push하도록 하겠습니다.

새벽이라 머리가 안 돌아가네용.. 아침 해가 밝아오면 쌩쌩한 상태로 코멘트 수정하겠습니다아

2021-04-28 12:46 UTC, JunHoPark93 requested changes
안녕하세요 웨지!
미션 잘 구현해주셨어요 🙇‍♂️
몇가지 코멘트 남겨두었어요~ 
고민해야될 부분들이 있을수있는데, 궁금한점이 있으시면 편하게 남겨주세요!

2021-04-28 12:46 UTC, JunHoPark93 commented on src/main/java/chess/mysql/dao/RoomDao.java
> +import chess.mysql.dao.dto.RoomDto;
dto라고 정의해주신부분이 보면 데이터계층에서만 쓰이는것으로 보여요. 하지만 dto의 클래스는 public 클래스입니다. 자칫하면 다른 레이어에서도 접근가능할텐데요. 전 레이어에 걸쳐서 쓰는게 아니라면 접근제한자를 좁혀서 이 레이어에서만 쓰는게 좋지 않을까요?

default 접근제한자를 사용하면 어떨까요? 아마 mysql 패키지내에 사용하고 있는 다른 클래스들의 가시범위에서 벗어나서 컴파일이 안될거에요. 그럼 패키지 레이어가 잘못 나누어진게 아닐까 다시한번 고민해보시고 패키지 조정도 해보면 좋을거같아요 🙏

2021-04-28 12:46 UTC, JunHoPark93 commented on src/main/java/chess/service/RoomService.java
> +        User whiteUser = userRepository.createUser(WHITE, userPassword);
한 사람이 여러 방을 생성해도 되나요?
그게 아니라면 현재 방을 가지고 있는 유저인지 확인을 해주어야될거같아요.

2021-04-28 12:46 UTC, JunHoPark93 commented on src/main/java/chess/chessgame/domain/room/Room.java
> +    public boolean isSamePassword(Color color, String password) {
방에서 사람을 찾는데 색상과 비밀번호를 동시에 다 만족해야 합니다. 메서드 이름만 봤을때는 같은 비밀번호냐를 묻고있어요.
사용처에서 room.isSamePassword(...) 라고 부르게 되는데 방의 비밀번호가 일치하는지 질의하는거같습니다.
그것보다 방에서 해당 사람이 있는지를 확인하기 때문에 room.isUserExistsIn...같은걸로 변경하고 지금처럼 두개의 인자를 사용한다면 특정 사람을 찾는 행위가 드러날거같은데 어떻게 생각하시나요?

2021-04-28 12:46 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/RoomRestController.java
> +
이부분이 웨지가 아래처럼 말씀하신 부분인가요? 
* 방을 생성한 유저는 흰색, 비밀번호를 입력하여 입장한 유저는 검은색 진영을 맡게 됩니다.
* 입장할 때 비밀번호가 일치하면 같은 유저라고 판단합니다.

이부분은 웨지가 정해서 구현하신건지 궁금해요. 무조건 생성을 하면 무조건 흰색이 되는거고 두번째 들어온사람은 무조건 검은색이 되어버리는거죠?

2021-04-28 12:46 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/GameRestController.java
> +        validateUser(user, nextColor);
이런 검증도 현재 컨트롤러에서 진행이되고있어요!
움직일수있을지없을지 판단하는것도 만들어주신 체스게임 이라는 도메인이 판단해야되는 부분 아닐까요?
이 부분은 단순히 chessService.move(...) 만 해주고 끝나는게 나을거같아요. chessService내에서 체스게임이라는 친구가 움직일수없는 요청이라면 예외를 던지면 될거구요.

2021-04-28 12:46 UTC, JunHoPark93 commented on src/main/java/chess/controller/web/GameRestController.java
> +    }
그러려면 isProperUser에서 행하는 로직이 서비스 혹은 도메인 안쪽으로 들어가게 될거구요, 지금 이 메서드는 쪼개져야할거같아요.

권한이 없는 부분(401)은 컨트롤러에서 쳐내는게 맞는거같구요. (현재 인터셉터나 필터가 없기 때문이에요. 그래서 저희가 컨트롤할수있는 최앞단 부분은 컨트롤러라고 생각할게요)

컨트롤러에서 로직을 전개하는것이 어떤 이슈가 있을지 고민해보시면 좋을거같아요 🙏

2021-04-28 13:29 UTC, sihyung92 commented on src/main/java/chess/controller/web/GameRestController.java
> +    @GetMapping("{gameId}/score")
넵!! 공통적으로 적용하도록 하겠습니다

2021-04-28 13:39 UTC, sihyung92 commented on src/main/java/chess/mysql/dao/RoomDao.java
> +import chess.mysql.dao.dto.RoomDto;
계층 내부에서만 활용할 수 있는 Dto는 접근제한자를 붙여 다른 패키지에선 존재가 드러나지 않도록 하는 것의 필요성에 대해선 공감했습니다! 하지만 default 접근 제한자를 활용하면 해당 Dto를 활용하고 있는 Dao들과 같은 패키지에 속해야 할텐데, 거기에 대해서 고민이 많습니다.
저는 그동안 패키지를 사상할 때 '~의' 라고 생각을 했는데요, 가령 chess.mysql.dao.dto.RoomDto 패키지의 경우 체스의 mysql(관련)의 dao의 dto 中 RoomDto이다  , 이런 식으로 생각해왔습니다. 피드백을 반영하려면 이런 생각을 일부 포기하고 dao와 같은 패키지에 두어야 할텐데, default 접근제한자의 범위가 하위 패키지까지 포함하는 게 아닌 같은 패키지만을 의미하는 걸 감안하면 java의 방향성과 제 패키지 설계법이 맞지 않나 생각도 드네요!! 어떻게 생각하시는지 궁금합니다

2021-04-28 13:56 UTC, sihyung92 commented on src/main/java/chess/mysql/dao/RoomDao.java
> +import chess.mysql.dao.dto.RoomDto;
해당 내용을 반영하다보니 클래스 이름에 Dao, Dto가 들어가는데 꼭 패키지로 분리할 필요는 없겠다는 생각이 들었습니다~! 해당 Dto를 알 필요가 없는 곳에서 편의를 위해 의존을 생성하던 부분을 제거하게 된 것도 또다른 수확이네요.

하지만 패키지 하나에 너무 많은 클래스가 들어가는 것에 대한 불편함도 느꼈는데요, 분류가 안 되있다는 느낌에서 오는 불편함인 것 같습니다!

1. 클래스 이름에 Dao, Dto가 들어가는데 꼭 패키지로 분리할 필요는 없다
2. 동류의 클래스끼리 묶어주는 것이 낫다
의견 궁금하네요!!
또한 한 패키지에 적당한 클래스 갯수는 어떻게 될까요?

2021-04-28 13:57 UTC, sihyung92 commented on src/main/java/chess/service/RoomService.java
> +        User whiteUser = userRepository.createUser(WHITE, userPassword);
현재는 한 사람이 여러 방을 생성 할 수 있습니다. 이 게임 저 게임 동시 대국이 가능하다는 느낌으로.. ㅎ_ㅎ

2021-04-28 14:03 UTC, sihyung92 commented on src/main/java/chess/controller/web/RoomRestController.java
> +
넵 말씀하신 내용이 맞습니다!

2021-04-28 14:13 UTC, sihyung92 commented on src/main/java/chess/chessgame/domain/room/Room.java
> +    public boolean isSamePassword(Color color, String password) {
적절치 못한 메소드명이었던 것 같습니당! 피드백 반영하여 수정하였습니다

2021-04-29 09:07 UTC, sihyung92 commented on src/main/java/chess/service/RoomService.java
> +        User whiteUser = userRepository.createUser(WHITE, userPassword);
한 사람이 멀티 게임을 동시에 진행할 수 있다는 콘셉트였는데, 오늘 크루들과 이야기 하다 보니 1인당 1게임이 맞는 것 같아 해당 내용으로 수정하겠습니다 🤔

2021-04-29 14:02 UTC, sihyung92 commented on src/main/java/chess/controller/web/GameRestController.java
> +    }
새로운 컨트롤러가 생길 때 중복 코드가 생겨나거나 버그가 일어나겠지요! 아직 레이어 분리에 대해 공부가 많이~~ 필요한 것 같습니다! 피드백 감사합니당 :)

2021-04-29 15:18 UTC, sihyung92 commented
안녕하세요 제이 귀한 피드백 감사합니당!
테스트를 조금씩 추가하겠다고 말씀드렸는데 금요일날!! MockMvc와 Mockito를 학습해서 테스트를 작성해보겠습니다~!
패키지를 재조정할 때 처음엔 dto 패키지를 다 풀어헤쳐 모두 모아놓았다가, 가독성이 너무 떨어져 패키지를 어떻게 해야 좋을까 생각을 하다 각 도메인별로 묶어보았는데 이 방법이 클래스간의 응집도를 표현해준 것 같아 괜찮은 것 같습니다. 

피드백 잔뜩 부탁드려용!!

2021-05-01 06:50 UTC, JunHoPark93 approved these changes
피드백 반영하시느라 고생많으셨습니다.
끊임없이 고민하고 시도하는모습이 정말 인상깊네요 🙇‍♂️
마지막으로 한가지 코멘트 남겨두었어요!
다음 미션도 화이팅입니다 🥳

2021-05-01 06:51 UTC, merged

2021-05-02 00:30 UTC, sihyung92 commented on src/test/java/chess/controller/chessgame/GameRestControllerTest.java
> +                .andExpect(status().isOk());
ㅎ_ㅎ 감사합니다 제이!!! 그동안 프로덕션 테스트에 사용했던 Junit5과 달리 TestDouble같은 개념도 새로 나오고 사용법을 모르면 테스트 코드를 못 짜게 될거라는 걱정이 앞서 얼른 배워야한다는 부담을 가졌었던 것 같아요 😀 
중요한건 특정 라이브러리를 통달하는 것보다 새로운 라이브러리에 빨리 적응하는 능력이라고 생각합니다~!  이번에 다양하게 사용해봤으니 다음에는 더 잘할 수 있다는 자신감이 생겼습니다 😤 다음 미션엔 Mockito까지 접목시켜보는걸로!!

제이 정말 감사했어요!!! 담에 커피 한번 살 영광을 주시길😉