[Spring 체스 - 1단계] 유콩(김유빈) 미션 제출합니다.
woowacourse/jwp-chess pull request #401
Opened 2022-04-25 06:51 UTC by kyukong

안녕하세요 에단! 리뷰를 받게 된 유콩입니다. 잘 부탁드려요.ㅎ_ㅎ

### ♟ 체스 미션
저와 제 페어 라라의 프로젝트 중 라라의 프로젝트를 선택하였습니다. 이전 미션에서 최소의 요구사항만을 지키기 위해 현재는 테이블에 `하나의 체스 게임` 정보만을 저장합니다. `game` 테이블에서는 하나의 체스게임이 저장되며 게임이 종료될 경우 정보를 삭제합니다. `piece` 테이블에서는 하나의 체스 게임에서 사용되는 기물의 정보가 저장되며 게임이 종료될 경우 정보를 삭제합니다. 2단계를 보니 체스 게임을 여러개 저장하여 원하는 체스 게임 방을 선택하는 기능이 추가되었더라구요. 이 요구사항은 **2단계**에서 추가시키겠습니다! 

### 🤓 이번 미션에서 접한 것
스프링을 처음 접하다보니 각 계층이 어떤 역할을 하는지를 파악해보았습니다.
- `dto` : 여러 계층간에 정보를 전달하기 위해 만들어진 객체
- `dao` : DB 에 쿼리문을 실행시키는 객체
- `service` : DB 와 관련된 비즈니스 로직을 담는 객체

혹시 잘못 이해하고 있는 개념이 있다면 피드백 부탁드립니다!

### 🧐 질문
- rest API 규격에 맞게 URL 을 설계한 것이 맞나요?
> `/chess-game` : index.hbs 파일 호출
`/chess-game/load` : DB 에 저장된 체스 게임 정보 호출
`/chess-game/start` : 체스 게임 시작
`/chess-game/score` : 체스 게임 정보 호출
`/chess-game/move` : 기물 이동
`/chess-game/end` : 체스 게임 종료

GET, POST 등과 같은 API method 로 용도를 나타내고 URL 에는 동사를 사용하지 말라는 글을 본 적이 있습니다. 하지만 http 강의를 보니 실제로 method 로만 구분하기에는 API 의 종류가 너무 다양해 실제로는 동사를 사용하는 경우도 있다고 하시더라구요. 제가 설계한 것처럼 의미를 분명하게 나타내기 위해 다음과 같은 동사들을 사용해도 되는 걸까요?

***

피드백 감사합니다. 기다리고 있겠습니다! 🙇‍♀️

2022-04-25 09:44 UTC, Laterality requested changes
안녕하세요 유콩.

리뷰어 에단입니다 👋 

전반적으로 잘 구현해주셨어요.

몇가지 피드백을 남겨드렸는데, 확인 부탁드려요.

궁금하신 점은 언제든 DM 주세요!

## Q&A

* Q. rest API 규격에 맞게 URL 을 설계한 것이 맞나요?

요약: URL로 리소스를 식별하고 있다면 Yes, 그렇지 않다면 No.

REST API에 관해서는 사람마다 의견이나 원칙이 조금씩 다른 주제이다보니 제가 딱 잘라서 이것이 맞다 틀리다 이야기하긴 어렵겠어요. 다만 REST API라는 개념을 처음 제안한 Roy Fielding은 아래처럼 정의했네요:

> The key abstraction of information in REST is a resource. Any information that can be named can be a resource: a document or image, a temporal service (e.g. "today's weather in Los Angeles"), a collection of other resources, a non-virtual object (e.g. a person), and so on. In other words, any concept that might be the target of an author's hypertext reference must fit within the definition of a resource. A resource is a conceptual mapping to a set of entities, not the entity that corresponds to the mapping at any particular point in time.

비슷한 질문의 [Stackoverflow  답변](https://stackoverflow.com/a/19650279)에서 말하는 것처럼, 단순히 동사냐 명사냐로 판단하기보다는 이 URL이 "리소스를 식별하고 있는가"로 판단하는 것이 정확할 수 있겠네요.

말씀하신 것처럼 모든 API를 REST 제약 조건을 모두 만족하도는 RESTful API로 정의하고 개발하는 것은 쉽지 않은 일이기도 하고 실용적이지 않을 수도 있어요. 대신 이 경우에는 REST API와 구분하기 위해 Web API 혹은 HTTP API 등으로 부르기도 합니다.

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/Command.java
> +public enum Command {
이 클래스는 사용되는 곳이 있을까요?

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/controller/ExceptionAdvice.java
> +    public ResponseEntity<ErrorResponseDto> handleIllegalArgumentException(Exception exception) {
`IllegalArgumentException`만 처리하는 메서드인데 인자 타입이 `Exception`일 필요가 있을까요?

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/dao/GameDao.java
> +
여백은 한 줄 씩만 사용해주세요~

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/dao/GameDaoImpl.java
> +public class GameDaoImpl implements GameDao {
`Impl`이라는 접미사는 이 클래스의 어떤 특성도 설명하지 못하는데요. 

이 클래스를 더 잘 나타낼 수 있는 이름이 있을까요?

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/dao/GameDaoImpl.java
> +                            )
늘어난 depth를 어떻게 하면 줄일 수 있을까요?

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/dao/PieceDao.java
> +    void update(Position source, Position target);
업데이트하는 것이 `Piece`가 아니라 `Piece`의 위치 뿐이라면 메서드명에 이 점을 나타내면 어떨까요?

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/dto/ChessResponseDto.java
> +package chess.dto;
이 패키지는 컨트롤러와 서비스 중 어느 계층에 속할까요?

2022-04-25 09:44 UTC, Laterality commented on src/main/java/chess/dto/ScoresDto.java
> +        return scores;
API에서 응답 필드에 노출시키기 위한 거라면 문제 없겠지만, 서비스에서 반환되는 DTO라면 컬렉션을 복사해 반환하면 어떨까요?

2022-04-25 09:44 UTC, Laterality commented on src/test/java/chess/service/ChessServiceTest.java
> +public class ChessServiceTest {
서비스에 대한 테스트 💯

2022-04-25 14:14 UTC, kyukong commented on src/main/java/chess/Command.java
> +public enum Command {
헉! 콘솔 관련된 클래스는 다 지운줄 알았는데 남아있었네요! 삭제하였습니다!!

2022-04-25 14:30 UTC, kyukong commented on src/main/java/chess/dao/GameDaoImpl.java
> +public class GameDaoImpl implements GameDao {
Spring 의 JdbcTemplate 을 사용하였으므로 `GameDaoImpl` 을 `JdbcGameDao` 으로, `PieceDaoImpl` 을 `JdbcPieceDao` 으로 수정하였습니다.

2022-04-25 14:52 UTC, kyukong commented on src/main/java/chess/dto/ScoresDto.java
> +        return scores;
서비스에서 반환되는 DTO 도, 서비스에서 사용하지 않는 DTO 및 도메인도 모두 복사해서 반환하였습니다. 현재는 사용하지 않더라도 사용할 수는 있는 객체이기 때문에 모두 처리했습니다.

2022-04-25 15:07 UTC, kyukong commented on src/main/java/chess/dao/PieceDao.java
> +    void update(Position source, Position target);
실제 쿼리문은 `Piece` 의 위치만을 수정하므로 `modifyPosition` 으로 수정하였습니다.

2022-04-26 07:18 UTC, kyukong commented on src/main/java/chess/dto/ChessResponseDto.java
> +package chess.dto;
처음엔 그저 dto 니까 같은 패키지로 묶었다가, 에단의 피드백을 받고 제 나름의 기준대로 나누어 보았습니다.

- `controller` 패키지 내 dto : controller 에 있는 클래스에서만 호출하며 뷰에 띄우기 위해 사용하는 dto 객체
- `service` 패키지 내 dto : service 에서 **생성**하는 dto 객체

2022-04-26 10:19 UTC, Laterality approved these changes
안녕하세요 유콩.

잘 수정해주셨어요 👍 

이번 미션은 이만 머지하도록 할게요.

간단한 피드백을 추가로 남겨드렸는데, 다음 단계 진행하면서 참고해주세요.

고생 많으셨습니다 :)

2022-04-26 10:19 UTC, Laterality commented on src/main/java/chess/dto/ChessResponseDto.java
> +package chess.dto;
💯

2022-04-26 10:19 UTC, Laterality commented on src/main/java/chess/dao/JdbcGameDao.java
> +        final String sql = "insert into game (turn, status) values (?, ?)";
쿼리를 상수로 분리해보면 어떨까요?

2022-04-26 10:19 UTC, Laterality commented on src/main/java/chess/dao/JdbcGameDao.java
> +    private RowMapper<GameDto> getGameDtoRowMapper() {
메서드를 호출할 때마다 익명 객체가 새로 생성될텐데요.

여기서 반환하는 객체는 재사용할 수 없을까요?

2022-04-26 10:19 UTC, merged