[Spring 체스 - 1단계] 슬로(이한울) 미션 제출합니다.
woowacourse/jwp-chess pull request #409
Opened 2022-04-25 08:34 UTC by hanull

안녕하세요 철시, 슬로입니다.
이번 미션동안 잘부탁드려요~! 감사합니다 😁

2022-04-25 08:44 UTC, hanull commented on src/main/java/chess/controller/ChessGameController.java
> +    public ResponseEntity<ChessGameDto> createNewGame(@RequestParam("name") String gameName) {
PostMapping으로 보낼 때, body는 비워두고 parameter 로 보내도 괜찮을까요?

저는 새로 게임을 생성할 때, 이름만 사용하기 때문에 RequestBody로 받아서 새로운 dto 클래스를 생성하는 것이 불필요하다고 생각했어요. 그래서 body 부분은 비워두고 RequestParam을 사용했습니다.

2022-04-25 14:42 UTC, pkch93 requested changes
안녕하세요 슬로 👋 만나뵙게되서 반갑습니다~!
전반적으로 Spring 적용 잘해주셨네요. 👍
몇몇 피드백 드렸는데 확인 부탁드릴께요~!

2022-04-25 14:42 UTC, pkch93 commented on src/main/java/chess/controller/ChessGameController.java
> +    public ResponseEntity<ChessGameDto> createNewGame(@RequestParam("name") String gameName) {
그렇다면 굳이 Content-Type을 `application/json`로 받을 필요가 있을까요? json 형태의 body를 사용할 필요가 없다면 다른 Contnet-Type을 고려해볼 수 있을거 같아요.

2022-04-25 14:42 UTC, pkch93 commented on src/main/java/chess/controller/ChessGameController.java
> +    @GetMapping("/finish")
GET HTTP 메서드는 보통 다른 사이드 이펙트 없는 조회시에 사용을 하는데요.
현재 `finishGame`은 게임 종료를 위해서 여러 데이터를 정리하는 동작들을 하는것 같네요. GET이 적절할지도 고민해보면 좋을거 같아요.

2022-04-25 14:42 UTC, pkch93 commented on src/main/java/chess/exception/ExecuteQueryException.java
> +        super(HttpStatus.NOT_ACCEPTABLE, message);
`ExecuteQueryException`는 쿼리 실행 실패시에 발생하네요. 이 경우 406 응답을 내리는데 어떤 이유일까요?

2022-04-25 14:42 UTC, pkch93 commented on src/main/java/chess/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
예외 처리를 담당하는 `GlobalExceptionHandler`를 `@RestControllerAdvice`를 활용하여 구현하셨군요~ 👍

2022-04-25 14:42 UTC, pkch93 commented on src/main/java/chess/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new ErrorMessageDto(e.getMessage()));
`DataAccessException`가 발생할때는 400 응답을 내리내요. 이유가 있을까요?

2022-04-25 14:42 UTC, pkch93 commented on docker/docker-compose.yml
> +      - ./db/mysql/init:/docker-entrypoint-initdb.d
현재 테이블 초기화가 되지 않네요. 그래서 게임 실행이 되지 않는데 이부분도 같이 확인부탁드려요.

2022-04-26 08:46 UTC, hanull commented on docker/docker-compose.yml
> +      - ./db/mysql/init:/docker-entrypoint-initdb.d
gitignore 설정을 잘못해서 테이블 관련 sql 이 안올라간 것 같아요. 수정했습니다!

2022-04-26 11:10 UTC, hanull commented on src/main/java/chess/controller/ChessGameController.java
> +    public ResponseEntity<ChessGameDto> createNewGame(@RequestParam("name") String gameName) {
content-type 을 `application/x-www-form-urlencoded` 로 사용해서 body 없이 RequestParam 으로 받도록 수정했어요!

2022-04-26 16:59 UTC, hanull commented on src/main/java/chess/controller/ChessGameController.java
> +    @GetMapping("/finish")
철시가 말한 것처럼 GET은 항상 동일한 응답을 돌려받는 조회 시에 사용한다는 것을 알게 됐어요! 
그리고 게임과 체스말 정보를 삭제하는 동작을 하기 때문에 Delete로 바꿨습니다.

2022-04-26 17:40 UTC, hanull commented on src/main/java/chess/exception/ExecuteQueryException.java
> +        super(HttpStatus.NOT_ACCEPTABLE, message);
잘못 생각한 것 같아요!! 찾아보니 406 응답은 `content-type 에 적혀있는 형식으로 변환이 불가능할 때` 발생한다는 걸 알게됐어요.
그리고 쿼리, DB 에러는 서버와 관련 있기 때문에 500 에러를 내리는 게 맞는거 같아요!

2022-04-26 22:47 UTC, pkch93 approved these changes
피드백 확인 및 반영하시느라 고생하셨습니다~ 👍 
슬로의 1단계는 이만 머지할께요. 2단계 때 더 많은 이야기 나눠봐요 ㅎㅎ

2022-04-26 22:47 UTC, merged