[Spring 체스 - 2단계] 알렉스(이영환) 미션 제출합니다.
woowacourse/jwp-chess pull request #411
Opened 2022-04-25 15:39 UTC by yxxnghwan

안녕하세요 루피! 두 번째 PR이네요!
이번 리뷰도 잘 부탁드립니다!(공부할 것을 던져주시면 간식받은 강아지마냥 기쁘답니다ㅎㅎ)

DM에서 얘기 나눴듯 도메인 객체를 엔티티로 사용하는 구조는 트레이드 오프로 이점이 조금 더 느껴져서 따로 분리하지는 않았습니다!

> RestController 와 Controller 의 차이에 대해서 학습해보면 좋을 것 같아요.
> 
> 스프링에서 작성한 어노테이션 코드를 살펴보면 도움이 되실 것 같아요 ㅎㅎ

컨트롤러에 대해서는 `@RestController`가 `@Controller` + `@ResponseBody`역할을 하는 것으로 알고 있는데,
1단계 PR에서 질문 드렸던 컨트롤러를 나누는 기준에 대해 좀 더 고민해보고 RestController와 Controller를 분리할지 말지 결정해야할 것 같아요! 현재 어플리케이션에서 rest api방식으로 동작하는 메서드도 있지만, 뷰를 반환하는 메서드가 같이 있기 때문에 Controller에 필요한 메서드만 ResponseBody를 붙이는 것도 나쁘지 않은 방식이라는 생각이 들었습니다. 혹시나 잘못된 점이 있다면 지적 부탁드려요!🙏

> 생성자 주입에 대하여 추가로 읽어보시면 좋을 것 같아요 ㅎㅎ
> 
> 아래 링크를 참고해주세요

생성자가 한개일 경우에는 `@Autowired`어노테이션을 제거해도 생성자 주입이 동작하는군요! 불필요한 어노테이션들을 제거했습니다.

> for 문이 도는 중간에 어떠한 이유로 실행이 실패하여 중단된다면 어떤 일이 발생할지 고민해보는 것도 좋을 것 같아요.
> 
> 이번에 사용하신 MySQL 은 강력한 원자성을 보장하기 위해 어떤 기능을 제공하고 있을까요 ?

중간에 에러가 발생하면 앞에 넣었던 데이터만 반영되고 추후 넣어야할 데이터는 들어가지 않는 끔찍한 상황이 발생하겠네요!
트랜잭션이라는 것을 알게되어 서비스의 메서드마다 `@Transactional`을 붙였습니다! 맞게 적용시킨 건지 확신이 안서네요 한번 확인 부탁드려요 ㅠㅠ😂

2022-04-26 01:55 UTC, TheDevLuffy requested changes
알렉스 안녕하세요.

사실 스프링 가져다 사용하는 부분이라 코드 리뷰는 딱히 더 할 것이 없는 것 같아서.. 이것저것 스프링 문서 링크를 가져와봤어요.

`@Controller` 와 `@RestController` 는 말씀해주신 차이 외에도 컨트롤러는 `spring-context` 와 `spring-web` 각각에 정의되어 있다는 점도 있습니다. 이 이상은 더 알게 되면 저한테도 알려주세요 ㅎㅎ

생성자 주입은 스프링 문서에서는 본인들이 POJO 를 지향하기 때문에 만든 방식이라고 하지만, POJO 도 논란의 여지가 많은 개념이라 이런게 있구나 하고 차차 고민해보시는 것도 좋을 것 같아요. 꼭 알아야 되는 것은 아닙니다 !

* [POCO](https://en.wikipedia.org/wiki/Plain_old_CLR_object)
* [POJO](https://en.wikipedia.org/wiki/Plain_old_Java_object)

`@Transactional` 어노테이션도 잘 사용해주신 것으로 보여요. ㅎㅎ 그래서 한번 더 생각해볼 내용을 코멘트로 남겨두었으니 참고 부탁드려요.

일단 시간이 많이 남아서 Request changes 로 리뷰를 드리긴 할텐데 딱히 수정할 내용이 없다고 생각하시면, 따로 알려주세요 ㅎㅎ

2022-04-26 01:55 UTC, TheDevLuffy commented on build.gradle
> +    //implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
주석처리 하신 이유가 따로 있으실까요 ?

불필요하다면 제거해주세요 ㅎㅎ

2022-04-26 01:55 UTC, TheDevLuffy commented on src/main/java/chess/service/GameService.java
>      public ChessGame findByGameId(final Long gameId) {
읽기 작업에서는 데이터베이스의 작업, 읽기시 설정에 따라 결과값이 달라질 수 있을텐데요.

`spring-framework/spring-tx` 의 `@Transactional` 중 isolation 을 참고해보시면 도움이 될 것 같아요.

각각이 어떤 상황에 사용될 수 있을지 고민해보면 어떨까요 ㅎㅎ

https://github.com/spring-projects/spring-framework/blob/b595dc1dfad9db534ca7b9e8f46bb9926b88ab5a/spring-tx/src/main/java/org/springframework/transaction/annotation/Isolation.java

2022-04-26 01:55 UTC, TheDevLuffy commented on src/main/java/chess/service/GameService.java
>      public void move(final Long gameId, final String rawFrom, final String rawTo) {
동일한 gameId 에 대해서 동시에 서로 다른 요청이 들어오는 경우는 어떻게 처리할 수 있을까요 ?

"2단계 - 동시에 여러 게임 하기" 이니 한번 고민해볼 수 있는 주제인 것 같아요.

2022-04-26 01:55 UTC, TheDevLuffy commented on src/main/java/chess/service/GameService.java
>      public void move(final Long gameId, final String rawFrom, final String rawTo) {
키워드는 `공유자원`, `동시성` 정도가 될 수 있을 것 같아요.

2022-04-26 01:55 UTC, TheDevLuffy commented on src/main/java/chess/config/DataSourceConfig.java
> +    public PlatformTransactionManager transactionManager(DataSource dataSource) {
스프링 프레임워크에서 트랜잭션을 지원하는 배경과 각각에 대한 장단점을 설명해두었는데요.

한번 참고해보셔도 좋을 것 같아요.

https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction-motivation

2022-04-26 08:49 UTC, yxxnghwan commented on build.gradle
> +    //implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
제가 로그백을 따로 사용할줄을 몰라서 예외 로그를 확인하는 데에 오히려 더 방해되어서 주석처리 했습니다..! 굳이 사용하지 않는 것 같아서 지금은 제거했어요! 더불어서 스파크에 대한 부분도 같이 더이상 사용하지 않으므로 제거했습니다!

2022-04-26 08:52 UTC, yxxnghwan commented on src/main/java/chess/service/GameService.java
>      public ChessGame findByGameId(final Long gameId) {
트랜잭션에 isolation level이라는게 있었군요! 낮은 레벨일 수록 빠르지만 안정성이 떨어지구요.
읽기의 경우엔 커밋된 트랜잭션에 대한 데이터는 읽어도 좋을 것 같아서 `READ_COMMITTED` 레벨로 했구요,
수정의 경우 트랜잭션에서 사용하는 데이터가 완전히 독립되는 것이 안전할 것 같아서 가장 높은 `SERIALIZABLE`레벨로 설정했는데,
이렇게 설정한게 맞을지 의견 부탁드려도 될까요?

2022-04-26 08:54 UTC, yxxnghwan commented on src/main/java/chess/service/GameService.java
>      public void move(final Long gameId, final String rawFrom, final String rawTo) {
해당 메서드를 여러 스레드에서 접근할 수 없도록 `synchronized` 키워드를 붙였습니다!
그리고 DB도 해당 데이터에 여러 수정 요청이 동시에 들어오면 안될 것 같아서 트랜잭션 isolation 레벨을 SERIALIZABLE로 설정했습니다!

2022-04-26 08:56 UTC, yxxnghwan commented on src/main/java/chess/config/DataSourceConfig.java
> +    public PlatformTransactionManager transactionManager(DataSource dataSource) {
아직 공식문서를 보고 이해할 정도가 안되나봐요..!ㅠㅠ 다음 리뷰 해주시는 동안 더 공부해보겠습니다!

2022-04-26 08:57 UTC, yxxnghwan commented
안녕하세요 루피! 언급해주신 부분들에 대해 코드수정 해봤습니다!
리뷰 잘부탁드립니다!

2022-04-26 13:05 UTC, TheDevLuffy approved these changes
안녕하세요~ 알렉스 !

뭔가 추가로 고민해볼 포인트로만 코멘트드리고 코드에 반영은 안해주셔도 되는 것들인데 코드로 반영을 해주셨군요.
이번 미션은 스프링 전환하기가 목표였는데 제가 너무 많은 것들을 이야기 했나봅니다. 🤣

잘 진행해주셨구요.
너무 빨리 진행해주셔서 벌써 머지해도 괜찮을까 싶기도 한데, 잘 진행해주셔서 2단계도 이만 머지하도록 할께요 !

2022-04-26 13:05 UTC, workromancer commented on src/test/java/chess/dao/MockGameDao.java
>      private final static Map<Long, ChessGame> store = new ConcurrentHashMap<>();
이 MockGameDao 를 왜 지금 봤을까요

Map 을 이용한 DB 목킹 좋네요 👍

2022-04-26 13:05 UTC, workromancer commented on src/test/java/chess/service/GameServiceTest.java
> +import static org.assertj.core.api.Assertions.assertThatThrownBy;
명시적인 import 문 👍

intellij 설정을 통해 wildcard import 를 끌 수 있어요

2022-04-26 13:05 UTC, workromancer commented on src/main/java/chess/controller/spring/GameController.java
> +    @ResponseBody
👍

제가 놓쳤군요 🤣

2022-04-26 13:05 UTC, workromancer commented on src/main/java/chess/service/GameService.java
> +    @Transactional(isolation = Isolation.SERIALIZABLE)
저는 `@Transactional` 을 리뷰에 반영해주실줄은 몰랐습니다...

그냥 이런게 있으니 살펴보면 좋을 것 같다는 의도였는데..!

SERIALIZABLE 은 동시성이 중요한 경우 잘 사용하지 않습니다. 이 말은 즉 오늘날 서비스하는 회사는 대부분 사용하지 않을 것 같아요.
관련해서는 Spring 이 지원하는 기능이고, Isolation level 같은 경우는 DB 에 너무 가까운 내용이니 그냥 이런게 있구나 하고 넘어가는 것이 좋을 것 같아요... 아직 Spring 시작하시는 단계이신데 제가 괜한 코멘트를 남긴건 아닌가 싶네요 ㅎㅎ

2022-04-26 13:05 UTC, workromancer commented on src/main/java/chess/service/MemberService.java
> +    @Transactional(isolation = Isolation.READ_COMMITTED)
member 조회는 적절하게 사용해주신 것 같아요 ㅎㅎ

2022-04-26 13:05 UTC, TheDevLuffy commented on src/main/java/chess/service/GameService.java
>      public ChessGame findByGameId(final Long gameId) {
`SERIALIZABLE` 을 사용하는 경우 동시 접근이 제한되어서 가용성(availability)가 떨어지게 될꺼예요.

요 부분은 차차 더 고민해보셔도 좋을 것 같아서 이정도만 하겠습니다 ㅎㅎ

https://hyunki1019.tistory.com/111

2022-04-27 12:13 UTC, yxxnghwan commented
안녕하세요! 루피! 미션 요구사항과 다르게 구현된 점 있었던 것 같아서 맞춰봤습니다! 
저는 입장시 비밀번호를 누르고 입장하는줄 알았는데 삭제시 비밀번호를 입력하는 요구사항이더라구요! 요구사항에 맞게 기능 변경해봤구요!

`@Transactional`의 `isolation level`에 대한 고민을 해봤는데요! 다음같은 생각을 정리해봤습니다!

## move 명령이 동시에 여러 개가 들어온다면..?

transaction에서 isolation 레벨을 serialize로 설정한다. 그럼 해당 데이터를 건드리는 로직에 lock이 걸리기 때문에 먼저 시작된 트랜잭션이 끝나기 전까지 이후에 들어온 트랜잭션이 레코드를 건드릴 수 없다.

isolation 레벨이 높아질수록 속도는 느려지고 안정성은 올라간다.

막아야 하는 건 move에서 건드리는 레코드에 대한 동시수정이다. 모든 move의 동시작업이 아님.

그래서 move 메서드 자체를 synchronized 붙이는건 맞지 않은 것 같음.

같은 게임 id를 건드리는 행에 대해서만 이루어지면 된다.

즉 DB의 레코드 단에서 동시 접근을 막아야한다. 그때 쓰는게 isolation레벨을 serializable로 두는 것임.

근데 serializable의 동시접근 레코드를 판단하는 기준은 where절 기준인데 나는 where절 조건이 gameId만 있는 것이 아니라 피스 위치까지 조건절에 들어간다. 피스위치가 다르고 게임만 같으면 레코드에 대한 동시 접근이 허용되는 상황이다.

어카지..?

1. 동시성 이슈를 포기한다 ^^
2. 조건절을 맞추기 위해 무브 방식을 gameId에 맞는 모든 pieces를 삭제하고 다시 무브된 pieces를 넣는다. (전에 그렇게 구현되어 있었는데 좀 느렸음. 매번 64개를 삭제하고 새로 insert해서 그런듯)
3. 그냥 game 테이블에 각 피스들의 컬럼 64개를 추가로 뚫어준다^^ (빠르고 조건절도 맞출 수 있다. 근데 컬럼 64개를 더 뚫는다..? 이건 너무 정규화를 무시한 케이스가 아닐까...)

---

위같은 생각을 해봤는데... 명확한 해결책이 떠오르지 않는군요..😂 루피의 생각을 공유해주시거나 더 공부할 방향을 제시 부탁드려도 될까요..?

2022-04-27 21:22 UTC, TheDevLuffy approved these changes
알렉스 안녕하세요.

PR 이 벌써 3번째 ? 4번째가 되어가고 있는 것 같아요 🤣
아직 우테코 과정이 많이 남았으니 동시성 관련해서는 운영체제에서 공유자원 관련된 내용을 확인해보시고, 이를 처리하는 방법으로 DB의 기능을 이용하는 비관적 락, 쿼리를 이용하는 낙관적 락 두 가지 키워드를 가지고 추가 학습을 해보는 것이 좋을 것 같아요.

GameControllerTest 에 추가해주신 테스트 오류와 게임 실행시 동일한 유저로 게임이 생성되는 것만 의도된 것인지 확인해주시면 해당 미션은 머지하고 따로 학습하시면서 이야기 나눠 보시죠. ㅎㅎ

2022-04-28 04:18 UTC, yxxnghwan commented
안녕하세요 루피! 말씀해주신 두 가지 사항 수정했습니다!

제가 게임 삭제시 해당 게임이 종료된 게임인지 판단하는 로직을 추가하면서 테스트를 변경하지 않았었네요!
테스트 케이스 추가하면서 해당 문제점 해결했구요!
같은 멤버id로 게임을 생성하는 경우는 컨트롤러의 핸들러 메서드에서 검증하도록 했습니다!

동시성 이슈에 관련된 내용은 루피가 주신 키워드로 학습해보고 따로 DM으로 추가 질문 드려도 될까요?!

2022-04-28 19:00 UTC, workromancer approved these changes
알렉스 고생 많았어요 !

제가 너무 머리 아픈 내용들을 리뷰 드린건 아닌가 싶네요 ㅠㅠ

이만 머지하겠습니다 ! 고생하셨습니다 !

2022-04-28 19:00 UTC, TheDevLuffy commented on src/main/java/chess/controller/spring/GameController.java
> +        final Long whiteId = createGameRequestDto.getWhiteId();
👍

2022-04-28 19:00 UTC, TheDevLuffy commented on src/test/java/chess/controller/spring/GameControllerTest.java
> +    void deletePlayingGame() {
👍

2022-04-28 19:00 UTC, merged

2022-04-30 09:09 UTC, yxxnghwan commented
루피! 비관적 락과 낙관적 락에 대해 학습해보았는데, 트랜잭션을 이용하지 않고 낙관적 락을 통해 ~~큰 성능 저하 없이~~ 원래 문제되었던 동시성 문제를 해결할 수 있을 것 같아요! 학습 이후에 추가로 궁금한 점이 생겼는데요, 낙관적 락을 사용할 경우 rollback이 필요한 상황에서 트랜잭션의 롤백기능을 이용할 수 없는데, 오히려 그 문제때문에 불안감이 올라갈 수 있을 것 같아서요...ㅠㅠ

실무에선 이런 공유자원에 대한 동시접속에 대해서 주로 어떤 방식으로 처리하는지 궁금한데 여쭤볼 수 있을까요?
더불어서 루피가 체스를 구현하신다면 동시 움직임 요청에 대해서 어떤 방식으로 동시성 이슈를 해결할지 의견이 궁금합니다!

2022-04-30 09:35 UTC, TheDevLuffy commented
@yxxnghwan 

낙관적 락에 대하여 포인트를 잘 잡아주신 것 같아요. 낙관적 락은 가용성을 최대한 보장하면서 동시성 문제를 쿼리(where절)를 이용하여 해결할 수 있는 방법이거든요.

트랜잭션은 쿼리를 실행하기 이전에 트랜잭션을 열고, 하나 이상의 쿼리 수행 후 commit 을 통해 한번에 반영하거나 혹은 롤백이 수행 되는 것이라 별개의 범위가 아닌가요?! 추가로 학습해보시고 저도 한번 알려주세요 ㅎㅎ

실무에서도 크게 다르지 않아요 ㅎㅎ 운영체제에서 공유자원을 다루는 방법들을 바탕으로 여러가지 도구를 이용하여 구현을 하는 것이거든요.

저 같은 경우는 낙관적 락과 비관적 락에 대하여 몇 가지 기준을 더 두는데요. 발생 빈도, 행위의 주체가 하나 이상인가, 경합발생시 비즈니스 로직에 대한 영향도 정도를 추가로 고려해서 동시성 이슈 바라봅니다 !

2022-05-02 05:46 UTC, yxxnghwan commented
> 트랜잭션은 쿼리를 실행하기 이전에 트랜잭션을 열고, 하나 이상의 쿼리 수행 후 commit 을 통해 한번에 반영하거나 혹은 롤백이 수행 되는 것이라 별개의 범위가 아닌가요?! 추가로 학습해보시고 저도 한번 알려주세요 ㅎㅎ

낙관적 락을 사용하는 경우 트랜잭션을 함께 사용하면
`세션1이 1번 게임의 기물들을 수정하는 중일 때 동시에 세션2가 같은 1번 게임의 기물을 수정하려 한다면, 세션1이 수정을 커밋하기 전에 세션 2가 접근하면 세션 2와 같은 버전을 읽어들이고 같은 버전으로 커밋을 하게되는 문제가 발생하지 않을까?` 하는 생각으로 업데이트 되는 족족 바로 반영되어야 그 로우를 더 이상 건드리지 않을 거라고 생각해서 저렇게 답글을 달았습니다! 근데 낙관적 락은 트랜잭션 충돌이 일어나지 않는다고 가정한 락 기법이다보니 트랜잭션을 사용하는 것과는 별개인 것 같아요. 제가 잘못 생각했네요!


공부를 하다 `select ~ for update`문을 통해 락을 거는 방법에 대해 알게 되었는데요, 트랜잭션 시작시에 해당 게임 기물에 관한 데이터에 락을 거는 방식을 사용하면 원하는 데이터에 대한 동시접근을 막을 수 있을 것 같은데 저는 이번 체스 같은 경우는 절대로 두 세션이 동시에 같은 게임의 체스 기물 데이터에 접근하면 안된다고 생각하거든요! 그래서 `select ~ for update`문을 써서 현재 수정중인 게임에 대한 락을 거는 방법이 괜찮을 것 같은데, 이 방법도 DB의 기능을 이용하는 비관적 락에 해당될까요?