[Spring 체스 - 2단계] 애쉬(김동호) 미션 제출합니다.
woowacourse/jwp-chess pull request #415
Opened 2022-04-27 05:36 UTC by dongho108

안녕하세요 제이! 2단계 미션 제출합니다.
DM으로 질문 많이 드렸는데 답장 많이 해주셔서 감사합니다 ㅠㅠ!!

## 1단계 피드백 반영했습니다.

- ChessGame이 필드에 존재
> 여러 게임을 동시에 실행시킬 수 없으므로 id를 이용해 매번 가져오도록 수정했습니다.

- repository vs dao
> 지금까지 둘의 차이를 아예 모르고 용어를 사용하고 있었습니다.
그래서 일단 느낌이라도 알려고 간단하게 학습을 했습니다.
지금은 repository는 특정 엔티티 중심, dao는 db중심이라는 정도로만 알고있고, 이번 미션 동안 더 학습해 나갈 예정입니다.

## 2단계 구현

> UI는 정말 부족하게 짰습니다. 얼른 피드백받고 더 공부하려고 최대한 빨리 작성해 제출합니다!

2022-04-29 10:37 UTC, jjj0611 requested changes
안녕하세요 애쉬! 리뷰어제이입니다.

구현해주신 코드 잘 봤습니다!
간단하게 고민해볼만한 부분들 코멘트로 남겨두었어요.

코멘트 확인부탁드리고, 혹시 궁금하신 점이나 잘 모르겠다 싶은 부분은 DM이나 코멘트로 알려주세요 :)

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +    private final JdbcTemplate jdbcTemplate;
한 번 주입한 뒤 변경할 수 없도록 잘 막아주셨네요 👍

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +            ps.setString(3, "white");
항상 첫 턴이 화이트여서 이렇게 저장하는걸까요?
만약 규칙이 바뀌어서 흑이 먼저 시작하는 걸로 바뀌면 이전에 생성된 게임들은 백이 먼저 시작되고,
새롭게 생성된 게임들은 흑이 먼저 시작되는 구조겠네요 :)

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +    }
체스 게임이 2조 개 생성되어 있으면 어떻게 될까요..?!

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +        if (isEnd(chessGameId)) {
체스 게임이 완전히 끝나지 않으면 삭제를 할 수가 없군요!

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +        if (result.isEmpty()) {
메서드를 호출하는 곳에서 NPE가 터질 가능성은 없나요??

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +        jdbcTemplate.update(sql, password, chessGameId);
만약 이 과정에서 DataAccessException이 발생하면 어떻게 되나요??

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +        chessGameDao.update(chessGame.getState().getTurn(), chessGameId);
체스 게임을 찾아서 커맨드로 진행시키는 것 까지는 좋은데,
pieceDao에서 삭제하고, 저장하는 로직과 chessGame을 저장하는 로직까지는 개념적으로 하나로 합쳐져 있어야 할 것 같아요.
제가 저번에 말씀드린 58번 라인에서 성공하고, 59번에서 실패하면 어떻게 될까요?와는 별개로 드리는 코멘트에요!

2022-04-29 10:37 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +        ChessGame chessGame = chessGameDao.findById(chessGameId);
비밀번호는 게임 참가에 쓰이는게 아니라 삭제에만 쓰이나요???

2022-04-29 10:37 UTC, jjj0611 commented on src/test/java/chess/dao/ChessGameDaoTest.java
> +@Transactional
어떤 의미로 붙여주신걸까요??
Transaction에 대한 공부를 하셨을까요??

2022-04-29 10:37 UTC, jjj0611 commented on src/test/java/chess/service/ChessServiceTest.java
> +class ChessServiceTest {
전체적으로 Service 테스트가 조금 부실한 것 같아요.
테스트 하지 않은 부분들은 필요가 없다고 느껴서일까요??

2022-04-30 03:30 UTC, dongho108 commented on src/main/java/chess/dao/ChessGameDao.java
> +    }
너무 많은 데이터를 가져올 것 같습니다.
select 쿼리에 limit 를 두고 가져오도록 수정했습니다.

추가로 100개만 가져오지만 101번쨰 만든 방을 들어가기 위해선 방들을 page로 구분해서 가져오는 기능이 있어야 할 것 같아요.

2022-04-30 03:54 UTC, dongho108 commented on src/main/java/chess/service/ChessService.java
> +        ChessGame chessGame = chessGameDao.findById(chessGameId);
요구사항이 게임참가일땐 방제목클릭, 삭제할때는 패스워드가 필요하다고 되어있어서 이렇게 구현했어요!

2022-04-30 04:15 UTC, dongho108 commented on src/test/java/chess/dao/ChessGameDaoTest.java
> +@Transactional
테스트에서 @Transactional이 데이터를 자동으로 rollback 시키는 기능을 사용하려고 붙였습니다!!

2022-05-01 14:11 UTC, dongho108 commented on src/main/java/chess/service/ChessService.java
> +        if (isEnd(chessGameId)) {
요구사항이 종료된 게임만 삭제할 수 있다여서요!!

2022-05-01 15:23 UTC, dongho108 commented on src/main/java/chess/service/ChessService.java
> +        chessGameDao.update(chessGame.getState().getTurn(), chessGameId);
삭제하고 update, update하는 쿼리는 결국에 세번 나가야할 것 같아서  ```개념적으로 합치라```는 말씀에 집중해 그냥 메서드로 묶었습니다.

2022-05-01 15:24 UTC, dongho108 commented on src/test/java/chess/service/ChessServiceTest.java
> +class ChessServiceTest {
단순 도메인로직을 호출하는 메서드는 테스트 하지 않았습니다. 그 외에 추가로 행위를 해주는 메서드들은 테스트를 추가해주었습니다!

2022-05-01 16:51 UTC, dongho108 commented on src/main/java/chess/dao/ChessGameDao.java
> +            ps.setString(3, "white");
게임이 시작될때 ready상태로 시작되고 게임시작 버튼을 누르면 그때 턴이 저장되도록 수정했습니다. 만약 첫턴을 블랙으로 바꾸게되면 도메인로직이 수정되는 것이므로 도메인의 execute에서 command가 start시 new Black()을 return하도록 하면 됩니다.

2022-05-01 16:52 UTC, dongho108 commented on src/main/java/chess/dao/ChessGameDao.java
> +        if (result.isEmpty()) {
기존의 beforeFirst()를 이용하기위해 preparedStatement로 옵션을 지정해주던 코드를 없애고 단건조회 쿼리를 하도록 수정했습니다.

2022-05-01 17:02 UTC, dongho108 commented on src/main/java/chess/service/ChessService.java
> +        if (isEnd(chessGameId)) {
그래도 게임이 시작되지 않았으면 삭제가 가능하도록 수정했습니다!

2022-05-01 17:10 UTC, dongho108 commented on src/main/java/chess/dao/ChessGameDao.java
> +        jdbcTemplate.update(sql, password, chessGameId);
```DataAccessException``` 을 언급하신게

1. 쿼리를 실행하다가 오류가 생기는 것을 의미 하신것인가요?
2. 아니면 정말 ```DataAccessException``` 자체를 언급하신 건가요? ```DataAccessException```을 알아보니 jdbc 템플릿이 그냥 sql exception을 한번 포장해서 전해주는 예외라고 해서요!

만약 1번을 언급하신 거라면 런타임 exception이니 예외페이지로 갈 것 같습니다. 방 삭제하다가 예외페이지로 가는 것은 이상하다고 생각되지만 password가 틀릴경우 예외가 발생하진 않고 아무변화도 일어나지 않는 것을 보니 ```DataAccessException``` 이 터지는 것은 정말 DB연결에 심각한 문제가 터진 것이니 예외페이지로 가는게 맞다고 생각이 됩니다.

제가 질문의 의도를 잘못 파악한 걸까요?!

2022-05-04 04:42 UTC, woowahan-neo requested changes
미션 잘 진행해주셨습니다 👍 
소소한 코멘트 남겨두었으니 확인 부탁드릴게요~

2022-05-04 04:42 UTC, woowahan-neo commented on README.md
> +  * [ ] 진행중인 체스방은 삭제할 수 없다.
```suggestion
* [o] 체스방 삭제버튼 클릭시 비밀번호를 입력해 체스게임을 삭제한다.
  * [o] 진행중인 체스방은 삭제할 수 없다.
```

체크를 놓치셨네요~

2022-05-04 04:42 UTC, woowahan-neo commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
```suggestion
    runtimeOnly 'com.h2database:h2'
```

매의 눈 @_@

2022-05-04 04:42 UTC, woowahan-neo commented on src/main/java/chess/dao/ChessGameDao.java
> +        jdbcTemplate.update(sql, password, chessGameId);
제가 기존에 남겼던 코멘트는 아니지만 제 의견도 남겨둘게요~
패스워드가 틀린 상황인지, 존재하지 않는 게임인지 아니면 DB에 문제가 있는 상황인지 등에 대해 별도로 예외처리 하지 않아도 될지 고민해보세요 :)

2022-05-04 04:42 UTC, woowahan-neo commented on src/test/java/chess/service/ChessServiceTest.java
> +}
```suggestion
}

```

EOF를 챙겨주세요~

- 여러 버전의 유닉스 OS간의 공통된 API 및 인터페이스를 정의해놓은 POSIX 명세 중 text file 부분을 보면 유닉스 시스템은 text file들을 서로 구분할때 EOL을 사용하기 때문에 파일을 만들때마다 파일의 끝에 EOL을 넣어주는 것이 안전하다.

2022-05-04 06:18 UTC, dongho108 commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
저것만 tab이어서 인텔리제이에서 안보였네요..;;; ㅎㅎ

2022-05-04 06:19 UTC, dongho108 commented on src/test/java/chess/service/ChessServiceTest.java
> +}
이거 딴 사람꺼는 잘보이는데 제껀 못봤네요..ㅋㅋ

2022-05-04 09:38 UTC, jjj0611 requested changes
안녕하세요 애쉬! 리뷰어제이입니다.

구현해주신 코드 잘 봤습니다!
코멘트 조금 남겨드렸으니 확인 부탁드려요!

이해가지 않는 부분은 코멘트나 DM으로 해주셔도 됩니다 :)

2022-05-04 09:38 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +        chessGameDao.update(chessGame.getState().getTurn(), chessGameId);
엇 단순히 메서드를 묶는 것을 요청드린 것은 아닙니다.
게임이 진행된 뒤에 진행된 게임을 기반으로 db를 갱신하는 것이 아니라
게임이 진행이 잘 되었으니 dao를 요청 받음 값으로 갱신하는 방식에 대해 이야기 드린거에요.
만
어떻게 생각하시나요??

2022-05-04 09:38 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +            ps.setString(3, "white");
게임을 처음 생성하고 생성된 도메인에서 턴을 뽑아서 저장하면 안되나요?
위와 같은 방식을 채택한 이유가 궁금합니다.

2022-05-04 09:38 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +    }
네 page에 대해 고민해주셨네요 :)

모든 데이터를 한 번에 불러오는 것은 언제나 위험할 수 있습니다 :)

2022-05-04 09:38 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +        jdbcTemplate.update(sql, password, chessGameId);
넵 네오의 말에 대한 이야기였습니다.
password와 id가 둘 다 같은 row를 삭제하는 식으로 비밀번호 일치 여부를 확인하게 되면,
DataAccessException이 터졌을 때 패스워드가 일치하지 않은 것인지, 예외가 발생한 상황인지 등 각 상황에 대해 아는 방법이 예외로그를 보고 판단해야하는 문제가 있다고 생각합니다.
어떤 것이 문제가 되는지 케이스를 잘 나누는 것이 중요하다고 생각합니다

2022-05-04 09:38 UTC, jjj0611 commented on src/test/java/chess/dao/ChessGameDaoTest.java
> +@Transactional
`@Transactional` 어노테이션을 사용하기 전에 트랜잭션에 대한 개념을 더 먼저 공부하시면 좋을 것 같아요 :)

2022-05-04 09:38 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +            ps.setString(3, "ready");
게임은 항상 ready 상태로 save되겠네요

2022-05-04 09:38 UTC, jjj0611 commented on src/main/java/chess/dao/ChessGameDao.java
> +        return jdbcTemplate.query(sql, chessGameDtoMapper());
dao에서 data를 가져올 때 dto를 return 하는 이유는 뭘까요??

2022-05-06 03:59 UTC, dongho108 commented on src/main/java/chess/dao/ChessGameDao.java
> +            ps.setString(3, "ready");
전달받은 엔티티의 값으로 세팅해주도록 변경했습니다!!

2022-05-06 04:04 UTC, dongho108 commented on src/main/java/chess/dao/ChessGameDao.java
> +        return jdbcTemplate.query(sql, chessGameDtoMapper());
처음엔 도메인에 id가 포함되어 있지 않아서 id가 포함된 ChessGameDto를 직접 반환해주도록 했었습니다.
그리고 어차피 컨트롤러에 DTO를 반환해줄거여서 DTO를 반환했었습니다.

하지만 DAO는 컨트롤러의 존재도 모르고 DTO의 존재도 모르기 때문에 DTO를 반환해주면 안됩니다.
그래서 List<ChessGame>을 반환하도록 수정했습니다.

2022-05-07 09:04 UTC, jjj0611 approved these changes
안녕하세요 애쉬! 리뷰어 제이입니다!

제출해주신 코드 잘 봤습니다 :)
간단하게만 코멘트 몇 개 더 남겼어요!

다른 것들은 보고 넘어가주셔도 되는 것들인데,
도메인에 도메인 로직이 아닌 것 같은 부분들이 좀 보이네요.

그런 부분만 신경 써서 다음 미션 진행할 때도 같이 녹여서 고민해주세요!

코드는 여기서 머지할게요!
고생하셨습니다!

2022-05-07 09:04 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +        if (chessGame.isProgress()) {
한 메서드의 라인 수가 10줄을 넘어가지 않는다 는 규칙은 더 이상 유효하지 않은 걸까요??

2022-05-07 09:04 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +    public List<PieceDto> getPieces(int chessGameId) {
getPieces와 findChessGame에서
어떤 경우에는 get을 어떤 경우에는 find를 쓴걸까요??

2022-05-07 09:04 UTC, jjj0611 commented on src/main/java/chess/controller/ControllerExceptionHandler.java
> +    public String handleIllegalArgumentException(RedirectAttributes redirectAttributes,
이 핸들러에서만 error log를 찍지 않는 것 같은데
애쉬만의 규칙이 있는걸까요?

2022-05-07 09:04 UTC, jjj0611 commented on src/main/java/chess/controller/SpringController.java
>  @Controller
controller의 이름이 조금 아쉽네요.
Spring을 도입했기 때문에 스프링 컨트롤러일까요?

2022-05-07 09:04 UTC, jjj0611 commented on src/main/java/chess/domain/ChessGame.java
>      public List<String> getSymbols() {
이 부분이 도메인 로직이 맞을까요??

2022-05-07 09:04 UTC, jjj0611 commented on src/main/java/chess/dto/ChessGameDto.java
> +    public int getChessGameId() {
아래에는 더이상 사용하지 않는 메서드도 많이 있네요!
그대로 남겨두신 이유가 있을까요??
이 객체 말고도 사용하지 않는 메서드가 꽤 있어보입니다!

2022-05-07 09:05 UTC, merged