[Spring 체스 - 2단계] 엘리(한해리) 미션 제출합니다.
woowacourse/jwp-chess pull request #440
Opened 2022-04-28 08:15 UTC by RIANAEH

2022-04-29 14:01 UTC, ksy90101 commented on src/main/java/chess/controller/ChessApiController.java
> +        return ResponseEntity.noContent().build();
```suggestion
        return ResponseEntity.noContent()
        .build();
```

2022-04-29 14:11 UTC, ksy90101 requested changes
안녕하세요 엘리 :) 리뷰어 럿고입니다.
2단계 구현하시느라 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니, 확인해주시면 감사하겠습니다.

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/controller/ChessApiController.java
> +    public ResponseEntity<?> deleteRoom(@PathVariable final long id,
Void로 하면 어떨까요?
아울러 어차피 id는 Long으로 관리하게 될텐데, PathVariable도 Long으로 하면 어떨까 의견을 내봐요 :)

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/controller/ChessControllerAdvice.java
> +    @ExceptionHandler({NotExistRoomException.class})
👍

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/controller/ChessWebController.java
> +    @GetMapping("/room/{roomId}")
해당 roomId가 있는지는 체크해야 하지 않을까요?

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/dao/PieceDao.java
> +    public PieceDao(final JdbcTemplate jdbcTemplate, final DataSource dataSource) {
```suggestion
    private final SimpleJdbcInsert insertActor;

    public PieceDao(final JdbcTemplate jdbcTemplate, final DataSource dataSource) {
```

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/dao/PieceDao.java
> +                        ChessPieceMapper.toPieceType(entry.getValue()), entry.getValue().color().getValue()))
entry.getValue().color().getValue()

이 부분이 디미터의 법칙을 위반한거 같은데, 한번 수정해보면 어떨까요?

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/dao/PieceDao.java
> +        final String sql = "select * from pieces where room_id = ?";
이건 제 개인적인 생각인데 SQL 예약어를 대문자로 해놓으면 훨씬 더 보기 좋은거 같아요.

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/dao/PieceDao.java
> +    private RowMapper<PieceEntity> rowMapper() {
공통의 rowMapper는 맨 아래로 내리는게 더 좋더라구요.

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/service/ChessService.java
> +    public List<RoomResponseDto> loadAllRoom() {
조회할때는 @Transaction(readOnly=true)를 쓰는 편이에요.
왜 쓰는지 한번 찾아보면 어떨까요?

2022-04-29 14:11 UTC, ksy90101 commented on src/test/java/chess/dao/RoomDaoTest.java
> +    private RoomDao roomDao;
이것도 Bean인데, @Autowired로 불러오지 않은 이유가 있나요?

2022-04-29 14:11 UTC, ksy90101 commented on src/test/java/chess/service/ChessServiceTest.java
> +@SpringBootTest
Mocking을 사용해서 작성해보면 어떨까요?

2022-04-29 14:11 UTC, ksy90101 commented on src/main/java/chess/entity/RoomEntity.java
> +    private final String password;
한번 Password를 암호화 해보면 어떨까요?

2022-05-01 11:19 UTC, RIANAEH commented on src/main/java/chess/controller/ChessWebController.java
> +    @GetMapping("/room/{roomId}")
ChessService에 roomId를 이용해 방의 존재 여부를 확인하는 checkRoomExist() 메서드를 추가해서 적용했어요!!

### 궁금증
현재 ChessService에는 다음과 같이 각 메서드에서 방의 존재 여부를 확인하고 있어요. 
```java
public void end(final Long roomId) {
        if (!roomDao.isExist(roomId)) {
            throw new NotExistRoomException("방이 존재하지 않아 게임을 종료할 수 없습니다.");
        }

        final ChessGame chessGame = generateGame(roomId);
        chessGame.end();
        roomDao.updateStatusById(roomId, GameStatus.END.getValue());
    }
```
이렇게 방의 존재 여부를 확인하는 로직을 기존처럼 ChessService에 둘지, ChessController에서 ChessService의 checkRoomExist() 메서드를 호출할지 고민이 생기더라구요. 저는 조금 더 구체적인 에러 메시지를 주고 싶어 일단 ChessService에 두는 방향으로 결정했는데, 럿고는 이에 대해 어떻게 생각하시나요?

2022-05-01 11:22 UTC, RIANAEH commented on src/main/java/chess/service/ChessService.java
> +    public List<RoomResponseDto> loadAllRoom() {
@Transactional 어노테이션의 readOnly 속성에 대해 학습하고 필요해보이는 메서드에만 적용해보았어요!!👍

2022-05-01 11:30 UTC, RIANAEH commented on src/test/java/chess/dao/RoomDaoTest.java
> +    private RoomDao roomDao;
저는 DAO를 테스트하는 클래스에서 @JdbcTest 어노테이션을 사용하고 있는데, @JdbcTest 어노테이션을 사용하면 어플리케이션의 모든 빈을 IoC Container에 등록하는 것이 아니라 JDBC 작업과 관련있는 빈만(JdbcTemplate, DataSource 등)을 등록하는 것 같더라구요. 그래서 RoomDao에는 의존성 자동 주입 기능이 적용할 수 없었어요.

@SpringBootTest 어노테이션을 사용하면 RoomDao에도 의존성 자동 주입 기능을 적용할 수 있지만 [럿고가 추천해주신 블로그](https://galid1.tistory.com/772) 를 읽고 나니.. "DAO 테스트에서는 불필요한 빈까지 IoC Container에 등록하지 않는 것이 더 좋지 않을까?"라는 생각이 들어라구요. 그래서 @SpringBootTest 어노테이션을 사용하는 방향으로는 변경하지 않았어요.

럿고는 이에 대해 어떻게 생각하시나요??

2022-05-01 11:41 UTC, RIANAEH commented on src/test/java/chess/service/ChessServiceTest.java
> +@SpringBootTest
[럿고가 추천해주신 블로그](https://galid1.tistory.com/772) 가 많은 도움이 되었어요!! 테스트에 Mocking 기술을 처음 적용해봤는데 뭔가 신기한 기술인것 같더라구요😄

제가 처음에 Mocking을 적용하지 않은 이유는 Service 테스트에서는 "Service가 도메인과 DB의 데이터를 이용해 비즈니스 로직을 잘 수행하는가"를 확인해야한다고 생각했기 때문이었어요. 그런데 해당 블로그에는 "Service 테스트에서 DAO에 대한 의존성을 제거해야한다"고 이야기하더라구요. 솔직히 왜 Service 테스트에서 DAO에 대한 의존성을 제거해야하는지.. 아직 잘 이해가 가지는 않는 것 같아요..ㅎㅎ

그래도 DB에 대한 접근을 제거하고, 불필요한 빈 등록을 제거함으로써 테스트 속도가 빨라진다는 장점은 체감할 수 있었던것같아요👍

2022-05-01 11:53 UTC, RIANAEH commented on src/main/java/chess/entity/RoomEntity.java
> +    private final String password;
저는 "Spring Boot를 사용하고 있는 김에 Spring Security에서 제공하는 암호화 기능을 사용해보면 어떨까?"해서 PasswordEncoder를 이용해 비밀번호 암호화를 적용해봤어요. 

PasswordEncoder 인터페이스는 암호화를 해주는 endcode() 메서드와 원본 비밀번호와 암호화된 비밀번호의 일치 여부를 확인해주는 matches() 메서드를 제공해주더라구요. 암호화 과정에서 어떠한 해시 함수를 사용하는지에 따라 다양한 구현 클래스들이 존재했는데, 저는 그 중 예시 코드에서 많이 사용하는 것 같은 BcryptPasswordEncoder를 사용했어요. (https://www.baeldung.com/spring-security-5-default-password-encoder)

2022-05-01 11:56 UTC, RIANAEH commented
안녕하세요 럿고!!
받은 리뷰 모두 반영해보았고, 궁금한 부분에 대해서는 코멘트로 달아두었어요!! 
꼼꼼히 리뷰해주셔서 너무 감사합니당🙇‍♀️

2022-05-02 23:44 UTC, ksy90101 commented on src/main/java/chess/controller/ChessWebController.java
> +    @GetMapping("/room/{roomId}")
후자로 호출해야 하지 않을까요 :)

2022-05-02 23:45 UTC, ksy90101 commented on src/test/java/chess/dao/RoomDaoTest.java
> +    private RoomDao roomDao;
네 `DAO 테스트에서는 불필요한 빈까지 IoC Container에 등록하지 않는 것이 더 좋지 않을까?` 이게 메인일거 같네요 :)
단위테스트인 만큼 최소한으로 해야 한다고 생각이 들어요 :)

2022-05-03 07:58 UTC, ksy90101 approved these changes
안녕하세요 엘리 :)
2단계도 리뷰 적용하시느라 고생 많으셨습니다 💯 
이만 2단계는 마무리 할게요~ 질문에 대한 답은 코맨트에 남겨두었습니다.
언제든지 추가 질문이 있다면 슬랙을 이용해주세요 :)

2022-05-03 07:58 UTC, merged