[Spring 체스 - 2단계] 코린(유현지) 미션 제출합니다.
woowacourse/jwp-chess pull request #446
Opened 2022-04-28 11:45 UTC by hamcheeseburger

범블비 안녕하세요~~ 2단계로 돌아온 코린입니다.

지난 PR 때 남겨주신 리뷰에 대한 답변과 함께 2단계 PR을 날리게 되었습니다! 잘 부탁드립니다🙇🏻‍♀️  

---
> 제네릭을 사용하신 이유가 있을까요? https://github.com/woowacourse/jwp-chess/pull/357#discussion_r857110874

DB 구조가 바뀔 변경성을 생각하여, interface 구현체에 따라 다른 entity를 사용할 수 있도록 제네릭을 사용하였습니다!

> 웹을 적용하면서 도메인이 꽤나 변경된 것으로 보여요. 
위 요구사항을 달성하기 힘들었는지, 만약 그랬다면 왜 어려웠는지 생각해보시면 좋을 것 같습니다 :) https://github.com/woowacourse/jwp-chess/pull/357#discussion_r857119687

보드의 상태가 DB에 저장되다 보니, `Board` 객체에 기물의 위치를 나타내는 Map<>이라는 상태가 필요없다고 생각했습니다. 그래서 도메인 로직을 서비스에서 처리하는 상황이 발생하였습니다. 

또한 Controller - Service - Dao 라는 구조에 집중하다 보니, 도메인을 활용할 생각을 제대로 하지 못한 것 같습니다. 지금은 Service에서 `Board` 의 주요 로직을 사용하는 상태로 최대한 변경해 보았습니다..!

한 가지 고민인 점이 있는데, 이 부분에 대한 범블비의 생각을 듣고싶습니다.

원래는 `ChessBoard`의 필드를 `Board`로 옮기려고 생각했으나, 불필요하게 `Board`에 필드가 추가된다는 느낌을 받았습니다. `ChessBoard`는 Db와 동일한 필드 구조를 갖는 객체이고, `Board`는 기물의 위치를 가지고 주요 로직을 처리하는 각기 다른 책임을 갖는 객체라고 생각했거든요.

범블비는 `ChessBoard`와 `Board`를 합치는 것이 더 낫다고 생각하시나요?

> 생성자를 통해서 의존성 주입을 받는 경우에 어노테이션 또는 인터페이스가 필요할까요? https://github.com/woowacourse/jwp-chess/pull/357#discussion_r857118865

- annotation
    
    스프링 4.3 부터는, 생성자가 1개인 경우 `@Autowired` 를 사용하지 않아도 된다고 하네요 🙂
    
- interface
    
    필드 타입이 interface일 때 구현체가 1개라면 해당 구현체를 빈으로 생성하여 주입하고, 여러 개라면 필드명과 동일한 구현체를 찾아 빈을 생성하는 것으로 알고 있습니다..
    
    이렇게 되면 특정한 구현체를 필드로 갖게되는 것과 똑같다는 생각이 드네요. BoardDao, MemberDao 등의 interface를 지우는 것이 나을까요?
    

> setter를 사용한 의존성 주입과 생성자를 통한 의존성 주입은 어떤 차이가 있을까요?

생성자 주입은 객체 생성 시점에 주입이 이루어지고, setter 주입은 객체 생성 이후에 주입이 된다는 특징이 있습니다. 

생성자 주입은 객체가 변경될 가능성이 없고 객체 주입에 있어서 강제성이 있습니다. 그에 반면에 setter 주입은 주입받는 객체가 변경될 가능성이 있고 주입의 강제성이 없습니다.

그래서 필드가 null이 될 가능성을 막고 불변을 보장하는 생성자 주입을 자주 사용합니다.👍🏻

2022-04-29 13:50 UTC, ddaaac requested changes
안녕하세요 코린~

질문에 대한 답변들 상세하게 남겨주셔서 어떤 생각을 하고 계신지 파악하기 편했습니다. 감사해요 🙇 

저도 몇 가지 코멘트 남겼으니 확인 부탁드려요.
질문은 DM이나 게더 호출로 편하게 해주세요~

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/controller/ChessAdvice.java
> +    }
예외 핸들링 구현 잘해주셨습니다 👍 
항상 body를 반환하는 예외 핸들러라면 `@RestController`와 마찬가지로 `@RestControllerAdvice`를 사용할 수 있습니다 :)

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/controller/ChessController.java
> +    private String roomView;
`@ Value`를 사용하신 이유가 있을까요?

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/controller/ChessController.java
> +        return new ResponseEntity<>(new GameStatusDto(gameService.isEnd(id)), HttpStatus.OK);
200 상태코드 + body를 반환하고 싶다면 `ResponseEntity<T>` 대신에 `T`를 바로 리턴해도 됩니다.

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/domain/game/Board.java
> +    public Board(final Initializer initializer) {
여기서 pieces를 lazy하게 할당하는 이유가 있을까요?

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/dao/WebChessPieceDao.java
> +    public Piece findByPositionId(int positionId) {
`Optional`을 제거하신 이유가 있을까요?

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/dao/WebChessPieceDao.java
> +    }
위 코멘트에서 Optional -> 예외로 변경하셨는데, 여기서는 예외 -> int 반환으로 변경하셨어요. 어떤 기준으로 리팩토링 해주신건지 궁금합니다!

2022-04-29 13:50 UTC, ddaaac commented on src/test/java/chess/dao/WebPieceDaoTest.java
> +@Sql({"schema.sql"})
어플리케이션이 실행될 때 classpath의 schema.sql이 항상 실행됩니다.
따라서 schema.sql을 resources 폴더 아래로 옮기면 요 `@Sql()`은 필요없어질 것 같네요 😄

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
>      }
> ChessBoard는 Db와 동일한 필드 구조를 갖는 객체이고, Board는 기물의 위치를 가지고 주요 로직을 처리하는 각기 다른 책임을 갖는 객체라고 생각했거든요.
범블비는 ChessBoard와 Board를 합치는 것이 더 낫다고 생각하시나요?

ChessBoard는 객체보다는 DB Entity에 가까운 것 같아요. 로직 없이 순수하게 DB의 테이블과 대응되는 자바 클래스로 보이네요.
반면에 Board는 도메인 객체라고 부를 수 있겠네요.

저라면 BoardDao는 DB Entity인 ChessBoard를 저장하고 조회하도록 하고 여기서는 불러온 ChessBoard로 Board를 만들어서 반환할 것 같습니다.

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/domain/game/Game.java
>      }
`Game` 객체는 더 이상 사용하지 않는 걸까요?

2022-04-29 13:50 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
>          return savedBoard;
> 또한 Controller - Service - Dao 라는 구조에 집중하다 보니, 도메인을 활용할 생각을 제대로 하지 못한 것 같습니다. 지금은 Service에서 Board 의 주요 로직을 사용하는 상태로 최대한 변경해 보았습니다..!

콘솔 때는 `Board`와 `Game` 객체를 활용했는데 지금 두 객체를 보면 그 때는 사용했지만 지금은 사용하지 않는 메서드들이 많은 것 같아요. 이 부분이 View가 콘솔에서 웹으로 바뀌었을 때 코드 변화가 큰 이유입니다. 도메인에 있던 로직들이 지금은 Service, Dao 등 여러 군데로 흩어졌죠.
요구사항을 만족시키기 위해서는 기존에 사용하던 도메인의 로직을 최대한 재활용하는 식으로 구현해야합니다. 이런 경험은 굉장히 중요하기 때문에 시간이 조금 걸리더라도 한 번쯤 시도해보시는 걸 추천드려요!

2022-05-01 16:44 UTC, hamcheeseburger commented on src/main/java/chess/domain/game/Board.java
> +    public Board(final Initializer initializer) {
생성자에서 초기화하고 있는데 lazy로 할당하는 걸까요??

2022-05-01 16:47 UTC, hamcheeseburger commented on src/main/java/chess/controller/ChessController.java
> +    private String roomView;
제가 `@value`를 완전히 오용하고 있었네요..ㅠㅠ

2022-05-02 01:47 UTC, hamcheeseburger commented on src/main/java/chess/dao/WebChessPieceDao.java
> +    public Piece findByPositionId(int positionId) {
`queryForObject`는 결과 값이 없을 때 예외를 발생한다는 것을 알고 `Optional` 키워드를 제거해도 괜찮겠다고 생각했습니다.

그런데 제가 `EmptyResultDataAccessException`에 대해 따로 처리를 하고 있지 않아서 예외가 발생할 경우 500에러가 사용자에게 전달이 되겠더라구요.

그래서 `queryForObject`가 아닌 `query`로 sql을 실행하고 `DataAccessUtils.singleResult` 를 활용해 `Optional`로 반환하도록 변경하였습니다.

2022-05-02 01:49 UTC, hamcheeseburger commented on src/main/java/chess/dao/WebChessPieceDao.java
> +    }
queryForObject가 결과 값이 없을 때 예외를 발생시킨다는 것을 모르고 작성한 코드가 계속 남아있었던 것 같아요 😢
꼼꼼하게 확인하지 못해 죄송합니다.

현재는 해당 메소드를 사용하는 곳이 없어서 삭제한 상태입니다!

2022-05-02 01:58 UTC, hamcheeseburger commented on src/main/java/chess/service/GameService.java
>      }
현재 GameService에서 saveBoard를 실행하면 저장된 보드의 id 값이 담긴 BoardEntity가 반환되게 되는데요,

제가 이렇게 만든 이유는, controller에서 해당 saveBoard를 실행했을 때 저장된 보드의 id 값이 필요하기 때문이었습니다.

하지만 범블비가 말씀하신 대로 saveBoard를 실행했을 때 도메인 객체인 Board를 반환하게 되면 controller에서 저장된 보드의 id 값을 알 수 가 없을 것 같아요😥  또한 saveBoard 실행 이후에 Board가 가지고 있는 로직을 사용할 일 도 없을 것 같구요.

저는 지금처럼 BoardEntity를 반환해서 controller가 필요한 값을 view로 전달하고, Board는 주요 로직이 쓰일 때만 생성해서 활용하는 방식이 좀 더 적합하다고 생각합니다!

2022-05-02 02:06 UTC, hamcheeseburger commented on src/main/java/chess/service/GameService.java
>          return savedBoard;
네.. 맞습니다... 😢  제가 코드를 구현하면서 깊게 생각하는 시간이 짧았던 것 같아요..ㅠㅠ

Service에서 기물의 움직임을 판단하는 로직이 Game 도메인과 중복되는 부분이 많더라구요..! 
Game을 활용해서 기물의 움직임을 판단하고, 예외가 발생하지 않는다면 DB에 값을 변경하는 식으로 적용하였습니다!

지적해주셔서 감사합니다!!

2022-05-02 02:11 UTC, hamcheeseburger commented on src/main/java/chess/domain/pieces/Blank.java
> +public final class Blank implements Type {
범블비 안녕하세요! 범블비의 리뷰를 받고 로직이 조금 변경된 부분이 있어 코멘트 남깁니다.

기물과 위치의 상태를 활용할 때 DB의 의존성을 줄이고자 Blank라는 타입을 추가하게 되었어요.

원래는 새로운 보드가 생성되면 DB의 Piece 테이블에는 32개, Position에는 64개의 레코드가 저장되었는데요.

현재는 Blank 타입을 추가하여 Piece와 Position에 모두 64개의 레코드가 저장되게끔 변경하였습니다.

Blank를 도입하게 된 이유에 대해서는 아래 코멘트를 참고해주시면 감사하겠습니다.

2022-05-02 02:22 UTC, hamcheeseburger commented on src/main/java/chess/service/GameService.java
> +        boardDao.updateTurn(game.getTurn(), roomId);
본래 Blank 타입이 없었던 경우,
positionDao.findAllPositionsAndPieces() 를 실행하면 join 연산자 때문에 32개의 결과값만 반환되었어요. 

이렇게 결과값이 나오게 되면 targetRawPosition의 id값을 알아내기 위해서 또 다른 db query문을 실행하게 되더라구요. 

이러한 부분이 DB의 의존성을 높이는 것 같아, Blank 타입을 추가하여 모든 위치와 기물을 가져올 수 있도록 변경하게 된 것 입니다.

move 로직이 기존보다 변경된 점이 많은 것 같아 코멘트를 남기게 되었습니다!

참고 부탁드리며, 리뷰 또한 잘 부탁드리겠습니다 😊

2022-05-02 09:50 UTC, ddaaac approved these changes
안녕하세요 마루~

리뷰 반영 정말 잘해주셨어요. 짧은 시간 안에 많은 변화를 잘 구현해주셨습니다. 👏 

몇 가지 코멘트 남겼으니 확인해주세요.

이번 PR은 여기서 머지하겠습니다. 남긴 코멘트에 대해서 질문 있으시면 언제든지 편하게 해주세요!

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/controller/ApiController.java
> +        }
```suggestion
        gameService.end(id, password);
```
컨트롤러에 로직을 두면 다른 View에서 이 로직을 재활용할 때 복붙을 해야되는 상황이 발생할 거 같아요 😄 
Game#canDelete 또는 Game#canEnd 정도를 만들어서 서비스에서 체크하면 좋을 것 같습니다.

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/controller/ApiController.java
> +    }
```suggestion
    public void endGame(@PathVariable("roomId") int id, @RequestParam("password") String password) {
        if (!gameService.isEnd(id)) {
            throw new IllegalArgumentException("진행중인 게임은 삭제할 수 없습니다.");
        }
        if (!gameService.end(id, password)) {
            throw new IllegalArgumentException("게임 삭제에 실패하였습니다.");
        }
    }
```
요렇게 해도 같은 동작을 합니다!

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/controller/ChessAdvice.java
> +}
만약 IllegalArguementException 이외의 예외가 발생하면 사용자는 어떤 화면을 보게 될까요?
특별히 정해둔 타입 이외의 예외가 발생했을 때 "요청에 응답할 수 없습니다" 정도의 메세지를 띄워주는 건 어떨까요?

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/domain/game/Board.java
> +        if (wrappedPiece.isPresent() && !wrappedPiece.get().isBlank()) {
```suggestion
        piece(targetPosition).ifPresent(piece -> checkNotBlank(piece));
```
처럼도 쓸 수 있습니다!

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
> +        final BoardEntity board = wrappedBoard.get();
```suggestion
        final BoardEntity board = boardDao.findById(roomId).orElseThrow(() -> new IllegalArgumentException());
```
처럼도 나타낼 수 있어요!

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/dao/WebChessPositionDao.java
> +        Position position = DataAccessUtils.singleResult(jdbcTemplate.query(sql, namedParameters, (rs, rowNum) -> makePosition(rs, "id")));
여기 아래 `saveAll()` 메서드에 남기는 코멘트에요.

시그니처를 `saveAll(boardId, List<Position>)`으로 바꿔야 더 자연스러울 것 같습니다.
지금은 초기화하는 역할까지 Dao가 가져가고 있네요.

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
> +        }
Position에 id가 필요할까요?
Piece가 positionId를 필드로 갖는 대신 직접 Position이라는 값을 내부 필드로 가져도 될 것 같다는 생각이 들어서요.
지금은 로직이 부자연스럽게 느껴지네요.

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/dao/WebChessPositionDao.java
> -    @Override
여기 위에 105~119라인에 남기는 코멘트입니다.
두 개를 join한 결과라서 아마 dto를 따로 만들지 않으신거 같아요. 
제 생각엔 DB와 대응되는 dto를 만드는 편이 가독성이나 안전함을 생각했을 때 더 나을 거 같아요.
코린의 생각은 어떤가요?

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
>          Map<String, Piece> pieces = mapPositionToString(allPositionsAndPieces);
Position -> String 매핑은 View와 관계있어보이는데요, dto에서 하는 게 좀 더 자연스러울 것 같습니다.

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
> +        final BoardEntity board = wrappedBoard.get();
GameService 내의 모든 로직을 `BoardEntity -> Game -> BoardDto`로 통일할 수 있을 거 같아요.
그 과정에서 해당 로직에 불필요한 정보를 가져오기 위해 불필요한 쿼리가 발생할 수도 있겠지만 한 번 작성해보시는 걸 추천드립니다.

지금은 Game에 대한 정보가 여기저기 나뉘어 저장되어 있고, 특정 로직을 실행하기 위해 Game의 어떤 부분 정보가 필요한지 모두 GameService가 알고 있습니다. 
특정 로직을 실행하기 위해 어떤 정보가 필요한지는 Game이 판단하고 GameService는 단순히 여러 정보를 가져와서 Game을 만들어주는 정도로 만들어주면 도메인에 집중된 코드가 나올 것 같네요 😄

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/domain/game/Board.java
> +    public Board(final Initializer initializer) {
파라미터에서 람다로 넘기고 있어서 lazy로 생각했네요. 
그러면 더욱 람다 인터페이스를 받을 필요가 없지 않을까요? 바로 초기화하면 Map<>을 받아도 될 거 같아요.

2022-05-02 09:50 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
>      }
Board가 id를 가지면 해결될 거 같아요! 지금은 save 이후에 특정 로직을 수행하지 않지만 실제로는 save 이후에 로직을 실행하는 경우가 아주 많습니다 :) 
결국 View 단에서 활용되는 값은 board의 id 정도인 것 같은데 id만 리턴하게 바꾸는 것도 괜찮아보여요. DB의 모양이 View까지 노출될 필요는 없어보입니다.

2022-05-02 09:51 UTC, merged

2022-05-06 04:43 UTC, hamcheeseburger commented on src/main/java/chess/dao/WebChessPositionDao.java
> -    @Override
join 했을 때 나오는 필드들로 구성된 dto를 말씀하시는게 맞으실까요??
Piece랑 Position이 도메인이라서 dao에서 바로 맵핑되는게 적절하진 않은 것 같네요!! 
Dto 맵핑으로 변경해보겠습니다!