[Spring 체스 - 2단계] 라쿤(이병훈) 미션 제출합니다.
woowacourse/jwp-chess pull request #451
Opened 2022-04-28 14:22 UTC by nbalance97

안녕하세요 루피😊 1단계에 이어서 2단계도 잘 부탁 드립니다!!

기존 코드에서는 오직 하나의 게임만 제공하도록 설계하였는데 이번에 여러개의 방을 지원하도록 하려고 하니
많은 변경이 필연적으로 발생하게 되었네요😥

바쁜 시간 내어 코드리뷰 해주셔서 감사합니다🙇‍♂️

2022-04-29 08:52 UTC, TheDevLuffy requested changes
안녕하세요 라쿤 ㅎㅎ

서울은 별일 없나요 ! 영국산 리뷰를 드리는 것이 두번째네요.
2단계 요구사항에 대한 내용도 전반적으로 잘 구현해주셨는데요.

코멘트 몇 개 남겨두었으니 확인해보시고 리뷰요청 주세요 !

2022-04-29 08:52 UTC, TheDevLuffy commented on src/main/java/chess/WebChessApplication.java
> -@Controller
제거 해주셨군요 👍

2022-04-29 08:52 UTC, TheDevLuffy commented on src/main/java/chess/controller/WebApiController.java
> +    @GetMapping(path="/{roomNumber}/status", produces = MediaType.APPLICATION_JSON_VALUE)
produces 는 없어도 되지 않나요 ?!

RestController 를 사용하면 제거할 수 있을 것 같아요 !

2022-04-29 08:52 UTC, TheDevLuffy commented on src/main/java/chess/dao/JdbcPieceDao.java
> +        for (Position position : board.keySet()) {
for 문이 실행되는 도중에 어떠한 이유로 중단된다면 문제가 발생할 수 있을 것 같은데요.

어떤 문제가 발생할 수 있을지 고민해보면 좋을 것 같아요 ㅎㅎ

2022-04-29 08:52 UTC, TheDevLuffy commented on src/main/java/chess/dao/RoomDao.java
> +public interface RoomDao {
`체스 게임을 진행할 수 있는 방을 만들어서 동시에 여러 게임이 가능하도록 하기` 요구사항에 해당 내용이 추가된 것으로 보이는데요.

어떻게 보면 해당 내용을 비즈니스 규칙으로 볼 수 있을 것 같아요. 이렇게 봤을 때, Room 과 관련된 도메인 객체는 확인할 수 없는 것 같거든요.
혹시 방을 만든다와 관련하여 어떤 의도로 코드를 작성해주신 것인지 설명해주실 수 있으실까요 ?!
비즈니스 규칙으로 보시지 않으셨을 수 있을 것 같아서요 ㅎㅎ

2022-04-29 08:52 UTC, TheDevLuffy commented on src/main/java/chess/dao/RoomDao.java
> +public interface RoomDao {
관련 내용은 클린아키텍처 19장 정책과 수준 를 참고하시면 도움이 될 수 있을 것 같아요 ㅎㅎ (꼭 안보셔도 됩니다 ! 이런게 있구나 하고 넘어가셔도 되어요 !)

2022-04-29 08:52 UTC, TheDevLuffy commented on src/main/java/chess/WebChessApplication.java
방을 여러개 만들고,

`localhost:8081/2/board` 에서 게임 시작을 누르면 `이미 진행 중인 게임이 있습니다.` 메시지만 노출되고 있어요.

확인 부탁드려요 !

2022-04-30 09:21 UTC, nbalance97 commented on src/main/java/chess/controller/WebApiController.java
> +    @GetMapping(path="/{roomNumber}/status", produces = MediaType.APPLICATION_JSON_VALUE)
해당 부분은 기존 Controller에서 해당 부분을 RestController 어노테이션을 사용하는 WebApiController로 분리하고 
produces를 제거하였습니다😃

2022-04-30 09:31 UTC, nbalance97 commented on src/main/java/chess/dao/RoomDao.java
> +public interface RoomDao {
초기에는 Room 도메인을 만들려고 해 보았는데, Room 도메인에 비즈니스 로직을 넣기가 너무 애매하게 느껴졌습니다😥

방 삭제, 생성, 조회 기능 자체가 데이터베이스에서 행해진다고 생각이 되어서 데이터베이스에서 조회해온 데이터를 화면에 표시하기만 하면 될 거 같아 dto로만 구성하였습니다😅

2022-04-30 14:00 UTC, nbalance97 commented on src/main/java/chess/dao/JdbcPieceDao.java
> +        for (Position position : board.keySet()) {
현재 구조에선 for문이 실행되는 도중에 중단된다면 piece가 부분적으로 저장되는 문제가 발생할 거 같습니다😥

이 부분은 Transaction 어노테이션을 붙여서 문제가 생기는 Rollback하는 방식으로 변경하였습니다!!

2022-04-30 14:39 UTC, nbalance97 commented on src/main/java/chess/WebChessApplication.java
루피의 말을 듣고 흠칫 놀라며 테스트를 해봤습니다😱 

현재 코드에서는 게임 시작 버튼을 누르면 체스판에 말이 로드가 되는데,  체스말이 로드된 이후에 게임 시작 버튼을 다시 누르면 이미 진행 중인 게임이 있다는 메세지가 출력이 되는 상태입니다.😅

저는 똑같이 방을 여러개 만들고 말이 로드되지 않은 상황에서 localhost:8081/2/board에서 게임 시작버튼을 누르면 정상적으로 동작하는 것 같아요😅

2022-04-30 14:48 UTC, nbalance97 commented
안녕하세요 루피😊 영국산 리뷰는 진귀하네요..ㅋㅋㅋㅋㅋㅋ 영상도 잘 봤습니다🤣 

전체적으로 리뷰를 반영하여 보았는데, RoomDao 관련해서는 저도 조금 애매하게 느껴졌습니다😅
도메인으로 추출하려고 시도해 보았는데 비즈니스 로직이 없는 것 같아 Room보단 RoomDto가 맞다고 생각되어서
RoomDto는 존재하지만 Room 클래스를 따로 만들지는 않았습니다! 이러한 방식으로 코드를 작성하면 문제가 될까요..?

진짜진짜 바쁘실텐데 코드 리뷰 남겨주셔서 감사드립니다😎

2022-04-30 22:50 UTC, TheDevLuffy commented on src/main/java/chess/controller/WebApiController.java
> +    @GetMapping(path="/{roomNumber}/status")
`@GetMappring(“/{roomNumber}/status)` 도 가능할 것 같아요

2022-04-30 22:50 UTC, TheDevLuffy commented on src/main/java/chess/service/ChessGameService.java
> +@Transactional(rollbackFor = Exception.class)
클래스 레벨에 트랜잭션을 건다면 해당 클래스가 가지는 모든 퍼블릭 메서드에 적용이 되지만, 각각이 개별적인 전략을 가지기 힘들 수 있을 것 같아요 ㅎㅎ

참고만 해주시고 나중에 적용하실 때 고민해봐주세요 !

2022-04-30 22:50 UTC, TheDevLuffy commented on src/main/java/chess/WebChessApplication.java
제가 환경이 지금 열악해서 실수를 했나봅니다 ㅎㅎ 확인 감사드려요 !

2022-04-30 22:55 UTC, TheDevLuffy approved these changes
라쿤 안녕하세요~

스프링이 처음이라고 하셨는데 잘 학습해주시고 잘 적용해주신 것 같아요 !
Room 의 경우는 생각하기 나름인 것 같아요.
도메인으로 분류한 객체를 하나 더 추가한다면, 비교적으로 Room 과 관련된 요구사항 변경에 대해서 자유로울 수 있을 것 같아요. 반면 코드를 한 벌 더(RoomDao) 작성해야 하는 점은 번거롭고 사람이 실수해서 에러가 발생할 수 있는 포인트가 생길 수 있을 것 같아요.
반면 Room 관련해서 도메인으로 분류한 객체를 추가하지 않는다면 추가했을 때의 장점이 단점이 되고 단점이 장점이 되겠지요 ㅎㅎ
적절하게 판단해서 구현해주시는 것이 가장 중요하다고 생각해서 라쿤의 의견도 괜찮을 것 같아요.

이번 미션도 고생 많으셨고, 앞으로 레벨2 화이팅입니다 !
언제나 DM 은 열려있으니 편하게 메시지 주세요 !

2022-04-30 22:55 UTC, merged

2022-04-30 23:00 UTC, nbalance97 commented on src/main/java/chess/controller/WebApiController.java
> +    @GetMapping(path="/{roomNumber}/status")
path는 생략이 가능하군요😃 공식 문서를 더 찾아보겠습니다!!