[Spring 체스 - 2단계] 짱구(신승철) 미션 제출합니다.
woowacourse/jwp-chess pull request #453
Opened 2022-04-28 15:11 UTC by sc0116

안녕하세요 범블비!
1단계에 이어서 2단계도 잘부탁드립니다!!

2022-04-29 14:48 UTC, ddaaac requested changes
안녕하세요 짱구~

몇 가지 코멘트 남겼으니 확인 부탁드려요.
질문은 DM이나 게더 호출로 편하게 해주세요~

2022-04-29 14:48 UTC, ddaaac commented on src/main/java/chess/dao/game/GameDao.java
> +    void move(final Long gameId, final ChessGame game, final String rawFrom, final String rawTo);
생성에 필요한 dto로 분리해주셨군요!

전 개인적으로 생성 dto를 만들 경우 가장 큰 장점은 id를 non-nullable하게 만들 수 있는 점이라고 생각해요. `Long` -> `long`으로 변경할 수 있지 않을까요?

2022-04-29 14:48 UTC, ddaaac commented on src/main/java/chess/dao/game/SpringJdbcGameDao.java
>      }
https://github.com/woowacourse/jwp-chess/pull/352#discussion_r857080463
이 코멘트에 대한 리뷰가 반영이 되지 않은 것 같아요!

2022-04-29 14:48 UTC, ddaaac commented on src/test/java/chess/dao/MockGameDao.java
> +        Optional<Member> black = mockMemberDao.findById(createGameRequestDto.getBlackId());
https://github.com/woowacourse/jwp-chess/pull/352#discussion_r857073619 
이 코멘트에 대해서 다시 생각해볼까요?
mocking은 언제 사용해야할까요? 테스트하고 싶은 대상을 mocking해도 괜찮을까요?

[Slice test](https://tecoble.techcourse.co.kr/post/2021-05-18-slice-test/)에 대해서도 공부해보면 좋을 것 같습니다 😄

2022-04-29 14:48 UTC, ddaaac commented on src/main/java/chess/dao/member/SpringJdbcMemberDao.java
> +        }
적절한 예외를 캐치해서 원하는 결과로 리턴 👍

2022-04-29 14:48 UTC, ddaaac commented on src/main/java/chess/dao/game/SpringJdbcGameDao.java
>      @Autowired
이전에 남겨드렸던 https://github.com/woowacourse/jwp-chess/pull/352#discussion_r857070270 를 보시면

> As of Spring Framework 4.3, an `@Autowired` annotation on such a constructor is no longer necessary if the target bean defines only one constructor to begin with.

요런 문구가 있습니다. 불필요한 `@Autowired`는 제거해주셔도 될 거 같아요.

2022-04-29 14:48 UTC, ddaaac commented on docker/db/mysql/init/init.sql
>      black_member_id bigint
제 로컬에서는 init.sql이 실행되지 않아서 쿼리가 발생할 때 에러가 나는데요, 혹시 짱구 로컬에서는 잘 되는지 한 번만 확인 부탁드려요!

<img width="693" alt="image" src="https://user-images.githubusercontent.com/43440195/165968256-617e6f63-afb1-41a5-ae58-5910eb73882b.png">

2022-05-02 04:46 UTC, sc0116 commented on docker/db/mysql/init/init.sql
>      black_member_id bigint
앗 저도 처음에 안되길래 docker/db/mysql/data를 아예 지웠다가 다시 실행시키니까 동작했습니다..!!

2022-05-02 05:57 UTC, sc0116 commented on src/main/java/chess/dao/game/SpringJdbcGameDao.java
>      }
앗 이 부분에 대해선 고민이 많았는데요 `ChessGame`을 생성할 때 `white`와 `black`이 필요하기 때문에 내부에서 받아주었습니다..!

2022-05-02 05:58 UTC, sc0116 commented on src/test/java/chess/dao/MockGameDao.java
> +        Optional<Member> black = mockMemberDao.findById(createGameRequestDto.getBlackId());
서비스를 테스트할 때 mocking해야 하는데 지금 저는 mock을 만들고 mock 자체를 테스트하고 있었네요...

2022-05-02 12:51 UTC, ddaaac approved these changes
안녕하세요 짱구!

새로운 기능을 구현할 때 코드의 변화가 거의 없네요 👍 

몇 가지 코멘트 남겼으니 확인해주세요.

이번 PR은 여기서 머지하겠습니다. 남긴 코멘트에 대해서 질문 있으시면 언제든지 편하게 해주세요!

2022-05-02 12:51 UTC, ddaaac commented on src/main/java/chess/controller/spring/GameController.java
>      public ResponseEntity<Long> terminateGame(@PathVariable final Long gameId) {
DeleteMapping을 사용하면 Delete /game/id 로 url을 잡아도 충분히 뜻이 표현될 수 있을 거 같네요.

2022-05-02 12:51 UTC, ddaaac commented on src/main/java/chess/service/GameService.java
> +    public GameService(final GameDao gameDao) {
여기도 https://github.com/woowacourse/jwp-chess/pull/453#discussion_r861864440 이 코멘트가 적용될 수 있을 거 같아요. 불필요한 의존성은 최대한 제거해주세요!

2022-05-02 12:51 UTC, ddaaac commented on src/main/java/chess/domain/ChessGame.java
> +    private final String title;
https://github.com/woowacourse/jwp-chess/pull/453#discussion_r861854685 이 코멘트는 여기 타입이 long으로 바뀌어도 되지 않을까 했던 코멘트였어요. nullable 하지 않다면 boxing 타입을 사용할 필요가 없을 것 같네요.

2022-05-02 12:51 UTC, ddaaac commented on src/test/java/chess/dao/MockGameDao.java
> -package chess.dao;
아예 지우기 보다는 Dao가 잘 작동하는지 확인하는 테스트를 만들어보는 건 어떨까요?

아래 두 가지를 생각하고 테스트를 작성해보시면 좋을 것 같아요
- spring boot는 in-memory db를 지원합니다. 이를 사용해볼까요?
- 현재는 db에 테이블을 직접 생성해줘야하는데요, DDL를 자동으로 실행해주는 [기능](https://leveloper.tistory.com/38)을 활용해봐도 좋을 것 같습니다.

2022-05-02 12:51 UTC, ddaaac commented on src/main/java/chess/dao/game/SpringJdbcGameDao.java
> +            statement.setLong(5, memberDao.findById(createGameRequestDto.getBlackId()).get().getId());
Optional<>에 대해서 값 체크 없이 get()을 해서 사용하시는 부분이 많습니다. 이 때 값이 없으면 NoSuchElementException이 발생하는데, Optional을 사용하는 의미가 없어집니다. 값이 있는지 여부를 꼭 확인해주세요.
매번 확인하는게 귀찮다면 `memberDao.getById()` 등의 네이밍으로 Member가 없을 경우에는 특정한 예외를 발생시키도록 하고 Member를 반환하는 메서드를 만들어도 좋을 거 같아요.

2022-05-02 12:51 UTC, ddaaac commented on src/main/java/chess/dao/game/SpringJdbcGameDao.java
>      }
네네 어떤 과정을 통해서 여기서 다른 Dao를 활용했는지는 알겠습니다!
그렇다고해서 단일책임원칙을 깨는게 옳다는 생각이 들지는 않네요. 또, 앞의 쿼리의 결과로 RowMapping 과정에서 쿼리문이 발생했을 때 어떤 사이드이펙트가 있을지도 고려해봐야할 거구요.
제 생각엔 DB의 table에 매핑되는 ChessGameEntity라는 dto를 만들어서 가져오고, Piece와 Member는 RowMapper가 아닌 곳에서 합쳐주는 게 조금 더 좋아보이네요. 짱구의 생각은 어떠신가요?

2022-05-02 12:52 UTC, merged