[Spring 체스 - 2단계] 배카라(박성우) 미션 제출합니다.
woowacourse/jwp-chess pull request #457
Opened 2022-04-29 05:21 UTC by seong-wooo

# 안녕하세요

2단계 미션에서도 스프링에 대해서 많이 공부하고싶었는데, 자바 스크립트에 대부분의 시간을 쏟은 것 같습니다.. 

아는 게 없어서 어떤 것을 질문해야할 지 모르겠습니다 ㅠ 

저를 혼내주세요.

2022-04-29 11:13 UTC, Laterality requested changes
안녕하세요 배카라.

2단계도 빨리 해주셨네요!

간단한 피드백을 먼저 남겨드렸어요. 확인 부탁드려요 :)

2022-04-29 11:13 UTC, Laterality commented on src/main/java/chess/controller/SpringChessGameController.java
> +        return "index";
뷰를 렌더링하는 컨트롤러와 API 처리를 하는 컨트롤러는 분리해보면 어떨까요?

2022-04-29 11:13 UTC, Laterality commented on src/main/java/chess/dao/GameDao.java
> +    void endGame(int roomId);
두 메서드는 DAO의 책임에 부합하는 기능일까요?

2022-04-29 11:13 UTC, Laterality commented on src/main/java/chess/dao/JdbcGameDao.java
> +        final String sql = "insert into game(roomId, state) values(?, 'run')";
쿼리는 상수로 분리해보면 어떨까요?

2022-04-29 11:13 UTC, Laterality commented on src/test/java/chess/dao/GameDaoTest.java
> +        jdbcTemplate.execute("CREATE TABLE game\n"
테이블 스키마가 바뀌면 이 부분도 변경돼야 할까요?

2022-04-29 11:13 UTC, Laterality commented on src/test/java/chess/dao/RoomDaoTest.java
> +
불필요한 빈 줄은 제거하면 어떨까요?

2022-04-29 11:54 UTC, seong-wooo commented on src/main/java/chess/controller/SpringChessGameController.java
> +        return "index";
분리했습니다 !

2022-04-30 09:43 UTC, seong-wooo commented on src/test/java/chess/dao/RoomDaoTest.java
> +
제거했습니다.

2022-04-30 12:17 UTC, seong-wooo commented on src/test/java/chess/dao/GameDaoTest.java
> +        jdbcTemplate.execute("CREATE TABLE game\n"
@Sql 애너테이션을 사용하는 구조로 변경하였습니다 !

2022-04-30 13:08 UTC, seong-wooo commented on src/main/java/chess/dao/GameDao.java
> +    void endGame(int roomId);
insert 기능과 update 기능을 분리해보았습니다 !

2022-04-30 13:09 UTC, seong-wooo commented on src/main/java/chess/dao/JdbcGameDao.java
> +        final String sql = "insert into game(roomId, state) values(?, 'run')";
중복되는 쿼리는 상수로 분리해보았습니다. 그런데 ` final String sql = "insert into game(roomId, state) values(?, 'run')";` 이 쿼리도 상수로 분리를 해야하는 이유에 대해서는 잘 모르겠습니다. !

2022-04-30 13:47 UTC, Laterality requested changes
안녕하세요 배카라.

잘 수정해주셨어요 👍 

몇가지 피드백을 추가로 남겨드렸어요. 확인 부탁드립니다.

군데군데 포맷이 맞지 않는 부분들(불필요한 빈 줄, 파일 끝에 빈 줄 없음)이 있는데 한번 정리해주시면 좋겠어요 :)

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/dao/JdbcGameDao.java
> +        final String sql = "insert into game(roomId, state) values(?, 'run')";
1. 쿼리를 상수로 분리하면 어떤 이점이 있을까요?
2. 말씀하신 쿼리도 상수로 분리하면 이러한 이점을 누릴 수 있을까요?

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/SpringChessApplication.java
>  @Controller
이 어노테이션이 여기에도 필요할까요?

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/controller/ChessApiController.java
> +    public ResponseEntity<ChessMap> loadRoom(@PathVariable("roomId") int roomId) {
반환 타입이 `ResponseEntity`인 경우에도 `@ResponseBody` 어노테이션이 필요할까요?

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/controller/ChessApiController.java
> +
여백으로 사용하는 빈 줄은 한 줄씩만 사용하면 어떨까요?

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/dao/GameDao.java
> +public interface GameDao {
이 인터페이스를 구현하는 입장에서는 인터페이스의 선언만 보고 어떤 기능을 구현해야 하는지 이해할 수 있을까요?

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/dao/JdbcTurnDao.java
> +    private final JdbcTemplate jdbcTemplate;
`JdbcRoomDao`는 클래스 본문을 한 줄 비우고 시작하는데 이 클래스는 그렇지 않네요. 클래스의 작성 방식을 통일하면 어떨까요?

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/dao/JdbcTurnDao.java
> +        jdbcTemplate.update(sql, Team.WHITE.getName(), roomId, Team.BLACK.getName());
이 로직은 DAO의 책임에 부합할까요?

2022-04-30 13:47 UTC, Laterality commented on src/main/java/chess/dao/JdbcTurnDao.java
> +        final String sql = "update turn set team = 'WHITE' where roomId = ?";
마찬가지로 DAO가 `team` 칼럼의 초깃값이 `WHITE`라는 점을 알 필요가 있을까요?

2022-04-30 13:47 UTC, Laterality commented on src/test/java/chess/dao/RoomDaoTest.java
> +
여기 빈 줄도 제거하면 어떨까요?

2022-04-30 13:58 UTC, seong-wooo commented on src/test/java/chess/dao/RoomDaoTest.java
> +
제거했습니다 !

2022-04-30 13:59 UTC, seong-wooo commented on src/main/java/chess/controller/ChessApiController.java
> +
한 줄만 사용하도록 변경하였습니다 !

2022-04-30 14:05 UTC, seong-wooo commented on src/main/java/chess/SpringChessApplication.java
>  @Controller
@Controller 는 삭제하였습니다!

2022-04-30 14:18 UTC, seong-wooo commented on src/main/java/chess/controller/ChessApiController.java
> +    public ResponseEntity<ChessMap> loadRoom(@PathVariable("roomId") int roomId) {
`ResponseEntit`에서 객체를 json 형태로 바꿔주므로 굳이 `@ResponseBody`를 작성할 필요가 없네요 !

2022-04-30 14:38 UTC, seong-wooo commented on src/main/java/chess/dao/JdbcTurnDao.java
> +    private final JdbcTemplate jdbcTemplate;
한 줄을 띄우고 시작하는 것으로 통일하였습니다 !

2022-04-30 15:53 UTC, seong-wooo commented on src/main/java/chess/dao/JdbcTurnDao.java
> +        jdbcTemplate.update(sql, Team.WHITE.getName(), roomId, Team.BLACK.getName());
dao안에는 sql을 실행하는 로직만 존재하도록 변경하였습니다 !

2022-04-30 16:02 UTC, seong-wooo commented on src/main/java/chess/dao/JdbcTurnDao.java
> +        final String sql = "update turn set team = 'WHITE' where roomId = ?";
서비스 클래스에서 초깃값을 매개변수로 전달하는 형태로 변경하였습니다 !

2022-04-30 16:25 UTC, seong-wooo commented on src/main/java/chess/dao/GameDao.java
> +public interface GameDao {
dao 내부의 메서드들의 역할을 잘 알 수  있도록 이름을 변경하였습니다 !

2022-05-01 08:12 UTC, Laterality requested changes
안녕하세요 배카라.

빠르게 수정해주셨네요.

몇가지 코멘트를 추가로 남겨드렸어요. 확인 부탁드려요 :)

2022-05-01 08:12 UTC, Laterality commented on src/main/java/chess/controller/ChessApiController.java
> +        return ResponseEntity.ok(chessService.initializeGame(roomId));
게임을 초기화하는 동작은 GET 메서드로 처리하기에 적절할까요?

2022-05-01 08:12 UTC, Laterality commented on src/main/java/chess/controller/ChessApiController.java
> +    @GetMapping("/chessMap/{roomId}")
위에서는 `make-piece` 형태로 path를 사용하는데 여기는 `chessMap` 형태네요. URL 형식을 통일하면 어떨까요?

2022-05-01 08:12 UTC, Laterality commented on src/main/java/chess/controller/ChessApiController.java
> +    public ResponseEntity<String> hasTwoKing(@PathVariable("roomId") int roomId) {
HTTP 메서드와 URL 만으로 어떤 요청을 처리하는지 알 수 있을까요?

2022-05-01 08:12 UTC, Laterality commented on src/main/java/chess/dao/JdbcRoomDao.java
> +    private final RowMapper<RoomDto> actorRowMapper = (resultSet, rowNum) -> {
변수명의 `actor`는 무엇을 의미하는 걸까요?

2022-05-01 08:12 UTC, Laterality commented on src/main/java/chess/service/ChessService.java
> +    public boolean hasTwoKing(int roomId) {
살아있는 킹의 개수로 게임의 진행중 여부를 판별하는 것으로 보이는데, 클라이언트가 이 점을 알 필요가 있을까요?

2022-05-01 08:25 UTC, seong-wooo commented on src/main/java/chess/controller/ChessApiController.java
> +        return ResponseEntity.ok(chessService.initializeGame(roomId));
게임을 초기화하는 동작은 기존에 존재하던 값을 수정하는 것이므로 PATCH 메서드로 변경하였습니다 !

2022-05-01 08:28 UTC, seong-wooo commented on src/main/java/chess/controller/ChessApiController.java
> +    @GetMapping("/chessMap/{roomId}")
둘 다 chessMap을 반환하기 때문에 chessMap 형태로 통일하였습니다 !

2022-05-01 08:57 UTC, seong-wooo commented on src/main/java/chess/dao/JdbcRoomDao.java
> +    private final RowMapper<RoomDto> actorRowMapper = (resultSet, rowNum) -> {
roomRowMapper로 변경하였습니다 !

2022-05-01 09:52 UTC, seong-wooo commented on src/main/java/chess/controller/ChessApiController.java
> +    public ResponseEntity<String> hasTwoKing(@PathVariable("roomId") int roomId) {
필요하지않은 api라고 생각이 되어 삭제하였습니다!

2022-05-01 09:52 UTC, seong-wooo commented on src/main/java/chess/service/ChessService.java
> +    public boolean hasTwoKing(int roomId) {
필요하지않은 api라고 생각이 되어 삭제하였습니다!

2022-05-02 00:10 UTC, Laterality approved these changes
안녕하세요 배카라.

잘 수정해주셨네요 👍 

이번 미션은 이만 머지하도록 할게요.

수고 많으셨습니다. 다음 미션도 화이팅하세요 :)

2022-05-02 00:10 UTC, Laterality commented on src/main/java/chess/service/ChessService.java
> +    public boolean hasTwoKing(int roomId) {
서비스에는 메서드가 남아있는 것 같은데, 확인 부탁드려요~

2022-05-02 00:10 UTC, Laterality commented on src/main/java/chess/dto/RoomDto.java
> +    }
테스트에서만 쓰이는 생성자네요.

2022-05-02 00:10 UTC, Laterality commented on src/main/java/chess/dto/RoomDto.java
> +    }
DAO에서 이 생성자를 사용하는 것으로 보이는데요. 일부 필드를 빈 값으로 초기화한다는 것은 DAO에서 불필요한 필드까지 사용하고 있다는 의미일까요? 그렇다면 DAO에서 이 DTO를 사용하는 것이 바람직할까요?

2022-05-02 00:10 UTC, merged