[Spring 체스 - 2단계] 야호(최지연) 미션 제출합니다.
woowacourse/jwp-chess pull request #459
Opened 2022-04-29 07:42 UTC by pup-paw

안녕하세요 희봉!! 2단계로 돌아온 야호입니다 😆

기능을 추가하다 보니 에러가 여기 저기에서 터져서 수정하다보니 제출이 많이 늦어졌네요..!
기능 구현을 완료한 후에도 리팩터링 하고 싶은 부분들이 많이 보여 고치다가 이대로는 리뷰를 못받겠다는 생각에 일단 PR 보냅니다 ..ㅜ0ㅜ

가장 마지막으로 진행한 리팩터링은 controller 의 역할을 덜어내는 것이었는데요, 도메인 로직을 줄이기 위해 controller 내의 domain 과 관련된 import 를 줄인다는 생각으로 진행해 보았습니다!
그러고 나니 controller 는 많이 가벼워진 것 같지만, service 가 무거워 진 것 같아 service 도 리팩터링 해보고 싶습니다..!!

가장 먼저 생각나는 부분은 loadGame 과 loadSavedGame 이 따로 작성되어 있는데, 한번에 합치는 작업을 하면 좋을 것 같다는 생각이 드네요 :)

이번에도 리뷰 잘 부탁드려요 ❤️

2022-04-30 09:49 UTC, heebong requested changes
안녕하세요, 야호! 리뷰어 희봉입니다 😄 
요구사항을 잘 구현해주셨네요. 어려웠을텐데 고생하셨어요. 
추가로 생각해볼 내용들을 코멘트로 남겼습니다. 확인 부탁드려요. 언제든 궁금한 내용이 생기면 DM 아시죠? 😉

2022-04-30 09:49 UTC, heebong commented on build.gradle
> +//    implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
logback을 주석처리 한 이유가 무엇일까요? 🤔

2022-04-30 09:49 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +            pieceDao.findByGameID(gameID);
아이디를 ID로 표기하는 이유가 있을까요? 카멜케이스와 맞지 않는 것 같아서요 🙂

2022-04-30 09:49 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +        return new ChessGame(new SavedBoardGenerator(pieceDao.findByGameID(chessGameDto.getGameID())),
한 줄에 굉장히 많은 함수 호출이 들어있네요. 가독성이 괜찮은가요? 👀

2022-04-30 09:49 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +    private GameResult getGameResult() {
`get`이 맞을지 의문입니다. 🤔  함수 내용으로 보면 `Board`를 새로 생성하는거라 `create`이 의미적으로 더 맞아보여요.
`get`의 의미를 한번 생각해보면 좋겠습니다. 🙂

2022-04-30 09:49 UTC, heebong commented on src/main/java/chess/controller/ReadyController.java
> +    @PostMapping("/")
`POST / ` 가 리소스를 삭제하는 URL로 적절할까요? 🤔

2022-04-30 09:49 UTC, heebong commented on src/main/java/chess/controller/ReadyController.java
> +    public String delete(@ModelAttribute ChessGameDto chessGameDto, Model model) {
`api`와 `controller`의 위치에 대해 생각해봅시다. 현재 야호가 `controller`를 나눈 기준은 `return` 값으로 보여져요. 때문에 `return`이 `ready`인 `delete api`도 `ReadyController`에 위치하는것 같고요.
하지만 화면에 따라 api를 배치하는게 맞을까요? 만약 `delete api` 호출 후 `ready` 페이지가 아니라 다른 페이지를 반환해야한다면, `delete api` 위치가 다른 `controller`로 옮겨져야합니다. 현재 의미적으로도 `delete`가 `ReadyController`에 있는게 맞지 않아보이고요. controller끼리 분리하는 기준이 무엇일지 생각해보면 좋겠습니다 🙂

2022-04-30 09:49 UTC, heebong commented on src/main/java/chess/controller/InGameController.java
> +    @PostMapping()
아무 값이 없다면 `()`가 없어도 됩니다. 😄

2022-04-30 09:49 UTC, heebong commented on src/main/java/chess/controller/InGameController.java
> +    public String movePiece(@ModelAttribute ChessGameDto chessGameDto, @ModelAttribute MovementRequest movement,
`move` 호출 시 `password`가 틀려도 정상적으로 동작하네요. 요구사항이 아니니 구현하지 않아도 상관 없습니다. 다만 야호가 의도한 것인지 궁금해서요 🙂

2022-05-02 04:46 UTC, pup-paw commented on src/main/java/chess/service/ChessService.java
> +        return new ChessGame(new SavedBoardGenerator(pieceDao.findByGameID(chessGameDto.getGameID())),
앗.. 그러게요..! 가독성을 높이는 방향으로 수정해보겠습니다 :)

2022-05-02 04:47 UTC, pup-paw commented on src/main/java/chess/service/ChessService.java
> +    private GameResult getGameResult() {
넵! 함수 내용을 명시적으로 표현하는 이름으로 변경해보겠습니다 :)

2022-05-02 04:50 UTC, pup-paw commented on src/main/java/chess/controller/InGameController.java
> +    @PostMapping()
앗 그렇군요!! 감사합니다 ☺️

2022-05-02 05:05 UTC, pup-paw commented on build.gradle
> +//    implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
logback을 사용하지 않는 것이 에러 메세지를 찾기 더 쉬워서 주석처리 했습니다!
logback을 사용하면 제가 생각하지 못한 이점을 얻을 수 있나요??

2022-05-03 07:43 UTC, heebong approved these changes
안녕하세요, 야호! 리뷰어 희봉입니다 😄 
피드백을 잘 반영해주셨어요 👍 스프링 프레임워크와 웹 개발로 쉽지 않았을텐데 잘 적용해주셨습니다.
이번 미션은 여기서 머지하도록 할게요.
추가로 생각해보면 좋은 내용들을 코멘트로 남겼어요. 확인 부탁드립니다. 이번미션 고생하셨어요~
(궁금한 내용이 생기면 언제든 DM 아시죠? 😉 )

2022-05-03 07:43 UTC, heebong commented on build.gradle
> +//    implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
혹시 로그가 남는걸 확인해보셨을까요? logback 설정이 되어있으면 요청/응답이 로그로 남아서 확인하기 용이합니다 😄 이미 알고있다면 상관없어요~

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/controller/ChessController.java
> +    @PostMapping("/delete/{gameId}")
`DeleteMapping`을 사용하는게 더 좋습니다 🙂

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/db/ChessGameDao.java
> +    public boolean findPasswordByGameId(String gameId, String password) {
`find`는 `boolean`을 반환하는 프리픽스로 적절하지 않은 것 같네요 🙂

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +            double whiteScore = getSavedGameResult(gameId).calculateScore(Color.WHITE);
`getSavedGameResult()` 리턴값을 변수로 담아놓으면 쿼리가 두번 날아가지 않겠네요

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +            double whiteScore = getSavedGameResult(gameId).calculateScore(Color.WHITE);
advanced 🆙 여기서 `catch`로 잡지 말고, `gameId`에 해당하는 `piece`가 있는지 확인하고 진행해도 좋을 것 같아요.
`try-catch`는 가독성이 떨어지기때문에 정말 예외상황이 아니라면 지양하는게 좋답니다. 다음 과제들을 진행하면서 고민해봐도 좋을 것 같아요 🙂 
advanced 🆙 (곧 배우게될) `CrudRepository` [인터페이스](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html)를 보면 `findBy~` 함수의 리턴값은 `Optional`이에요. 조회된 값이 없다면 `Optional.empty`가 나옵니다. 이런식으로 풀어낼 수도 있어요. 다른 서비스에서는 어떻게 풀었는지 확인해보는것도 좋은 힌트가 될 것 같아요~

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/db/PieceDao.java
> +    public Map<Square, Piece> findByGameId(String gameId) {
advanced 🆙  db와 도메인의 관계는 무엇일지, db에 무엇을 저장해야할지 고민해보면 좋겠습니다. 🙂  `PieceDao`의 `findByGameId()`를 보면 `gameId`를 가지고 `Piece`를 조회할 것 같아요. 하지만 해당 함수의 리턴값은 `Board`, 즉 `Map<Square, Piece>`에요. 도메인과 db에 저장되는 형식이 달라서 생긴 이슈로 보이는데요, 이런 부분에 대해 고민해보는 것도 좋을 것 같습니다 😄

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/controller/ChessController.java
> +    public String runGame(@RequestParam String gameId, @RequestParam String password,
advanced 🆙  `json` 데이터를 응답으로 보내는 것도 고려해보면 좋겠습니다. 물론 `form` 태그를 사용하지 못하고 `js` 작업이 더 필요하겠지만, `model`로 하는 것과 `json`을 리턴하는 것의 차이가 무엇일지 고민해보면 좋겠습니다. 😄

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/db/ChessGameDao.java
> +    private final JdbcTemplate jdbcTemplate;
advanced 🆙 jdbcTemplate을 왜 쓰는걸까요?
이번 미션의 주 내용은 spring으로 전환 및 jdbcTemplate 사용이라고 생각해요. 때문에 왜 jdbcTemplate을 사용하는지 정리하고 가면 좋을 것 같습니다.
스파크에서 사용했던 것처럼, DriveManager로 Connection을 직접 만들어서 사용하지 않는 이유는 무엇일까요? 🤔 
우선 
1. jdbcTemplate이 어디서 bean으로 등록되는지 찾아보고
2. DataSource와 jdbcTemplate의 차이점이 무엇인지
3. 왜 Connection을 직접 관리하지 않고 DataSource를 사용하는지

알아보면 기초를 다지는데 도움이 될 것 같아요 😄 

hint 1 🖊️ 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/21075774/166217620-3028eeb9-60f4-48a2-bbe9-af8328eaf307.png">
DI 받는 곳에서 버튼을 클릭하면 빈이 선언된 곳을 갈 수 있어요!

hint 2 🖊️ 
책 [자바 웹 개발 워크북] `5.12 DB 커넥션풀 5.13 DataSource와 JNDI` 읽어보기 (이제 교육장 출근하면 책 빌려읽을 수 있을거에요 🙂 )

2022-05-03 07:43 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +    public void movePiece(String gameId, MovementRequest movementRequest) {
advanced 🆙 `service`에서 `controller`에서 사용하는 `MovementRequest`를 사용하네요. 만약 스파크, 스프링, 콘솔을 제공해야한다면 `ChessService`를 재사용할 수 있을까요? 🙂 이런 관점에서 고민해보는 것도 좋습니다. 
(밑에 `ScoreResponse`를 리턴하는 것도 비슷한 문제를 가지고있죠~)

2022-05-03 07:44 UTC, merged