[Spring 체스 - 2단계] 렉스(오성원) 미션 제출합니다.
woowacourse/jwp-chess pull request #461
Opened 2022-04-29 09:00 UTC by Seongwon97

2022-04-29 14:21 UTC, ksy90101 requested changes
안녕하세요 :) 렉스
2단계도 잘 구현해주셨네요 💯 
간단한 피드백을 남겼으니, 한번 확인해주시면 감사하겠습니다!

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/controller/GameController.java
> +    @PostMapping("/game/create")
Post라는 Method가 이미 create라는 의미를 내포하고 있어요.
REST API naming convention을 한번 찾아보시면 어떨까요?

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/controller/GameController.java
> +    public ResponseEntity deleteGame(@RequestBody RemoveRoomDto removeRoomDto) {
<Void>로 제네릭 타입을 지정하면 될거 같아요!

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/controller/GameController.java
> +        long roomId = (long) session.getAttribute("roomId");
세션을 쓰신 이유가 무엇일까요?

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/controller/ViewController.java
> +    public String moveGameRoom(@PathVariable Long roomId, HttpSession session) {
해당 room이 존재하는지 체크해야 하지 않을까요?

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/dao/PieceDao.java
> +        final String sql = "insert into piece (position, name, team, room_id) values (?, ?, ?, ?)";
개인적으로 SQL 예약어는 대문자로 사용하는게 더 가독성이 높은거 같아요.

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/dao/PieceDao.java
> +    public void saveAllPieces(final Player player, final long roomId) {
일반적으로 save라는 단어는 insert와 update가 둘다 될때 사용하는거 같아요.
지금같은 케이스에서는 insert라는 단어가 더 잘 어울릴거 같네요.

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/dto/RoomInfoDto.java
> +    private final long id;
id를 Long으로 하기 시작햇다면 쓸데없는 캐스팅이 되지 않도록 통일하면 어떨까요?

2022-04-29 14:21 UTC, ksy90101 commented on src/main/java/chess/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler {
👍

2022-04-29 14:21 UTC, ksy90101 commented on src/test/java/chess/dao/RoomDaoTest.java
> +@SpringBootTest
@jdbcTest를 사용하는게 좋을거 같아요.
한번 찾아보시고, 왜 이걸 사용하는게 좋을지 한번 찾아보시면 좋을거 같습니다 :)

2022-04-29 14:25 UTC, ksy90101 commented
1. DB 테이블 데이터들의 id값 관리
네 최대값에 도달하게 되었다면 그때 또 방법을 찾는게 맞다고 생각이 듭니다.
43억개의 데이터가 들어온 순간, 그때는 또 다른 방법을 고민해봐야 하지 않을까 합니다 :)
실무에서도 일단 bigint로 해놓는 편이에요!

2. 게임 생성 후 페이지의 이동
사실 이부분은 프론트에서 제어를 해야 할거 같아요.
아울러 왜 2번의 요청이 일어나는게 잘못되었다고 생각하는지도 궁금하네요.
REST API라면 몇번의 요청은 있는게 자연스러워서요 ㅎㅎ

2022-04-30 07:35 UTC, Seongwon97 commented on src/main/java/chess/controller/GameController.java
> +    public ResponseEntity deleteGame(@RequestBody RemoveRoomDto removeRoomDto) {
로 타입의 ResponseEntity를 비한정적 와일드카드를 가진 ResponseEntity<?>로 변경했습니다!

<?>를 사용한 이유는 Delete의 경우 body의 값이 없는 noContent를 던져줘야하기에 null이 아닌 값이 들어올 수 없는 <?>를 사용했습니다.

2022-04-30 07:54 UTC, Seongwon97 commented on src/main/java/chess/dao/PieceDao.java
> +        final String sql = "insert into piece (position, name, team, room_id) values (?, ?, ?, ?)";
가독성 향상을 위해 피드백을 반영하여 변경했습니다😁

2022-04-30 07:57 UTC, Seongwon97 commented on src/main/java/chess/dao/PieceDao.java
> +    public void saveAllPieces(final Player player, final long roomId) {
럿고의 말대로 save는 `새로운 데이터를 저장`, `기존 데이터를 업데이트하여 저장`의 두가지 의미로 해석될 수 있을 것 같네요

피드백을 반영하여 save를 insert로 변경했습니다!

2022-04-30 08:40 UTC, Seongwon97 commented on src/main/java/chess/controller/ViewController.java
> +    public String moveGameRoom(@PathVariable Long roomId, HttpSession session) {
피드백을 반영하여 roomId를 통한 DB데이터가 존재하는지 체크 후, 방이 존재하지 않을 시에는 잘못된 URL이라는 메시지를 출력하도록 수정했습니다.

2022-04-30 08:48 UTC, Seongwon97 commented on src/main/java/chess/dto/RoomInfoDto.java
> +    private final long id;
`ResultSet`의 `getLong`의 반환값이 Long이 아닌 long이라서 모두 long타입을 사용하도록 변경했습니다!

<img width="648" alt="image" src="https://user-images.githubusercontent.com/57744251/166098734-64925484-a669-431a-81a6-ac0361b1164c.png">

2022-04-30 09:26 UTC, Seongwon97 commented on src/main/java/chess/controller/GameController.java
> +        long roomId = (long) session.getAttribute("roomId");
> ## 게임 생성 후 페이지의 이동
> 해당 내용은 이번 미션을 하며 가장 고민하고 시간을 많이 투자한 부분입니다..
> 게임 생성 버튼을 클릭하면, 게임 생성 후 생성된 게임의 정보를 이용해 게임 페이지로 이동을 하여야하는데 이러한 경우 어떤 방법으로 구현을 하는 것이 올바른 방법인지 모르겠습니다🥲
> 현재는 게임 생성 버튼을 클릭할 경우 post매핑을 통해 게임 생성-> get매핑을 통한 game페이지로 이동-> js onload메서드에서 get매핑을 통한 게임 정보 로드 및 말 생성의 순서로 구현을 하였으나, 게임 방으로 이동하는 과정에 2번의 request가 발생하여 올바른 방법이 아닌 것 같다 생각됩니다.(페이지 이동 후 말 정보를 로딩할때 게임의 id를 이용하기 위해 session을 이용하기까지 했습니다🤯)

해당 내용을 고민하면서 방 생성과 동시에 게임방으로 접속하는 기능을 고민하면서 세션을 사용하게 되었습니다.
방 생성 후, id를 통한  `/game/{roomId}` url로 get request를 보내면 말들의 정보와 view까지 한번의 request로 반환을 하고 싶었으나 해당 방법을 찾지 못하여 "view페이지로의 이동 + view페이지에서 말 정보 요청을 통한 말들 배치"를 하는 방법을 구현하게 되었습니다.

"view페이지로의 이동 + view페이지에서 말 정보 요청을 통한 말들 배치"을 구현하는데에는 3가지 방법을 생각해봤습니다.
1. 페이지 이동을 할 때 Js 단에서 roomId를 넘겨 `/game/load/{roomId}` get request를 통해 말을 가져오는 방법
2. 페이지 이동 후, js단에서 url을 파싱하여 roomId를 추출한 후 다시 request를 하여 말을 가져오는 방법
3. 뷰를 반환하는 `/game/{roomId}` get request를 할 때, 세션을 저장하고 그 후에 말 정보를 가져오는 `/game/load`에서 세션에 저장된 방 정보를 통해 말을 가져오는 방법

위의 3가지 방법을 생각해봤으나 맨 세션을 사용하는 방법이 가장 깔끔할 것 같아서 사용해봤습니다😭

2022-04-30 18:43 UTC, Seongwon97 commented on src/main/java/chess/controller/GameController.java
> +        long roomId = (long) session.getAttribute("roomId");
REST API를 학습해보니 REST API의 특징으로 상태 정보를 따로 저장하지 않고 들어오는 요청을 단순히 처리해주는 Stateless특징이 있는 것을 확인했습니다ㅠㅠ 역시 세션을 사용하는 방법은 좋지 않은 방법이었네요😭

Model을 사용하는 방법을 찾아 위의 고민도 해결하고 세션 사용도 삭제했습니다!!

2022-04-30 19:07 UTC, Seongwon97 commented on src/main/java/chess/controller/GameController.java
> +    @PostMapping("/game/create")
NHN Cloud에 올라온 [REST API 제대로 알고 사용하기](https://meetup.toast.com/posts/92) 게시글을 보며 제가 설계한 url들과 아래 피드백을 주신 Session을 사용한 방법이 REST API를 생성하는 것에는 올바르지 못한 방법임을 알게 되었습니다...

아래 피드백을 주신 Session 사용은 삭제하였으며, URL의 네이밍도 최대한 변경해봤습니다!! (Url네이밍도..역시 어렵네요)

2022-04-30 19:23 UTC, Seongwon97 commented
안녕하세요 럿고👋🏻
보내주신 피드백들을 반영하여 다시 PR을 보냅니다!!

피드백을 반영하면서 이전에 고민하였던 페이지 이동 관련 내용을 수정했습니다.
2단계 PR을 보내기 전에 미션을 수행하면서 Model의 사용도 시도했으나 잘 안되어서 이전과 같은 방법을 사용했는데 여러 시도끝에 해결을 했습니다.  (Handlebars Template에서는 model값을 읽어올 떄 `${}`이 아닌 `{{}}`를 사용한다는 것을 알기까지 수 일이 걸렸네요😭)
해당 내용을 해결하니 api 주소들도 정리가 되었고, Session 사용도 삭제할 수 있었습니다.

시간내서 리뷰해주셔서 감사합니다🙇🏻‍♂️

2022-04-30 19:23 UTC, Seongwon97 commented
게임 생성 후 페이지의 이동
사실 이부분은 프론트에서 제어를 해야 할거 같아요.
아울러 왜 2번의 요청이 일어나는게 잘못되었다고 생각하는지도 궁금하네요.
REST API라면 몇번의 요청은 있는게 자연스러워서요 ㅎㅎ

> **Re:** 2번의 요청이 좋지 못하다 생각한 이유는 체스 게임방을 이동할 때, 한 번의 요청으로 페이지 이동 및 말들을 불러오는 것이 가능한데 해당 요청을 두번으로 나누어서 요청을 하여 낭비??가 있다고 생각했습니다. 사용자가 많은 서비스의 경우, 한번에 수행할 수 있는 요청을 두번, 세번으로 나누어 보내도록 설계되면 서버의 과부하가 오지 않을까라는 생각을 하였던것 같습니다.

2022-04-30 19:29 UTC, Seongwon97 commented on src/main/java/chess/controller/ViewController.java
> +    @GetMapping("/game/create")
방을 생성하는 페이지로 이동하는 url의 경우, 다음과 같이 create라는 단어가 들어가서 페이지 이동이 아닌 "게임을 생성한다"라는 느낌을 주는 api라고 생각이듭니다..

아무리 생각해도 괜찮은 네이밍이 떠오르지 않는데..혹시 더 괜찮은 네이밍이 없을까요..?
럿고의 의견을 듣고 싶습니다🙏🏻

2022-05-01 05:48 UTC, ksy90101 commented on src/main/java/chess/controller/GameController.java
> +    public ResponseEntity deleteGame(@RequestBody RemoveRoomDto removeRoomDto) {
헉 \<Void\> 로 하면 된다고 이야기한건데 짤렸네요 ㅠㅠ

2022-05-01 05:54 UTC, ksy90101 commented on src/main/java/chess/controller/ViewController.java
> +    @GetMapping("/game/create")
아,,, 단순히 view를 랜더하는거군요 ㅎㅎ
이런 경우에는 그냥 create나 new라는 단어를 써서 하긴 해요 :) (프론트 입장에서요!)

2022-05-01 06:31 UTC, ksy90101 requested changes
렉스 안녕하세요 :) 리뷰어 럿고입니다.
피드백 적용하시느라 고생많으셨습니다 💯 
보다보니 Transaction에 대한 처리가 없어서, 해당 부분도 한번 해보시면 어떨까 해서, 리뷰를 좀 더 남겼어요.
언제든지 질문은 환영입니다 :)

2022-05-01 06:31 UTC, ksy90101 commented on src/main/java/chess/dao/PieceDao.java
> +        final String SQL = "insert into piece (position, name, team, room_id) values (?, ?, ?, ?)";
개인적으로 SQL 예약어는 대문자로 작성하는게 가독성이 높다고 생각이 들어요 :)

2022-05-01 06:31 UTC, ksy90101 commented on src/main/java/chess/controller/ViewController.java
> +        session.removeAttribute("roomId");
아직 session이 남아잇네요 :)

2022-05-01 06:31 UTC, ksy90101 commented on src/main/java/chess/dto/RemoveRoomDto.java
> +public class RemoveRoomDto {
Dto에서 입력값에 Validate도 하는 편이에요 :)
이건 참고만 해주세요 :) 서비스에 들어오기 전에 Dto에서 걸러진다면 더 성능상에서도 좋지 않을까요!?

2022-05-01 06:31 UTC, ksy90101 commented on src/main/java/chess/service/ChessGameService.java
>  public class ChessGameService {
지금보니깐,  @Transaction에 대한 처리가 없네요 :) 
관련해서 처리 해볼까요!?

2022-05-01 16:44 UTC, Seongwon97 commented on src/main/java/chess/controller/ViewController.java
> +        session.removeAttribute("roomId");
남아있던 세션 사용을 완전히 제거하였습니다😁

2022-05-02 05:24 UTC, Seongwon97 commented on src/main/java/chess/service/ChessGameService.java
>  public class ChessGameService {
트랜잭션 처리도 추가했습니다!!
트랜잭션 옵션에서도 isolation, propagation, noRollbackFor, timout 등의 많은 속성이 있는 것을 확인하였으나, 현재는 미션에서는 readOnly옵션만 추가해봤습니다!

2022-05-02 05:31 UTC, Seongwon97 commented
안녕하세요 럿고
남아있던 세션 사용의 제거와 트랜잭션 처리를 추가했습니다. 

스프링 공부 초기 단계라 그런가 공부할 내용이 넘쳐나네요ㅠㅠ

좋은 피드백들을 남겨주셔서 감사합니다🙇🏻‍♂️

2022-05-04 02:54 UTC, ksy90101 approved these changes
안녕하세요 렉스 :)
체스 미션 하느라 너무 고생 많으셨습니다 💯 
체스 미션은 이만 머지할게요~
언제든지 질문이 있다면 슬랙으로 연락주세요.

2022-05-04 02:54 UTC, merged