[Spring 체스 - 2단계] 수달(허수진) 미션 제출합니다.
woowacourse/jwp-chess pull request #462
Opened 2022-04-29 10:26 UTC by her0807

2022-05-02 01:13 UTC, KIMSIYOUNG requested changes
안녕하세요 수달! 
2단계 미션도 잘 구현해주셨네요🙂 몇가지 코멘트 남겼는데 확인 부탁드려요!
1단계 미션에 대한 대댓글은 1단계에 추가해두겠습니다.
궁금하신 내용은 언제나 편하게 말씀해주세요🙂

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/controller/ChessControllerAdvice.java
> +@ControllerAdvice
전역으로 예외처리를 잘 해주셨네요👏 조금 더 나아가서, 어플리케이션에서 발생하는 예외가 `Runtime`만 있을까요? 예상하지 못한 에러들에 대해서도 같이 처리해주면 좋을 것 같아요.

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/controller/ChessSpringController.java
> +    public ResponseEntity start(@PathVariable int id) {
꼭 필요한 건 아니지만, 저는 명시적으로 `ResponseEntity<GameStatusDto>`라고 선언해주는 걸 선호해요! 메소드 시그니처만 보고 어떤 값을 리턴할지 확인할 수 있으면 좋은 것 같아요🙂

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/controller/ChessSpringController.java
> +    public ResponseEntity list() {
방 기능을 잘 구현해주셨네요🙂 조금 더 나아가서, 컨트롤러도 역할 분리를 해보면 어떨까요? 

체스게임의 흐름을 담당하는 역할과, 방에 대한 흐름을 담당하는 컨트롤러로 분리해보면 좋을 것 같아요.

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/controller/ChessSpringController.java
> +    @PostMapping("/rooms/move")
데이터를 수정하는 것에 조금 더 적절한 HTTP 메소드는 없을까요?

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/ChessGameService.java
> +        this.roomDao = roomDao;
수달은 서비스라는 레이어의 역할을 무엇이라 정의하나요?🙂 컨트롤러와 서비스 각각의 역할범위를 어떻게 정의하고 있나요?

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/ChessGameService.java
> +        gameStatusDao.create(GameStatus.READY, roomId);
만약에 방과, 턴까지 생성하였는데 보드를 생성하는 과정에서 DB저장이 실패하게 되는 경우 어떻게 될까요? 

이들은 모두 하나로 묶여서 모두 성공하거나 실패해야하는 로직으로 보여요! @Transactional이라는 어노테이션을 키워드로 조금 더 학습해볼까요?

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/controller/ChessSpringController.java
> +    @PostMapping("/rooms/move")
조금 더 나아가서 만약 클라이언트가 From과 To에 Null을 입력하게 되는 경우 어떻게 처리되나요?

이런 부분에 대한 Validation 기능을 스프링에선 제공하고 있어요! RequestBody Validation이라는 키워드로 검색해서 조금 더 학습해보면 좋을 것 같아요.

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/dto/RoomResponseDto.java
> +    private String id;
아이디값을 클라이언트로 받을 때는 `int`를 사용하고 반환할 때는 `String`을 사용하는 이유가 있을까요? 

추가로 아이디값은 어떤 타입으로 관리하는 것이 적절할지 고민해보면 좋을 것 같아요.

2022-05-02 01:13 UTC, KIMSIYOUNG commented on README.md
> +## 2단계
변경되는 요구사항에 따라 문서를 잘 변경해주셨네요👏

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/ChessGameService.java
> +    private final RoomDao roomDao;
체스게임서비스가 꽤 무겁다고 느껴지지 않나요?🙂 

조금 더 역할을 나눠보면 어떨까요?

2022-05-02 01:13 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/ChessGameService.java
> +    public ChessGameService(BoardDao boardDao, TurnDao turnDao, GameStatusDao gameStatusDao,
생성자주입으로 잘 변경해주셨네요🙂

2022-05-02 07:22 UTC, her0807 commented on src/main/java/chess/controller/ChessControllerAdvice.java
> +@ControllerAdvice
우선 `Exception` 으로 묶어서 처리한 뒤, 에러 처리에 관하여 추가학습을 하여 리팩토링 해보겠습니다.

2022-05-02 07:31 UTC, her0807 commented on src/main/java/chess/controller/ChessSpringController.java
> +    public ResponseEntity start(@PathVariable int id) {
가독성을 위해서 변경해보겠습니다!

2022-05-02 08:09 UTC, her0807 commented on src/main/java/chess/controller/ChessSpringController.java
> +    public ResponseEntity list() {
변경해보도록 하겠습니다! ㅎㅎ

2022-05-02 09:27 UTC, her0807 commented on src/main/java/chess/domain/ChessGameService.java
> +    private final RoomDao roomDao;
RoomService 를 만들어서 나눠보겠습니다!

2022-05-02 09:30 UTC, her0807 commented on src/main/java/chess/dto/RoomResponseDto.java
> +    private String id;
이 부분은 조금 더 고민해보겠습니다!

2022-05-02 09:33 UTC, her0807 commented on src/main/java/chess/domain/ChessGameService.java
> +        this.roomDao = roomDao;
## 서비스
service 는 도메인 간 협력하여 비지니스 로직을 만들어야 할 경우, 비지니스 로직을 담당하는 역할을 한다고 생각합니다! 


## 컨트롤러
view 와 model(domain) 계층의 중간 역할이 controller 라고 생각합니다. 
쉽게 말하면 비지니스로직은 포함되지 않고, 비지니스 로직을 가지고 있는 도메인을 실행시켜 뷰에 원하는 데이터를 전달하는?!
그런 역할이 컨트롤러 같습니다.

2022-05-02 09:34 UTC, her0807 commented
오늘이 마감 기한이라서, 정신없이 리뷰 반영을 먼저 했습니다. (추가 학습이 필요할 것 같습니다) 
오늘 저녁에 추가로 학습하여 반영해두도록 하겠습니다. 카일 좋은 위로와 리뷰 너무 너무 감사합니다. 😄

2022-05-03 13:02 UTC, KIMSIYOUNG commented on src/main/java/chess/controller/ChessControllerAdvice.java
> +@ControllerAdvice
네네! 시스템내에서 발생할 수 있는 에러도 다양하고, 각 에러별로 어떤 상태값을 사용할지 어떤 메시지를 사용할지도 조금씩 달라지기 때문에 다음에 기회가 된다면 더 세부적으로 분리해보면 좋을 것 같아요🙂

2022-05-03 13:14 UTC, KIMSIYOUNG approved these changes
안녕하세요 수달! 
리뷰 잘 반영해주셨네요🙂 
이번 미션은 여기서 머지하면 좋을 것 같아요.
조금 더 고민해보면 좋을 것들 몇가지 남겼으니 확인해보시고 천천히 말씀해주세요!
고생 많으셨습니다 다음 미션도 화이팅입니다!

2022-05-03 13:14 UTC, KIMSIYOUNG commented on src/main/java/chess/dto/MoveDto.java
> +import org.jetbrains.annotations.NotNull;
요거 정상동작하나요? 저는 스프링벨리데이션을 의미한거였는데 나중에 확인해보고 알려주세요🙂

2022-05-03 13:14 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/ChessGameService.java
> +        this.roomDao = roomDao;
네네! 그러면 비즈니스 로직은 서비스에 있어야하는건가요? 컨트롤러에서 말하는 `비즈니스 로직을 가지고 있는 도메인을 실행시켜`라는 것이 서비스를 호출하는건가요? 요 부분에 대해서는 편하게 디엠으로 같이 얘기해봐요!

2022-05-03 13:14 UTC, KIMSIYOUNG commented on src/main/java/chess/domain/RoomService.java
> +@Transactional(readOnly = true)
트랜잭션에 대해서는 천천히 조금 더 학습해보면 좋을 것 같아요🙂

현재는 이 부분에 대한 테스트가 없고 테스트를 만들어도 정상동작하는데요! 

테스트환경을 H2가 아닌  mysql을 사용하는 것으로 변경하면 동작하지 않을거에요. 나중에 조금 더 학습해봐요!

2022-05-03 13:14 UTC, KIMSIYOUNG commented on src/main/java/chess/dto/RoomResponseDto.java
> +    private String id;
네네! 스프링과, 숫자타입에 대해서 먼저 고민해보시면 좋을 것 같고 스트링이라면 어떤 값을 그리고 숫자라면 어떤 타입(int, long, Integer, Long)이 적절할지 고민해보면 좋을 것 같아요.

2022-05-03 13:14 UTC, merged

2022-05-07 03:22 UTC, her0807 commented on src/main/java/chess/dto/MoveDto.java
> +import org.jetbrains.annotations.NotNull;
이 부분은 import 가 잘못들어간 것 같습니다. ㅠㅠㅠ