[Spring 체스 - 2단계] 이프(송인봉) 미션 제출합니다.
woowacourse/jwp-chess pull request #471
Opened 2022-04-29 22:09 UTC by sinb57

던!! 안녕하세요~😆 2단계 PR 요청드려요!!

체스방 제목&비밀번호 설정 및 체스방 삭제 기능 구현 과정은 크게 어렵지 않았어요.

대신 기능 구현 외적인 부분에서 리팩토링에 신경을 많이 썼어요.
[Repository-Dao 관계] [계층간 Dto 분리 및 DtoAssembler 도입]

미션 마감이 며칠 남지 않았지만, 피드백 주시면 남은 기간 동안 열심히 반영하겠습니다!!

2022-04-30 13:41 UTC, gch01410 requested changes
안녕하세요 이프!
2단계도 깔끔하게 구현해주셨네요! 👍 
피드백 남겼으니 확인부탁드릴게요~

2022-04-30 13:41 UTC, ghost commented on src/test/java/chess/repository/ChessRepositoryTest.java
> +        final Game game = chessRepository.save(Game.initializeGame("title", "password"));
sql 파일에는 테이블 생성 같은 DDL뿐 아니라 DML도 입력해서 테스트 코드가 실행될때마다 테이블에 데이터를 채워넣을 수 있어요!
더미 데이터를 셋팅해준다면 테스트 코드에서 매번 데이터를 insert하는 과정을 없앨 수 있겠어요!

2022-04-30 13:41 UTC, ghost commented on src/main/java/chess/service/ChessService.java
> +        chessRepository.remove(gameId);
실제 서비스라고 생각해보면 비밀번호 일치여부를 먼저 확인해야하지 않을까요~?
게임삭제 유효성 검사는 그 다음이 아닐까해요

2022-04-30 13:41 UTC, ghost commented on src/main/java/chess/repository/ChessRepository.java
> +        return saveGame(game, savePlayers(game.getPlayers()));
저는 다른곳에서 재사용하지 않는 메서드로 너무 작게 쪼개놓으면 오히려 가독성이 안좋아질 수 있다고 생각하는데요.
이프는 어떻게 생각하시나요?

2022-04-30 13:41 UTC, gch01410 commented on src/main/java/chess/controller/ChessController.java
> +    }
이 API에서 데이터를 수정하는 작업이 있네요!
적절한 http method로 변경해보아요!

2022-04-30 13:41 UTC, gch01410 commented on src/main/java/chess/service/ChessService.java
> +            throw new IllegalArgumentException("비밀번호가 일치하지 않습니다.");
커스텀 예외를 사용할때와 비교해서 `IllegalStateException` 같은 자바의 기본예외를 사용할때 단점이 어떤게 있을까요~?
그리고 `@ExceptionHandler, @ControllerAdvice` 를 사용해서 커스텀 예외를 처리하면 어떤점이 좋은지도 같이 고민해보면 좋을 것 같아요!

2022-04-30 13:41 UTC, gch01410 commented on src/main/java/chess/service/ChessService.java
> +public class ChessService {
`ChessService`에 대한 테스트 코드도 있어야할 것 같아요!

2022-04-30 13:41 UTC, gch01410 commented on src/main/java/chess/repository/ChessRepository.java
> +    }
Assembler를 이용해서 dto 변환을 깔끔하게 처리하셨네요! 👍

2022-05-02 05:26 UTC, sinb57 commented on src/main/java/chess/controller/ChessController.java
> +    }
removeGame의 경우 DeleteMapping으로 변경했고, endGame의 경우 PostMapping으로 변경했습니다!

2022-05-02 05:32 UTC, sinb57 commented on src/main/java/chess/repository/ChessRepository.java
> +        return saveGame(game, savePlayers(game.getPlayers()));
SRP에 따라 클래스를 설계하듯이, 메서드도 하나의 일을 수행하도록 작성해야 한다고 생각해요.
ChessRepository를 보시면 2개의 Dao (GameDao와 PlayerDao)를 이용해 public 메서드를 제공하고 있음을 볼 수 있어요.
public 메서드를 수행하기 위해 2개의 Dao 로직이 수행되는데, 이를 그저 하나의 public 메서드에 묶어 놓는다면
Dao 마다 존재하는 각기다른 변경점에 쉽게 대처하지 못할 것이라 판단했어요.
그에 반해 지금의 코드에서는 `GameDao에 대해 saveGame, findStatuses, updateGame 등`,
`PlayerDao에 대해 savePlayers, findPlayerById, updatePlayers 등` 각 Dao에 따른 private 메서드가 분리되어 있기 때문에
변경점에 쉽게 대처할 수 있어요.

2022-05-02 05:34 UTC, sinb57 commented on src/test/java/chess/repository/ChessRepositoryTest.java
> +        final Game game = chessRepository.save(Game.initializeGame("title", "password"));
말씀하신대로 test/resources/data.sql 을 통해 DML를 작성하고 테스트를 진행해봤는데, DML과 테스트 코드가 강하게 결합되어 있어서 추후에 변경할 때 신경써야 할 부분이 늘어난 것 같아요.ㅠ

어쩔수 없는 부분인지, 혹은 테스트코드를 잘못 작성하고 있는지 궁금합니다

2022-05-02 05:36 UTC, sinb57 commented on src/main/java/chess/service/ChessService.java
> +        chessRepository.remove(gameId);
`비밀번호 일치여부`와 `게임종료 여부`의 우선순위가 동일하다고 생각했는데,
사용자 입장에서는 `비밀번호 일치여부`가 우선시되는 것이 좋다고 생각되네요.

`게임종료 여부`를 우선시했다면, 차라리 UI에서 종료 버튼을 제공하지 않는 편이 좋았겠네요.

2022-05-02 08:57 UTC, sinb57 commented on src/main/java/chess/service/ChessService.java
> +            throw new IllegalArgumentException("비밀번호가 일치하지 않습니다.");
커스텀 예외를 사용하면 표준예외에 비해 좀더 상세한 정보를 담아낼 수 있고,
동일한 예외을 `디버깅` / `사용자에게 보여주기` 목적에 따라 분리할 수도 있으리라 생각해요.

하지만 지난 lv1 기간동안 여러 미션에서 커스텀 예외를 사용해보면서 단점을 크게 느꼈어서,
아직은 커스텀 예외 사용에 대해 조심스러운 상태입니다.

초기에는 exception 클래스명에서 보다 확실한 의미를 나타낼 수 있다는 점이나
assertThatThrownBy 테스트에서 isInstanceOf 를 통해 특정 Exception의 발생 여부를 확인할 수 있다는 점,
그리고 하나의 패키지에서 모든 Exception을 관리할 수 있다는 점 등에서
이점이 있다는 판단으로 커스텀 예외를 사용해왔어요.

하지만 lv1이 진행될수록 도메인이 복잡해지고 그에 따라 커스텀 Exception 클래스의 개수는 늘어나고 이를 관리하기가 버거워지더라고요.  그래서 패키징을 통해 커스텀 Exception 클래스를 분리하기도 해보고 커스텀 Exception 클래스를 상속을 통해 계층형으로 관리해보기도 했으며, 하나의 커스텀 Exception 클래스를 대표로 두고 메시지로 구분짓기 위해 Enum으로 예외메시지만 관리하기도 하는 등 여러 시도를 해봤지만, 결국 유지보수만 저하시키고 별다른 장점을 얻지 못했습니다.
(https://prolog.techcourse.co.kr/studylogs/1902)
(https://github.com/woowacourse-study/2022-back-end-code-review-study/blob/main/[Mission2]%20로또%20미션/[로또%20미션]%20이프%20최종%20리뷰%20정리/Enum%20클래스를%20통한%20상수%20문자열%20관리.md)

그래서 아직은 커스텀 예외 사용에 대해 잘 모르겠습니다.ㅜ

2022-05-04 07:31 UTC, gch01410 commented on src/test/java/chess/repository/ChessRepositoryTest.java
> +        final Game game = chessRepository.save(Game.initializeGame("title", "password"));
sql파일을 이용해서 테스트 코드 작성을 할 수 있다라는것을 알려드리기 위해 피드백을 드렸어요!
항상 좋은 방법은 아니고 상황에 맞춰서 잘 이용하면 될 것 같아요.

dml과 테스트 코드가 결합되어있는건 어쩔 수 없는 부분이라고 생각이 듭니다. dml과 의존되어있다는게 결국 테이블 구조와 의존되어있는건데, 테이블 구조랑은 당연히 강하게 결합될 수 밖에 없는게 아닌가하네요.

2022-05-04 07:41 UTC, gch01410 commented on src/main/java/chess/repository/ChessRepository.java
> +        return saveGame(game, savePlayers(game.getPlayers()));
이프의 의견에 동의해요
추가로 변경점에 대비하기 위해 어느 수준까지 메서드를 쪼개면 좋을지도 고민해보면 좋겠어요.
`아직 일어나지 않은 변경은 변경이 아니다.` 라는 말도 있어요!
유연한 설계는 변경하기 쉽고 확장하기 쉬운 구조를 만들지만 단점도 있어요.
단순함과 명확함을 버리게 될 가능성이 높아서 복잡한 설계가 될 가능성이 높아요.
`어떤 변경에 대비하기 위해 설계를 복잡하게 만들었는지?`  `정말 유연성이 필요한지?` 에 대해서 충분한 고민이 필요합니다.

2022-05-04 07:45 UTC, gch01410 commented on src/main/java/chess/service/ChessService.java
> +            throw new IllegalArgumentException("비밀번호가 일치하지 않습니다.");
이프가 생각한 장점이 맞습니다!
지금까지 구현했던 프로그램들에서는 예외를 상세하게 처리할 것까지 없어서 그렇게 느끼셨을 것 같아요.
프로그램이 복잡해지면서  예외마다 다르게 처리해야할 필요성은 커져갈꺼라서 미리 학습한다는 차원에서 커스텀 예외를 계속 적용하시면 좋을 것 같아요.

2022-05-04 07:47 UTC, gch01410 approved these changes
안녕하세요 이프!
코멘트 남겼으니 다음 미션 진행하시면서 같이 고민해보면 좋을 것 같아요.
체스 구현하시느라 고생많으셨습니다!

2022-05-04 07:47 UTC, merged