[Spring 체스 - 2단계] 레넌(조형래) 미션 제출합니다.
woowacourse/jwp-chess pull request #473
Opened 2022-04-30 05:45 UTC by brorae

안녕하세요, 스티치!
2단계도 리뷰 잘 부탁드리겠습니다!
1단계에서 피드백해주신 부분들을 통해 모두 생성자 주입 방식으로 의존성을 주입하도록 수정하였습니다. 그리고 테스트 코드 내에서 스키마를 실행하는 것을 schema.sql을 따로 만들어 실행해주도록 수정하였습니다. 
감사합니다.

2022-05-01 04:17 UTC, lxxjn0 requested changes
레넌, 2단계 미션 잘 봤습니다 👍🏼 

앞서 전달드린 피드백들은 잘 반영해주셨네요!! 이번에 조금 더 확인해보면 좋을 점들에 대해서 간단히 피드백 남겨보았습니다!! 한번 확인하고 반영해주세요 :)

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/controller/WebController.java
> +    }
selectGame 메서드에서 Model을 주입받는 식으로 처리해 보는 것은 어떨까요?? 아니면 해당 방법이 아닌 ModelAndView 객체를 사용한 이유가 있을까요??

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/controller/WebController.java
> +    public ModelAndView insertGame(RoomDto roomDto) {
해당 controller 메서드가 처리하는 요청은 새로운 게임을 생성하는 요청으로 보여져요!! 새로운 리소스를 생성할 때 사용하는 Http Method는 POST 입니다. 아래 글을 한번 참고해보면 좋을 것 같아요 :)

[Http Method 란? (GET, POST, PUT, DELETE)](https://velog.io/@yh20studio/CS-Http-Method-%EB%9E%80-GET-POST-PUT-DELETE)

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/controller/WebController.java
> +        chessService.insertGame(roomDto, new ChessBoard(new NormalPiecesGenerator()));
service의 해당 메서드의 경우 사용되는 곳들을 보니 새로운 game을 만들 때 사용하는 메서드로 보여요!! 메서드의 행위와 목적 자체가 새로운 게임을 생성하는 것이기 때문에 board도 아마 매번 초기 보드 세팅일 것으로 예상되고요.
그렇다면 controller에서 초기화할 board를 전달해주는 것은 조금 어색해 보입니다! 해당 메서드의 역할에서 불필요한 파라미터로 보이는데 혹시 이렇게 작성하신 이유가 있을까요?

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/controller/WebController.java
> +        chessService.updateBoard(gameId, moveDto.getFrom(), moveDto.getTo());
해당 메서드들의 경우에도 실제로 chess의 이동이라는 행위를 처리하는 메서드라고 생각돼요! 

만약 방의 이름을 입력할 수 있고 그 이름을 변경하는 경우 상태를 명시적으로 변경하는 것 같아서 update라는 이름도 적절한 것 같은데, 해당 메서드의 경우 내부에서 체스의 이동이라는 해당 도메인에서 중요한 행위를 하는 만큼 메서드에도 그러한 행위를 표현해주면 코드를 읽는 사람의 입장에서 더 이해하기 좋을 것 같아요!!

레넌의 생각은 어떤가요??

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/controller/WebController.java
> +        chessService.endGame(gameId);
위에서 `updateBoard` 에 남긴 피드백을 해당 메서드의 이름과 비교하면 더 이해하기 쉬울 것 같아요!! 

해당 메서드의 경우 Game의 상태를 종료 상태로 변경하는 것으로 보여집니다. 그렇다면 마찬가지로 여기서도 `updateGame` 와 같은 이름을 쓸 수도 있었겠지만 endGame을 사용함으로써 하고자 하는 행위가 명시적으로 드러나서 전 더 좋았던 것 같아요!!

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/dao/FakeBoardDao.java
> +public class FakeBoardDao implements BoardDao {
BoardDao를 인터페이스로 정의하고 해당 객체를 만들어서 테스트에서 db에 의존적이지 않은 테스트가 가능했겠네요!! 👍🏼 
해당 클래스의 경우 테스트에서만 사용하기 때문에 테스트 패키지 하위로 이동시키는 것이 더 좋을 것 같아요!! 프로덕션 패키지 (여기서의 src/main) 하위에는 실제 프로덕션 코드를 실행하는 데 필요한 클래스들만 위치하는 것이 좋아요 :)

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/dto/BoardDto.java
> +    public ChessBoard toEntity() {
해당 메서드를 확인해보니 FakeBoardDao, 즉 테스트에서 사용되는 메서드를 위한 메서드로 보여요!! 테스트만을 위한 메서드라면 다른 방식으로 해결해 보는 것은 어떨까요?? 프로덕션 코드는 최대한 테스트 코드에 의존받지 않는 코드들로 위치하면 좋을 것 같아요!!

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +        int id = gameDao.save(roomDto.getTitle(), roomDto.getPassword(), chessGame.getState().toString());
해당 라인에서 `chessGame.getState().toString()` 로직을 확인했는데 State의 toString 메서드에서 클래스 이름을 반환하는 것으로 보여요!! toString의 경우 해당 객체의 상태를 출력하는 데 사용되는 메서드입니다! 그래서 최대한 해당 목적 이외의 사용은 좋지 않다고 생각해요!!

만약 클래스의 이름이 필요하다면 `chessGame.getState().getClass().getSimpleName()` 과 같은 클래스 제공 기본 메서드를 활용하는 것도 방법이 될 수 있을 것 같아요!! 

하지만 상수가 아닌 클래스의 이름을 DB 에 저장하고 관리하는 것이 변경에 유연하지 못할 것 같아요!! 만약 해당 클래스의 이름이 변경되면 실제 비즈니스 로직에도 직접적인 영향을 끼치는 거라서 조금 위험할 수도 있을 것 같아요!! 그래서 이런 경우 상수인 enum이나 또는 직접 정의한 상수를 많이 사용하는 것 같아요!! 이런 부분에 대해서는 레넌도 한번 생각해보면 좋을 것 같아요!! 👍🏼

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +    }
title은 dto가 가지고 있는 값이네요!! 그럼 getter로 가져와서 유효성을 검증하기 보다는 dto에게 메시지를 보내보면 어떨까요?

2022-05-01 04:17 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +        return new StatusDto(scores.get(Color.WHITE), scores.get(Color.BLACK));
StatusDto가 가지는 값이 white의 점수와 black의 점수만 가진다면 StatusDto에게 scores를 넘겨주고 내부에서 색상 별로 값을 뽑아내는 것도 좋을 것 같아요!! 외부에 내부의 로직이나 상태를 노출하지 않고도 처리가 가능할 것으로 보여져요!!

2022-05-01 08:30 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +    }
Model을 주입 받는 방식과 ModelAndVIew객체를 사용하는 방식은 둘 다 model에 data를 담아 view를 렌더링하는 역할을 하고 있습니다. 개인적으로 ModelAndView객체를 사용하여 return ModelAndView(view, model) 방식으로 리턴해주는 것이 명시적으로 좋아보였는데, Model을 주입 받는 방식으로 사용하니 훨씬 더 코드가 깔끔해진 느낌이 드네요!

2022-05-01 08:30 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +    public ModelAndView insertGame(RoomDto roomDto) {
스티치의 말씀대로 새로운 데이터를 넣을 때에는 POST가 맞겠네요! restartGame 메소드는 데이터베이스에 있는 값을 수정하는 메소드이므로 PUT으로 수정해주었습니다. 수정하니 movePiece 메소드와 Mapping 방식과 url 모두 중복되어 movePiece의 url을 수정해주었습니다.

2022-05-01 08:40 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +        chessService.updateBoard(gameId, moveDto.getFrom(), moveDto.getTo());
updateBoard라는 이름은 처음 코드를 보는 입장에서 보면 너무 추상적인 이름일 수도 있겠네요. 도메인의 구체적인 행위가 나타나도록 movePiece라는 이름으로 수정하였습니다!

2022-05-01 08:41 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +        chessService.endGame(gameId);
감사합니다!

2022-05-01 08:41 UTC, brorae commented on src/main/java/chess/dao/FakeBoardDao.java
> +public class FakeBoardDao implements BoardDao {
test 패키지에 위치하도록 위치를 수정하였습니다!

2022-05-01 09:04 UTC, brorae commented on src/main/java/chess/controller/WebController.java
> +        chessService.insertGame(roomDto, new ChessBoard(new NormalPiecesGenerator()));
처음에는 외부에서 board를 주입하는 방식을 사용하지 않았습니다. ChessServiceTest에서 SelectWinner 메소드의 테스트를 작성하려고 하다보니 외부에서 주입받아 사용하는 방식이 테스트에 조금 더 용이하다고 생각이 들었습니다. SelectWinner의 로직은 다음과 같습니다. 
1. DB에서 게임의 상태와 보드를 불러와서 ChessGame을 만듭니다.
2. ChessGame에서의 ChessBoard가 왕의 개수가 1개인지 확인합니다. (보드에서 왕이 2개라면 게임이 끝나지 않은 것)
3. 왕의 개수가 1개인 색이 Winner입니다.

ChessBoard를 외부에서 주입 받지 않는다면 게임에서 왕을 잡기위해 chessService.movePiece(gameId, from, to)의 메소드를 왕이 죽을때까지 호출해주어야 Winner를 얻을 수 있게됩니다. 따라서 테스트의 용이성을 위해서 ChessBoard를 외부에서 주입받는 방식을 사용했는데, 적절하지 못한 방식일까요?

2022-05-01 09:05 UTC, brorae commented on src/main/java/chess/service/ChessService.java
> +        return new StatusDto(scores.get(Color.WHITE), scores.get(Color.BLACK));
스티치의 말씀대로 scores를 바로 넘겨주면 로직을 노출하지 않을 수 있을 것 같네요! 수정하였습니다.

2022-05-01 09:36 UTC, brorae commented on src/main/java/chess/service/ChessService.java
> +    }
RoomDto의 생성자에서 검증하도록 수정하였습니다. Client에서 Controller로 값이 전달될 때 검증 로직과 일치하지 않으면, IllegalArgumentException을 바로 발생시킬줄 알았는데, BeanInstantiationException이 먼저 발생하는 것을 알게되었습니다. ErrorController에서 해당예외를 처리하도록 수정했습니다!

2022-05-01 09:59 UTC, brorae commented on src/main/java/chess/dto/BoardDto.java
> +    public ChessBoard toEntity() {
스티치의 말씀에 동의합니다! 프로덕션 코드에는 테스트 용도로 사용되는 코드는 없어야된다고 생각합니다. FakeBoardDao에서 해당 메서드 로직을 직접 사용하도록 수정하였습니다!

2022-05-01 11:06 UTC, brorae commented on src/main/java/chess/service/ChessService.java
> +        int id = gameDao.save(roomDto.getTitle(), roomDto.getPassword(), chessGame.getState().toString());
toString의 사용 용도는 스티치의 말씀처럼 해당 객체의 상태를 출력하게 하여 디버깅 할때 유용하게 사용할 수 있는 것 같습니다. 따라서 production 코드를 위한 toString 사용은 지양하는 것이 좋다고 생각합니다. toString을 DB에 값을 저장하는 용도로 사용한다면, 다른 사람이 내 코드를 볼 때 상태를 확인하기 힘들수도 있겠다는 생각이 들었습니다. toString 메서드 대신 getValue라는 메서드를 두어 DB값에 저장할 수 있도록 수정했습니다.

2022-05-02 14:23 UTC, lxxjn0 commented on src/main/java/chess/controller/WebController.java
> +        chessService.insertGame(roomDto, new ChessBoard(new NormalPiecesGenerator()));
아 아닙니다!! 적절히 잘 사용하신 것 같아요 👍🏼 
제가 리뷰할 때는 NormalPiecesGenerator로 생성하는 로직만 있었는데 현재는 테스트 로직에서 사용되고 있군요!! 테스트하기 좋은 구조로 개선한 점 좋네요 💯

2022-05-02 15:25 UTC, lxxjn0 requested changes
레넌, 피드백 반영한 부분 잘 봤습니다!! 코드가 훨씬 더 깔끔해진 것 같네요 :)

이번에는 기존 코드에서 개선해볼만한 부분에 대해서 리뷰를 조금 달아놨어요!! 가장 중점적으로 봐야 할 부분은 기존 console 중심적인 로직에 대한 개선입니다!! 제가 리뷰를 달아둔 부분은 일부분이지만 전체적으로 한번 검토해보고 개선해보면 좋을 것 같아요 (직접 문자열 입력을 줘서 로직을 실행하는 부분 등)

그리고 매직 넘버들도 많이 보이는데 그런 부분들도 한번 체크해서 개선해주면 좋을 것 같아요 👍🏼

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/domain/state/State.java
> +        if (value.equals("BlackTurn")) {
여기서 비교하는 값으로 사용되는 `BlackTurn` 과 같은 값을 상수로 관리해보는 것은 어떨까요?? 그럼으로 얻을 수 있는 장점은 어떤 것들이 있을까요??

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +    }
해당 로직을 한번 간결하게 바꿔볼 수도 있을 것 같아요!!

만약 GameDto에서 Game 객체를 받아서 GameDto를 생성하는 정적 팩토리 메서드 `of`가 있고 이를 활용해서 한번 코드를 작성해 본다면

```suggestion
    public List<GameDto> findGame() {
        return gameDao.findAll().stream()
                .map(GameDto::of)
                .collect(Collectors.toList());
    }
```

이런 식으로 간결하게 바꿔볼 수도 있을 것 같아요!! :)

> 이번 코멘트는 코드적인 부분에 대한 코멘트여서 스타일의 차이가 있을 수 있어요!! 레넌이 기존의 코드의 스타일이 좋다면 기존의 스타일을 가져가는 것도 좋아요 :) 한번 다른 관점의 코드 작성 스타일도 있다는 정도로 봐주시면 좋을 것 같아요 👍🏼

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +        chessGame.playGameByCommand(GameCommand.of("start"));
`start` 문자열로 커멘드를 만들고, 이를 사용해서 게임을 실행시키는 것은 console 로직에 종속적인 메서드가 된 것처럼 보여져요. 한번 개선해보는 것은 어떨까요??

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/dao/GameDao.java
> +    int save(String title, String password, String state);
해당 메서드는 Game 클래스를 파라미터로 받으면 더 간결하게 처리될 수 있을 것 같아요!!

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/dao/BoardDaoImpl.java
>                  .collect(Collectors.toList());
dao에 너무 로직이 많이 있는 것 같아요!! save를 할 때 사용할 dto를 한번 만들어 보는 것은 어떨까요?? 
chessBoard 구조 그대로 저장을 한다면 괜찮지만 현재 jdbc를 사용할 때는 직접 저장할 수 있는 구조로 컨버팅이 필요할 것 같아요(현재 로직처럼요!!)
그래서 그러한 로직을 dto에서 처리해주면 책임을 더 분리할 수 있을 것 같아요!!

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/dao/GameDaoImpl.java
> +public class GameDaoImpl implements GameDao {
dao에서 RowMapper를 사용하면 원하는 클래스 형식으로 처리가 가능할 것 같아요!! 해당 dao와 boardDao에서도 object로 받아서 처리하는 부분이 있던데 한번 RowMapper를 사용해보는 것은 어떨까요??

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
>          return new BoardDto(board);
내부에 반복문의 경우 entrySet을 사용하면 더 간결하게 바꿀 수 있을 것 같아요!! 그리고 PieceDto에서도 Piece를 받아서 생성해본다면 또 한번 개선이 될 수 있을 것 같아요!! 도메인 객체가 dto에 의존하는 것은 안되지만 dto가 도메인 객체에 의존하는 것은 의존의 방향이 문제가 되지 않습니다. 이러한 의존을 잘 사용한다면 다양한 생성 메서드들을 제공할 수 있고, 그로 인해 많은 코드들이 간결하게 개선할 수 있을거에요 :)

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/resources/application.yml
>        on-profile: "test"
테스트에서만 사용하는 프로파일의 경우에는 test 패키지의 하위 resources에 application.yml에 설정하는 것도 좋을 것 같아요!! 그렇다면 main 패키지에서는 프로덕션만을 위한 프로파일, test 패키지에서는 테스트만을 위한 프로파일을 관리할 수 있어요 👍🏼

2022-05-02 15:25 UTC, lxxjn0 commented on src/main/java/chess/service/ChessService.java
> +        }
앞서 Game에서 password를 가져와서 밖에서 비교하는 방법 말고 좀 더 좋은 방법이 없을까요? :)

2022-05-03 15:45 UTC, brorae commented on src/main/java/chess/domain/state/State.java
> +        if (value.equals("BlackTurn")) {
State에서 사용했던 “BlackTurn”과 같은 상수는 StateName Enum에서 관리하도록 수정하였습니다. 또, Piece에서 사용했던 “WHITEKING”과 같은 상수도 PieceName Enum에서 관리하도록 수정하였습니다. Enum에 모아서 처리하도록 하니 상수의 값이 변경이 일어났을 때, Enum 한 곳에서만 처리해줄 수 있다는 점에서 장점이 있었습니다. 코드의 가독성도 올라간다고 점에서도 이점이 있다고 생각합니다. 기존 State와 Piece에 있던 state와 piece의 생성 로직을 Enum을 만듦으로써 if문을 줄일 수 있었습니다.

2022-05-03 15:47 UTC, brorae commented on src/main/java/chess/dao/GameDao.java
> +    int save(String title, String password, String state);
수정했습니다! :)

2022-05-03 15:49 UTC, brorae commented on src/main/resources/application.yml
>        on-profile: "test"
처음 미션을 구현할 때, 이상하게 작동이 잘 되지 않아서 application.yml 파일 하나에 main과 test를 나누어서 profile을 관리했었는데, 지금 분리하여 보니 정상 작동하네요. 감사합니다 :)

2022-05-03 16:22 UTC, brorae commented on src/main/java/chess/dao/BoardDaoImpl.java
>                  .collect(Collectors.toList());
감사합니다 :)

2022-05-03 16:23 UTC, brorae commented on src/main/java/chess/service/ChessService.java
>          return new BoardDto(board);
감사합니다 :)

2022-05-03 16:38 UTC, brorae commented on src/main/java/chess/service/ChessService.java
> +        chessGame.playGameByCommand(GameCommand.of("start"));
movePiece 메서드를 제외하고 수정하였습니다. `chessGame.playGameByCommand(GameCommand.of("move", from, to);` 이 부분에서 move의 턴이 바뀌는 로직과 예외가 발생하는 로직이 모두 구현되어 있어서 해당 메서드는 수정하지 못하였습니다 :(

2022-05-04 02:17 UTC, brorae commented on src/main/java/chess/dao/GameDaoImpl.java
> +public class GameDaoImpl implements GameDao {
코드의 중복도 줄어들고, 훨씬 더 가독성이 높아지는 것 같아요!

2022-05-04 08:33 UTC, brorae commented on src/main/java/chess/service/ChessService.java
> +        }
Game에 메시지를 보내서 비교하도록 수정했습니다!

2022-05-04 11:12 UTC, lxxjn0 approved these changes
레넌, 피드백 반영하느라 수고 많으셨습니다!!

처음 작성한 코드보다 훨씬 더 발전한 코드로 마무리 지어주신 것 같네요 :) 그간 미션 진행하시느라 수고 많으셨습니다 💯 

다음에 또 만나요 😄

2022-05-04 11:13 UTC, merged