[Spring 체스 - 2단계] 봄(장보미) 미션 제출합니다.
woowacourse/jwp-chess pull request #479
Opened 2022-04-30 13:59 UTC by JangBomi

안녕하세요 제이 :) 

2단계도 잘 부탁드립니다!!

2022-05-02 15:30 UTC, jjj0611 requested changes
안녕하세요 봄! 리뷰어 제이입니다!

구현해주신 코드 잘 봤습니다.
고민이 필요한 부분들 간단하게 코멘트 드렸어요!

확인 부탁드리고, 이해하기 어려운 부분이 있다면 코멘트나 DM으로 알려주세요!

2022-05-02 15:30 UTC, jjj0611 commented on docker/db/mysql/init/init.sql
> +);
절대적이진 않지만 [이 글](https://killu.tistory.com/52)을 한 번 참조해보시겠어요?

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/controller/ChessControllerAdvice.java
> +    }
현재 애플리케이션에서 발생할 수 있는 에러가 IllegalArgumentException밖에 없을까요??

2022-05-02 15:30 UTC, jjj0611 commented on src/test/java/chess/PieceDaoTest.java
> -        jdbcTemplate.execute("DROP TABLE PIECES IF EXISTS");
이 부분 코멘트 드리려고 했는데 수정해주셨네요! 👍
어떤 코멘트를 드리려고 했는지는 이미 알고 계시리라 생각합니다 :)

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/entity/GameEntity.java
> +public class GameEntity {
entity와 model을 분리하셨는데, entity는 db에 저장되는 데이터들이고, model은 기존 domain의 역할을 하는 것으로 생각이 되는데, 패키지 분리를 entity와 model로 명명한 이유가 있을까요??

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +        return WebBoardDto.from(chessGame.getBoard());
ChessGame이라는 domain과 db에 저장하는 방식이 너무 별개로 취급되고 있는거 아닐까요??

 ChessGame을 통해 게임을 진행시켰다면, 진행된 결과물을 가지고 저장을 해야하지 않을까요? 진행에 성공해서 아무일도 없었다 == 그 데이터로 저장해도 되겠다가 아니라 진행에 성공해서 아무 일도 없었다 == 진행에 성공한 결과물을 저장해야겠다 와 같은 방식이 되어야 하지 않을까요??

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/model/dto/GameInfoDto.java
> +public class GameInfoDto {
dto는 보통 요청과 응답에 대한 역할을 갖게 됩니다. 그것에 따라 조금 더 명시적으로 표현해보면 어떨까요??

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/controller/ChessGameController.java
> +        chessService.deleteByGameId(confirmPwd, id);
delete를 했을땐 상태코드 자체를 내려주지 않네요! 의도한 것인가요?

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/controller/ChessHomeController.java
> +        return ResponseEntity.created(URI.create("/")).build();
created 상태 코드는 무엇을 의미하나요?
어떤 데이터를 포함해야 한다고 명시되어 있나요?
지금 내려준 데이터는 그 명세에 적합한가요??

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/model/ChessGame.java
> +        throw new IllegalArgumentException("움직일 수 없는 위치입니다.");
```
        if (!canMove(source, target, sourcePiece, moveType)) {
            throw new IllegalArgumentException("움직일 수 없는 위치입니다.");
        }
        board.move(sourcePiece, source, target);
```

이런 방식은 어떤가요??

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/model/GameResult.java
> +        if (board.countKing() == 1) {
기존에 게임 로직에 어떤 문제가 있었어서 추가하게 되었나요??

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +    private final GameDao gameDao;
dao를 사용하면서 예외가 발생하면 어떻게 되나요??

2022-05-02 15:30 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +            gameDao.update(turn.finish(), id);
만약 54번 라인에서 updateGame에 성공하고, 56번 분기문이 true가 나와서 57번 라인으로 들어갔다가 57번 라인 update를 하다가 예외가 발생하면 어떤 문제가 발생할 수 있을까요??

2022-05-03 08:09 UTC, JangBomi commented on docker/db/mysql/init/init.sql
> +);
참고해서 수정했습니다!!

2022-05-03 08:12 UTC, JangBomi commented on src/main/java/chess/model/GameResult.java
> +        if (board.countKing() == 1) {
기존 게임 로직에서 흑이 백의 왕을 죽여도, 흑의 점수가 백의 점수보다 낮다면 흑이 패배하는 오류가 있어서 이 부분 수정했습니다 :)

2022-05-03 09:26 UTC, JangBomi commented on src/main/java/chess/entity/GameEntity.java
> +public class GameEntity {
처음에 model이라고 패키지 이름을 붙인 이유는, MVC 패턴에서 model의 역할을 하는 것이 도메인이라고 생각하고 모아놓은 것이었습니다!
이후에, dao에서 테이블의 한 row를 가져올 수 있는 객체가 필요해서, entity라고 이름을 짓고 하위에 class파일을 모아뒀습니다. 당시에 패키지 분리를 했을 때는, `이게 도메인은 아니잖아` 라는 생각에 entity 패키지를 따로 분리했는데, 제이의 질문을 들으니 고민이 되네요.
제가 생각한 패키지 분리 방법은
1. model 패키지 내에 entity 패키지를 위치한다.
- MVC 의 구조로 패키지를 분리하게되면, Entity는 controller나 view 가 아니라 model 내부에 위치하면 되겠다고 생각했습니다
2. controller/view/domain/entity/dao로 패키지를 분리한다.
- 기존 domain의 역할을 하는 model 패키지 이름을 domain으로 바꾸고, model 패키지 내에 존재하는 dao를 패키지 외부로 위치한다.
두 가지인데, 제이의 생각도 궁금합니다 :) 👍

2022-05-04 12:07 UTC, JangBomi commented on src/main/java/chess/model/dto/GameInfoDto.java
> +public class GameInfoDto {
Dto란 네이밍 대신, 요청과 응답에 따라 Request, Response를 사용하여 수정했습니다!

2022-05-04 12:17 UTC, JangBomi commented on src/main/java/chess/controller/ChessGameController.java
> +        chessService.deleteByGameId(confirmPwd, id);
delete 행위의 반환값이 void이기 때문에 상태코드가 필요없다고 생각했었는데, 제이의 리뷰를 보고 공부해보니 204 no content 라는 상태코드가 있어서 적용했습니다 :)

2022-05-04 13:20 UTC, JangBomi commented on src/main/java/chess/service/ChessService.java
> +        return WebBoardDto.from(chessGame.getBoard());
MoveResult 객체를 도입해 수정했습니다!

2022-05-04 13:24 UTC, JangBomi commented on src/main/java/chess/controller/ChessControllerAdvice.java
> +    }
발생할 수 있는 다른 오류를 해결하기 위해 Exception에 대한 ExceptionHandler를 추가하여 수정했습니다.
혹시 이외에도 다른 해결책이 있을까요?

2022-05-04 13:34 UTC, JangBomi commented on src/main/java/chess/controller/ChessHomeController.java
> +        return ResponseEntity.created(URI.create("/")).build();
[RFC7231 명세](https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.2) 

Location의 값을 명세에 따라 /games/{gameId}로 수정했습니다!

2022-05-04 14:10 UTC, JangBomi commented on src/main/java/chess/service/ChessService.java
> +            gameDao.update(turn.finish(), id);
문제에 대해 고민해봤는데, 제가 생각한 문제 상황은 `메서드가 한 트랜잭션으로 묶이지 않았을 경우, updateGame()의 동작과 gameDao.update(turn.finish(), id) 가 따로 관리 `되어 문제가 발생하는 상황이었습니다. 

기존에 Dao에서 예외가 발생할 경우 지금까지의 변경을 롤백할 수 있도록 한 트랜잭션으로 관리하기 위해 Service에 @transactional 어노테이션을 사용했기 때문에, 위의 문제 상황에 대비할 수 있을거라고 생각을 했고, 
상황을 확인해보기 위해 57번 line의 update 메서드를 항상 예외를 발생시키는 update2 메서드로 수정한 후, 56번 분기문이 true가 나오는 상태를 만들었을 때, gameDao.update2() 에서 예외 발생 시 전체 동작(상단 updateGame 메서드 내부에서 일어나는 동작)이 커밋되지 않고 모두 롤백되는 것을 확인했습니다!

혹시 제이가 위 코멘트를 남겨주신 이유에 대해 여쭤봐도 될까요?

2022-05-04 14:11 UTC, JangBomi commented on src/main/java/chess/service/ChessService.java
> +    private final GameDao gameDao;
[아래 코멘트](https://github.com/woowacourse/jwp-chess/pull/479#discussion_r864880191)에서 함께 답변했습니다 :)

2022-05-04 14:11 UTC, JangBomi commented on src/main/java/chess/model/ChessGame.java
> +        throw new IllegalArgumentException("움직일 수 없는 위치입니다.");
위의 방식을 사용하여 수정했습니다!

2022-05-04 14:12 UTC, JangBomi commented
제이 안녕하세요! 남겨주신 코멘트에 대해 답변 및 질문 남겼습니다 :) 확인 부탁드려요 감사합니다 제이 👍 👍 👍

2022-05-06 15:24 UTC, jjj0611 commented on src/main/java/chess/model/ChessGame.java
> +        throw new IllegalArgumentException("움직일 수 없는 위치입니다.");
넵 꼭 저런 방식을 사용해야하는 것은 아니고, 혹자는 not이 붙어서 이해하기 어렵다는 이야기를 하기도 하는데,
저는 기존의 방식에서 return문이 빠져도 컴파일이 잘 되고, 문제를 발견하기 어렵다는 생각이 들더라구요.
그래서 한 번 제안드려보았습니다 :)

2022-05-06 15:28 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +            gameDao.update(turn.finish(), id);
오 넵 트랜잭션에 대한 말씀을 드린것이었어요!
move dto에 따라 game은 업데이트가 되었는데, turn이 반영이 안되는 등의 상황이 발생할 수 있다는 의미로 드린 코멘트였습니다.
트랜잭션의 개념에 대해 이해하고 있는지를 여쭤보고 싶어서 드린 코멘트였는데,
제가 위에 어노테이션을 달아두신 걸 못 보기 지나쳤네요!

트랜잭션의 개념에 대해 이해하고 있다면 넘어가주세요 :)

2022-05-06 15:42 UTC, jjj0611 approved these changes
안녕하세요 봄! 리뷰어 제이입니다.

코멘트 반영해주신 부분 잘 봤습니다 👍
살짝만 코멘트 더 추가해드렸으니, 확인부탁드려요.

이해가지 않는 부분이 있다면 DM 부탁드려요!
코멘트는 드렸지만, 코드는 머지해도 될 것 같아서
체스는 여기서 이만 머지하도록 하겠습니다!

고생하셨어요!

2022-05-06 15:42 UTC, jjj0611 commented on src/main/java/chess/model/GameResult.java
> +        if (board.countKing() == 1) {
이런 방식으로 분기치지 않아도, 승 패를 판단하는 로직에서 커버할 수 있지 않을까요???

2022-05-06 15:42 UTC, jjj0611 commented on src/main/java/chess/model/dao/GameDao.java
> +    public String findPwdById(Long gameId) {
축약하지 마라는 더 이상 유효하지 않은걸까요?!

2022-05-06 15:42 UTC, jjj0611 commented on src/main/java/chess/service/ChessService.java
> +        throw new IllegalArgumentException("비밀번호가 올바르지 않습니다.");
봄 조금 이상하지 않나요...?
우리는 분명 객체지향에 대해 고민하고 있었는데,
패스워드라는 개념이 들어왔음에도 불구하고, 
chessGame 도메인에도 패스워드는 반영이 되어 있지 않고,
그렇다고 Room이라는 도메인이 생성되지도 않았네요!

비밀번호는 도메인이 아닌걸까요??
고민해보시고, 추후 미션을 진행하면서 계속 신경 써주시면 좋을 것 같아요 :)

2022-05-06 15:42 UTC, jjj0611 commented on src/main/java/chess/entity/GameEntity.java
> +public class GameEntity {
저는 좀 더 2번에 가까운 방법으로 분리를 할 것 같긴한데요.
여기에 플러스로 엔티티의 개념에 대해서도 한 번 학습해보시면 좋을 것 같습니다 :)

2022-05-06 15:42 UTC, merged