[Spring 체스 - 2단계] 조시(조현근) 미션 제출합니다.
woowacourse/jwp-chess pull request #489
Opened 2022-05-02 01:57 UTC by hyunrrr

희봉 안녕하세요! 미션 너무 늦게 제출해서 죄송합니다..
2단계 기능구현과 더불어 dao와 repository계층을 분리하는데 집중하면서 미션 진행했습니다!
시간이 많이 부족해서 생각을 많이 해보지는 못했네요ㅜㅜ
db테이블 create쿼리는 /src/main/resources/schema.sql에 적었습니다!! 감사합니다

2022-05-02 13:41 UTC, heebong requested changes
안녕하세요, 조시! 리뷰어 희봉입니다. 😄 
미션을 잘 구현하셨네요 👍 고생하셨습니다 👏  특히 `repository`와 `dao`의 차이점을 고민하신게 느껴집니다 💯 
추가로 생각해볼 내용을 코멘트로 남겼어요. 확인 부탁드립니다. (advanced로 남긴 부분은 바로 하지 않아도 괜찮아요 🙂) 궁금한 내용이 생기면 언제든 DM 보내주세요!

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/view/WebInputView.java
> +public class WebInputView {
이건 밸리데이션으로 보이는데, 적절한 이름일까요? 🤔

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/repository/GameRepository.java
> +    public int saveGameGetKey(String turn) {
advanced 🆙 [CrudRepository](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html) 인터페이스가 어떤지 확인하면 힌트가 될 것 같아요 🙂

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/repository/GameRepository.java
> +    public Color getColorFromStorage(int gameId) {
`FromStorage` 혹은 `ToStorage`가 이름에 노출될 필요가 있을까요? 🤔

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +        pieceRepository.saveAllPieceToStorage(gameId, new BoardInitializer().init());
`new Board()`를 안하고 `new BoardInitializer()`을 하는 이유가 있을까요?

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +        if (password.equals(deleteRequestDto.getPassword())) {
advanced 🆙 구현하는데 여러 방법이 있을 것 같아요. 어떤게 좋을지 생각해보면 좋겠습니다 🙂 
1. Id로 Room을 조회
2. Room의 pw와 리퀘스트의 pw가 같으면 삭제

혹은

1. id와 pw로 room을 조회
2. 조회가 되면 삭제

password라는 낱개 데이터를 사용하지 않고 room(여기서는 RoomDto가 되겠네요) 객체를 사용하는거랑 어떤게 다를까요? 고민해봐도 좋을 것 같아요 🙂

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +        return DeleteResponseDto.fail();
`fail`로 리턴을 하네요. 비밀번호가 달라도 http status 코드는 200으로 떨어지겠네요. 좋은 API일까요? 🤔 
이미 `exceptionHandler`를 사용하고 있으니 throw exception을 해도 괜찮지 않을까요?

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/controller/WebController.java
> +    @DeleteMapping("/games")
`DeleteMapping` 사용 👍

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/controller/WebController.java
> +    @GetMapping("/restart/{id}")
`restart`는 `재시작`으로 게임을 새로 시작하는 의미를 가지는 것 같아요. 실제로 `이전게임을 불러오는` 기능이라 `load`가 더 어울리지 않을까 합니다.

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/controller/WebController.java
> +    @GetMapping("/start/{id}")
이것도 실제로는 `새로운 게임을 시작`하는거라 `start`보다 `reset`이 더 어울리지 않을까요? 🤔

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +        ChessGame chessGame = new ChessGame(new Running(gameRepository.getColorFromStorage(gameId),
한 줄에 new가 많아서 가독성을 위해 몇개는 변수로 빼도 좋을 것 같네요 🙂

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +        ChessGame chessGame = new ChessGame(StateFactory.of(gameRepository.getColorFromStorage(gameId),
`gameRepository.getColorFromStorage(gameId)`, `pieceRepository.getBoardFromStorage(gameId)`가 굉장히 여러번 반복되네요. `private` 함수로 빼면 어떨까요? `private` 함수 으로 빼면 어떤점이 좋을까요? 😄 

hint 🖊️ repository 함수 이름을 변경한다면 (getColorFormStorage -> getColor) 지금은 4라인이 변경될거에요. 만약 `private` 함수로 뺐다면? 👀

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +        roomRepository.updateStatus(gameId, "PLAY");
리터럴 문자열을 사용하네요. 상수로 빼거나 enum으로 관리해도 좋겠네요 😄

2022-05-02 13:41 UTC, heebong commented on src/main/java/chess/controller/WebController.java
>      @ExceptionHandler({RuntimeException.class})
관심사를 분리하기 위해 `ExceptionHandler`는 새로운 클래스로 분리해도 좋을 것 같아요 🙂

2022-05-04 10:30 UTC, hyunrrr commented on src/main/java/chess/service/ChessService.java
> +        pieceRepository.saveAllPieceToStorage(gameId, new BoardInitializer().init());
체스게임 도메인에서 board의 책임이 너무 커서 초기화에 대한 책임을 board에서 boardInitializer로 분리했습니다!!

2022-05-04 12:10 UTC, hyunrrr commented
희봉 안녕하세요!!!
리뷰 보내주셔서 정말 감사합니다!!
advanced up은 꼭 고민해서 적용해 보겠습니다!!
아직 부족한 부분 있으면 리뷰 부탁드리겠습니다!! 감사합니다!!!!

2022-05-05 13:30 UTC, heebong approved these changes
안녕하세요, 조시! 리뷰어 희봉입니다 😄 
피드백 반영을 잘 해주셨어요 💯 미션이 겹쳐 시간이 촉박했을텐데 남긴 피드백을 모두 반영해주셨네요 👍 고생하셨습니다.
이번 미션은 여기서 마무리하도록 할게요. 추가로 고민해보면 좋을 내용을 코멘트로 남겼어요. 다음 미션을 진행하면서 같이 고민해보셨으면 좋겠습니다 🙂 언제든 궁금한 내용이 생기면 DM 주시는거 아시죠? 😉 고생하셨어요~!!

2022-05-05 13:30 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +    public List<RoomDto> loadRooms() {
advanced 🆙 dto와 도메인의 차이는 무엇일까요? `Room`은 도메인이 될 수 없을까요? 🤔

2022-05-05 13:30 UTC, heebong commented on src/main/java/chess/controller/WebController.java
> +    @GetMapping("/games")
advanced 🆙 `room`을 만드는 `api`는 `roomInformation`인데 조회하는 api는 `games`로 도메인 이름이 다르네요 😄

2022-05-05 13:30 UTC, heebong commented on src/main/java/chess/dao/GameDbDao.java
> +    private final JdbcTemplate jdbcTemplate;
advanced 🆙 jdbcTemplate을 왜 쓰는걸까요?
이번 미션의 주 내용은 spring으로 전환 및 jdbcTemplate 사용이라고 생각해요. 때문에 왜 jdbcTemplate을 사용하는지 정리하고 가면 좋을 것 같습니다.
스파크에서 사용했던 것처럼, DriveManager로 Connection을 직접 만들어서 사용하지 않는 이유는 무엇일까요? 🤔 
우선 
1. jdbcTemplate이 어디서 bean으로 등록되는지 찾아보고
2. DataSource와 jdbcTemplate의 차이점이 무엇인지
3. 왜 Connection을 직접 관리하지 않고 DataSource를 사용하는지

알아보면 기초를 다지는데 도움이 될 것 같아요 😄 

hint 1 🖊️ 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/21075774/166217620-3028eeb9-60f4-48a2-bbe9-af8328eaf307.png">
DI 받는 곳에서 버튼을 클릭하면 빈이 선언된 곳을 갈 수 있어요!

hint 2 🖊️ 
책 [자바 웹 개발 워크북] `5.12 DB 커넥션풀 5.13 DataSource와 JNDI` 읽어보기 (이제 교육장 출근하면 책 빌려읽을 수 있을거에요 🙂 )

2022-05-05 13:30 UTC, heebong commented on src/main/java/chess/service/ChessService.java
> +    public DeleteResponseDto deleteGame(DeleteRequestDto deleteRequestDto) {
advanced 🆙 `service`에서 `controller`에서 사용하는 `DeleteRequestDto`, `DeleteResponseDto`를 사용하네요. 만약 스파크, 스프링, 콘솔을 제공해야한다면 `ChessService`를 재사용할 수 있을까요? 🙂 이런 관점에서 고민해보는 것도 좋습니다.

2022-05-05 13:30 UTC, merged