[Spring 체스 - 2단계] 알파(배철환) 미션 제출합니다.
woowacourse/jwp-chess pull request #490
Opened 2022-05-02 04:32 UTC by bcc0830

안녕하세요 제이!
말씀하신 url을 넘겨주는 방식을 나름 고민했던 2단계였습니다. 2단계도 잘 부탁드립니다!

2022-05-03 12:22 UTC, JunHoPark93 requested changes
안녕하세요 알파~
2단계 구현하느라 고생하셨어요.
피드백 몇가지 남겨두었는데요, 살펴보시고 의견 및 반영 부탁드려요!

2022-05-03 12:22 UTC, JunHoPark93 commented on docs/README.md
> +- [x] 이미 끝난 게임을 삭제하는 기능
요구사항을 더 명확히 작성해보셔요. 
구현해야할 사항들이 더 잘 정리가 될거같아요~

2022-05-03 12:22 UTC, JunHoPark93 commented on src/main/java/chess/controller/WebChessController.java
> +            return RUN_EXCEPTION_URL;
컨트롤러에서 여러 로직들을 담당하고있어요. 역할에 맞는 전개일까요?

2022-05-03 12:22 UTC, JunHoPark93 commented on src/main/java/chess/controller/WebChessController.java
> +    public String gameSave(ChessForm chessForm, Model model) {
나중에 하시게 될거지만 url형식을 어떻게 가져가면 좋을지 여력이 되면 고민해보셔요!

2022-05-03 12:22 UTC, JunHoPark93 commented on src/main/java/chess/web/WebChessGame.java
> +    private RoomDAO roomDAO;
주입방식을 여러가지를 사용하고계신대 하나로 통일하는건 어떨까요?
어떤 방식을 하면 좋을지 알파가 한번 결정해보셔요~

2022-05-03 12:22 UTC, JunHoPark93 commented on src/main/java/chess/web/WebChessGame.java
> +    private Board board = new Board();
필요한 인스턴스 변수일까요?

2022-05-03 12:22 UTC, JunHoPark93 commented on src/main/java/chess/controller/WebChessController.java
> +    }
전체적으로 컨트롤러에 로직들이 많은데요, 어떻게 줄일수있을지 고민해보면 좋을거같아요!
추가로 controller만 사용하셨는데, 모든 액션에 대해서 뷰를 계속 새로 그려주는것은 의도하신건가요?

2022-05-04 02:22 UTC, bcc0830 commented on src/main/java/chess/web/WebChessGame.java
> +    private Board board = new Board();
Board보다는 State로 바꿔야 적절하다고 생각합니다.
만일 "WebChessGame이 DAO를 제외한 도메인 필드를 가져야 하냐?"라고 하신다면 저는 "필요하다"고 생각합니다.
왜냐하면 현재 저장방식이 플레이어가 매번 기물을 옮길때마다 저장하는 것이 아니라, 실제로 저장버튼을 눌러야 저장이 되기 때문입니다.
따라서, 만약 State 필드를 가지지 않는다면 사실상 이전 Board의 정보가 유일하게 있는 BoardDTO에서 가져와야 합니다. 그런데 제가 생각하는 DTO의 역할은 서비스 레이어에서 컨트롤러로 데이터를 넘겨주는 역할이라고 생각합니다.
따라서, 비즈니스 로직을 가지면 안된다고 생각합니다. 그런데 만일 BoardDTO에서 Board를 만들어주는 작업을 담당하게 된다면 비즈니스 로직을 가지기 때문에 이를 방지하면서 State를 일관되게 유지하는 방법은 WebChessGame의 필드로 존재하는 것이라고 생각합니다

2022-05-04 02:28 UTC, bcc0830 commented on src/main/java/chess/web/WebChessGame.java
> +    private RoomDAO roomDAO;
생성자 주입 방식으로 통일하였습니다!

2022-05-04 09:02 UTC, bcc0830 commented on docs/README.md
> +- [x] 이미 끝난 게임을 삭제하는 기능
수정하였습니다!

2022-05-04 09:03 UTC, bcc0830 commented on src/main/java/chess/controller/WebChessController.java
> +            return RUN_EXCEPTION_URL;
최대한 비즈니스 로직을 분리하여 수정하였습니다.
다만, 여러 상황에 따라 다른 hbs를 렌더링하기 때문에 컨트롤러에서 부득이하게 if나 try-catch문이 발생하였습니다

2022-05-04 09:15 UTC, bcc0830 commented on src/main/java/chess/controller/WebChessController.java
> +    }
model을 서비스 레이어인 webChessGame의 파라미터로 추가하여 로직을 최대한 줄이려 하였습니다!
모든 액션에 대해서 새로운 hbs, 즉 뷰 파일을 렌더링하는 것은 의도하였습니다.
왜냐하면 클릭 버튼에 따라 렌더링해야 할 정보가 달라지기에 극단적으로 하나의 hbs 파일로는 처리가 부적절하다고 생각했습니다!

2022-05-05 07:46 UTC, JunHoPark93 commented on src/main/java/chess/web/WebChessGame.java
> +    private RoomDAO roomDAO;
어떤 이유로 그렇게 하셨는지 고민하셨을거같아요. 잘 정리해두시고 추후에 활용해보셔요~

2022-05-05 07:48 UTC, JunHoPark93 commented on src/main/java/chess/web/WebChessGame.java
> +    private Board board = new Board();
@ Service 로 등록하신 클래스에 상태를 가지면 문제가 발생할 수 있습니다. 어떤 문제가 발생하는지 추후 미션을 진행하시면서 알아보시고 적용해보셔요!

2022-05-05 07:49 UTC, JunHoPark93 commented on src/main/java/chess/controller/WebChessController.java
> +    }
넵, 추후에는 데이터만 주고받는 서버를 만드시고 프런트개발자 분들과 협업을 하시게될텐데요 그때 지금과는 다른 방식을 경험하시게될거에요~

2022-05-05 07:50 UTC, JunHoPark93 approved these changes
안녕하세요 알파!
피드백 반영하시느라 고생많으셨습니다~
체스는 이만 머지할게요 다음 미션도 화이팅이에요

2022-05-05 07:50 UTC, merged